### ISSUE TITLE
add a metric to record the conf version & version of the region

### ISSUE THREAD

**Issue by siddontang** [tikv/pd#1092]
If a region's conf version is large, there may be some wrong that the PD does lots of balances for this region. 
If a region's version is large, it means the region may be hot and has a heavy write, we should pay attention to it.

We can add a histogram to record these, maybe we can also provide an API to show the top regions which have the largest version or conf version.

**Comment by rleungx** [comment]
Close it since we have supported two kinds of HTTP APIs to show the regions which have the largest confver or version.
