### ISSUE TITLE
a lot of errors unhandled found by using gosec

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#1165]
I use a tool named [gosec](https://github.com/securego/gosec) to do some security checks and list some kinds of the result as follows:
```
G204: Subprocess launched with variable (Confidence: HIGH, Severity: MEDIUM)
> exec.Command("jq", "-c", filter)
G304: Potential file inclusion via variable (Confidence: HIGH, Severity: MEDIUM)
> os.Open(d)
G404: Use of weak random number generator (math/rand instead of crypto/rand) (Confidence: MEDIUM, Severity: HIGH)
> rand.Int()
G104: Errors unhandled. (Confidence: HIGH, Severity: LOW)
> os.RemoveAll(s.server.GetConfig().DataDir)
```
Here is a final summary:
```
Summary:
   Files: 150
   Lines: 27049
   Nosec: 0
   Issues: 267
```
And most of them are `Errors unhandled`, should we handle these situations?

**Comment by gregwebs** [comment]
Yes, we should! See https://github.com/pingcap/pd/pull/1160 which adds `make check-fail` which shows all the missing error checks via `errcheck`. The output is less verbose than this `gosec. `gosec` looks like a nice tool though. I just made an additional commit to add `gosec` to `make check-fail` (it won't actually run now until `errcheck` passes).
