### ISSUE TITLE
some metrics increased too high suddenly 

### ISSUE THREAD

**Issue by sliver1001** [tikv/pd#1344]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
发送select语句，并返回结果

2. What did you expect to see?

正常返回结果，并且监控数据呈现平稳趋势

3. What did you see instead?

监控指标中某个时间短的数据曲线骤然升高
![default](https://user-images.githubusercontent.com/41311567/48995672-e3396780-f183-11e8-8a79-629636274c42.png)

4. What version of PD are you using (`pd-server -V`)?
v2.1
查看慢日志，发现有超时的SQL语句

**Comment by rleungx** [comment]
Thanks for your feedback! @sliver1001 
Can you provide more details? e.g. Which metrics has suddenly increased? How many TiKV, PD and TiDB are deployed in your cluster? What is your table structure?
