### ISSUE TITLE
pd server timeout 

### ISSUE THREAD

**Issue by victorggsimida** [tikv/pd#1411]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

 the write/read QPS ： 2k
2. What did you expect to see?

grafana : pd client  -》 pd  client cmd fail OPS : tso error:492

3. What did you see instead?

leader pd.log:

2019/01/16 13:32:48.798 log.go:82: [warning] etcdserver: [apply entries took t
oo long [365.399ms for 1 entries]]
2019/01/16 13:32:48.798 log.go:82: [warning] etcdserver: [avoid queries with l
arge range/delete range!]
2019/01/16 13:32:49.521 log.go:82: [warning] etcdserver: [apply entries took t
oo long [723.143609ms for 1 entries]]
2019/01/16 13:32:49.521 log.go:82: [warning] etcdserver: [avoid queries with l
arge range/delete range!]

2019/01/16 13:37:38.144 etcd_kv.go:119: [warning] kv gets too slow: key /pd/6499303721575278651/member/18106334223929248266/leader_priority cost 1.263445677s err <nil>

2019/01/16 14:32:50.606 log.go:82: [warning] etcdserver: [avoid queries with large range/delete range!]

follwer pd.log 

2019/01/16 13:30:15.844 heartbeat_streams.go:97: [error] [store 45276311] send
 keepalive message fail: rpc error: code = Unavailable desc = transport is clo
sing

2019/01/16 14:00:22.215 log.go:82: [warning] etcdserver: [avoid queries with large range/delete range!]

server status:
sar -q 
01:19:01 PM   runq-sz  plist-sz   ldavg-1   ldavg-5  ldavg-15   blocked
01:20:01 PM        16      1433     14.11     15.15     15.69         2
01:21:01 PM         9      1432     12.99     14.68     15.50         3
01:22:01 PM         9      1433     12.55     14.25     15.30         3
01:23:01 PM        14      1436     14.72     14.53     15.33         3
01:24:01 PM        10      1433     13.58     14.25     15.18         0
01:25:01 PM        11      1445     13.27     14.14     15.09         3
01:26:01 PM        15      1435     14.84     14.44     15.13         4
01:27:01 PM         9      1435     16.49     15.10     15.32         1
01:28:01 PM         9      1435     15.84     15.07     15.29         2
01:29:01 PM        21      1435     13.40     14.58     15.11         2
01:30:01 PM        16      1447     12.84     14.14     14.93         2
01:31:01 PM         9      1427     12.37     13.87     14.79         0
01:32:01 PM         6      1427     13.37     13.90     14.74         4
01:33:01 PM        17      1427     13.54     13.80     14.65         1
01:34:01 PM        21      1430     15.34     14.22     14.74         2
01:35:01 PM        13      1434     16.86     14.83     14.91         7

4. What version of PD are you using (`pd-server -V`)?
Release Version: v2.0.10
Git Commit Hash: 860ef894f1cae254dead276ab9d6078455b10bf1
Git Branch: release-2.0
UTC Build Time:  2019-01-03 09:25:39

**Comment by rleungx** [comment]
@victorggsimida Thanks for your feedback! 
Does your leader PD under high IO pressure?

**Comment by victorggsimida** [comment]
@rleungx 
I check
 with sar  and  not IO pressure

**Comment by rleungx** [comment]
@victorggsimida It is convenient for you to upload your PD logs (both leader and follower)?

**Comment by victorggsimida** [comment]
@rleungx 
can  I  send it to your email.  upload it here is not ok.

**Comment by rleungx** [comment]
Sure. It could be better to provide the information as much as you can.
Here is my email: rleungx@gmail.com
