### ISSUE TITLE
Reduce a replications

### ISSUE THREAD

**Issue by yqMac** [tikv/pd#1417]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
I want to Reduce a replications .I installed the tidb with ansible. I changed the "max-replicas: 2" which in  conf/pd.yml  and "ansible-playbook rolling_update.yml --tags=pd"

2. What did you expect to see?
I want to see the store size of TIKV should changed in grafana.

3. What did you see instead?
Nothing

4. What version of PD are you using (`pd-server -V`)?
ansible 2.0.6

**Comment by disksing** [comment]
Hi @yqMac , thanks for your feedback. PD only read the config file only at the first time it starts. To change config after bootstrap, you will need to use `pd-ctl` to do it online.
re https://github.com/pingcap/docs/blob/master/tools/pd-control.md
The command will be `config set max-replicas 2`.
