### ISSUE TITLE
Too frequent truncate/drop table may cause too many regions even with merge enabled.

### ISSUE THREAD

**Issue by Connor1996** [tikv/pd#1430]
PD will not merge regions with different table id. So if we truncate/drop a table, there still exists one empty region for that table in the last.  So too frequent truncate/drop table may generate too many regions.

**Comment by siddontang** [comment]
have we already met this problem now?

**Comment by Connor1996** [comment]
Noop, just some thoughts

**Comment by lhy1024** [comment]
For merge empty region, it speed up 10.8-14.57 times by #1789 and it can merge 200k empty regions in 15 mins. I think it can relieve stress from frequently truncate/drop table.

**Comment by Connor1996** [comment]
@lhy1024 Cool! But the root cause of this issue is we can't merge two regions belonging to different tables by default.

**Comment by lhy1024** [comment]
@Connor1996 We can enable the [option](https://github.com/pingcap/pd/blob/ec7cd581e0c573c245df608033c19dd2032710e9/conf/config.toml#L79) to merge two regions belonging to different tables when frequently truncate/drop table.

**Comment by Connor1996** [comment]
@lhy1024 But we only want to merge the regions belonging to dropped/truncated tables. It may merge normal regions or pre-split regions too
