### ISSUE TITLE
Improve balance region scheduler to prefer select regions with write traffic

### ISSUE THREAD

**Issue by disksing** [tikv/pd#1432]
When a large number of regions have write traffic, the hot region scheduler will not work. At this time, due to the limitation of the scheduling speed, the balance takes a long time. Selecting the region with the traffic preferentially can speed up the balance.

/cc @nolouch @rleungx @siddontang

**Comment by lhy1024** [comment]
I think current hot-region-scheduler is enough, can we close it?

**Comment by disksing** [comment]
of course
