### ISSUE TITLE
provide watch server for other component

### ISSUE THREAD

**Issue by bradyjoestar** [tikv/pd#1478]
@nolouch 

## Demand
provide watching service for other component in tidb

## Who will use it?
For PD, maybe it’s better to use its own client.ClientV3 in `server.go`?
We will mainly provide watching service for tikv, tipd.

## What will we do?
We will provide watchserver(implementation of go) and watchclient(implementation of go and rust).

## Design
- we'd better reuse the implementation of `watchserver` and `watcher` in `etcd` insteading of reinventing the Wheel.
- We couldn't directly access `etcd`  `watchserver` without `client.Clientv3`, maybe it's better to create a new grpcserver with watchserver.
- We need to connect to `watchserver` in other components, but currently we could’t create `watchclient` with `clientv3.Client`. And the etcd’s version that we use is v0.0.0-20180530235116-2b3aa7e1d49d .It couldn’t expose its `watchClient` currently. 
[https://github.com/etcd-io/etcd/issues/10581](https://github.com/etcd-io/etcd/issues/10581). maybe it's better to create our new `watchClient` and `watcher`.
- For tikv, we need to transalte the implementation of golang to rust.

## simple demo
I have write a simple demo in the [https://github.com/bradyjoestar/pd/tree/watch](https://github.com/bradyjoestar/pd/tree/watch)

### start grpcserver with watchServer
https://github.com/bradyjoestar/pd/blob/1f8b5fb637f4ae94fe9c50ff27ccf6825dbfa882/server/server.go#L210-L226

### create our new watchClient and watcher
- [watch.go](https://github.com/bradyjoestar/pd/blob/watch/watch/watch.go)
- [utils.go](https://github.com/bradyjoestar/pd/blob/watch/watch/utils.go)
- [op.go](https://github.com/bradyjoestar/pd/blob/watch/watch/op.go)

### connect to watchserver
https://github.com/bradyjoestar/pd/blob/20a680740a6e469dd3ac0cbb54eaa4a3058a5df5/watch/test/main.go#L13-L39

Here is the running result:
![Screenshot from 2019-03-25 01-54-59.png](https://upload-images.jianshu.io/upload_images/6907217-95291a88c8cbf342.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by nolouch** [comment]
cc @disksing

**Comment by nolouch** [comment]
＠bradyjoestar　we already have gRPC service in `grpc_service.go`, maybe no need to listen to a new port.

**Comment by bradyjoestar** [comment]
@nolouch Thank you!  I will read it again :smiley:

**Comment by bradyjoestar** [comment]
@nolouch  @rleungx @disksing 
I wanna to create `WatchPD` in `PDServer` and redefine our `WatchPDRequest` & `WatchPDResponse` in `pdpb.proto`
```
rpc WatchPD(stream WatchPDRequest) returns (stream WatchPDResponse) {}
```
Thus our watch service only depend on `mvcc-db` & `mvcc Event`  in etcdserver.

- `watchpd-client` in `tikv` and other component could be independent and need't to upgrade once the `clientv3/watch` changed.
-  we needn't to import `rpc.proto`  in `etcd` when we try to develop other language client. 

I have tried to write a simple demo of dependent `watchpd-client` and `watchpd-server`.  `watchserver` get the event from `mvcc`  and it send to our dependent client.
https://github.com/bradyjoestar/pd/tree/master/watch.

Is this reasonable?

Thank you!

**Comment by nolouch** [comment]
@bradyjoestar thanks! I will take a look.

**Comment by bradyjoestar** [comment]
@nolouch
This is my `pdpb.proto`
https://github.com/bradyjoestar/kvproto/blob/master/proto/pdpb.proto

:grinning:

**Comment by nolouch** [comment]
Hi, @bradyjoestar. The client is really heavy and I'm not sure it is easy to write with rust. Can we find a more easy way? like we can wrap the client in PD server and provide a single watch service.

**Comment by bradyjoestar** [comment]
@nolouch 
I'm with you on that. Even if we could write it, heavy client is hard to maintain.

Based on that you said, I will continue to think what base function should a proxy client in PDServer provide.  :ok_hand:
 
Thank you!

**Comment by bradyjoestar** [comment]
@nolouch 
I have write a simple demo here although there is a lot of work to do, if we choose it, for example watch_stream.
https://github.com/pingcap/pd/compare/master...bradyjoestar:master


I read `watchLeader` in `leader.go` and then I  think it may should provide two following function in pdpb.proto?
```
rpc GetPDKey(GetPDKeyRequest) returns (GetPDKeyResponse){}

rpc Watch(stream WatchRequest) returns (stream WatchResponse) {}
```

Thanks!

**Comment by nolouch** [comment]
@bradyjoestar  Yes, this more simple. and why not combine `GetPDKey` to `Watch`? I think you can fire a PR let us review now.

**Comment by bradyjoestar** [comment]
@nolunch
Sure,I will do it tonight :ok_hand:

**Comment by liubog2008** [comment]
How about this feature?

**Comment by nolouch** [comment]
@liubog2008  It's not in the roadmap.
close this issue first.

**Comment by nolouch** [comment]
@liubog2008  Can you tell me your needs?

**Comment by liubog2008** [comment]
I try to write a middleware to expose k8s-like API for PD so that I can reuse full k8s informer and lister codes in the operator.

However, I find that some important informations such as leader count are not stored in etcd. So I hope to know whether PD can support watch API directly.

**Comment by nolouch** [comment]
@liubog2008  We have some plans, but not yet, and the detailed path has not yet been determined.
