### ISSUE TITLE
Duplicate `Cluster` interface in `schedule`.

### ISSUE THREAD

**Issue by Luffbee** [tikv/pd#1664]
There are two similar `Cluster` interfaces in `schedule`. Maybe move this interface to package `schedule/cluster`?
https://github.com/pingcap/pd/blob/cdc87910eacc4bcbb4563add4d301aed1424da69/server/schedule/scheduler.go#L72-L86
https://github.com/pingcap/pd/blob/cdc87910eacc4bcbb4563add4d301aed1424da69/server/schedule/operator/operator.go#L51-L63

**Comment by lhy1024** [comment]
@disksing will we close it?
