### ISSUE TITLE
Provide binary packages on Github

### ISSUE THREAD

**Issue by onitake** [tikv/pd#1822]
## Feature Request

Referencing https://github.com/tikv/tikv/issues/5647 as this is also relevant for PD.

### Is your feature request related to a problem? Please describe:

Feature request

### Describe the feature you'd like:

Currently, the only download location for binary releases seems to be http://download.pingcap.org , and there is no obvious place for a list of files or checksums.

Github already provides a convenient download page for releases, it would make a lot of sense to also post binaries there, along with the tarball of each release.

### Teachability, Documentation, Adoption, Migration Strategy:

Along with posting releases on Github, it might also make sense to integrate with a public CI/CD system that posts directly to Github. It's currently somewhat unclear how binaries are built and released.

**Comment by disksing** [comment]
Thanks for your advice @onitake . We do have plans to add it :)

**Comment by rleungx** [comment]
I'm going to close it since it's stale. Feel free to reopen it.
