### ISSUE TITLE
The introduced dispersion and volatility of Region size

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#2002]
After a week of testing, it was basically determined that #1823 caused the region size to diverge and fluctuate in the second function.

### Cluster
tidb * 1 + tikv * 6 + pd * 3

### Config
```
stores set limit 128
config set region-schedule-limit 65536
config set max-snapshot-count 1024
config set max-pending-peer-count 1024
config set store-balance-rate 65536
config set high-space-ratio 0.05
config set low-space-ratio 0.25  
config set location-labels ""
```
### Branch 
#1991 #1816 cherry pick #1886+#1890
#1992 #1823 cherry pick #1886+#1890

## Result 

<p align="center">
  <img src="https://user-images.githubusercontent.com/19542290/70498369-1e20fa00-1b51-11ea-909f-103239ad5fb7.png"><br> 
  Figure 1: balance-test48 pr1991
</p>
<p align="center">
  <img src="https://user-images.githubusercontent.com/19542290/70498377-2416db00-1b51-11ea-80f9-19e185ff707d.png"><br> 
  Figure 2: balance-test58 pr1992
</p>

### coefficient of variation

#1991 |  The Proportion coefficient of variation below 0.075 | The Proportion coefficient of variation below 0.05 | The average of coefficient of variation
-- | -- | -- | --
test48 | 100.0% | 87.15% | 0.039
test61 | 99.75% | 87.59% | 0.035
test62 | 100.0% | 84.05% | 0.042
test63 | 100.0% | 85.54% | 0.043
test64 | 100.0% | 98.98% | 0.030
average | 99.95% | 88.66% | 0.038

#1992 | The Proportion coefficient of variation below 0.075 | The Proportion coefficient of variation below 0.05 | The average of coefficient of variation
-- | -- | -- | --
test58 | 20.12% | 0.02% | 0.113
test67 | 27.27% | 0.06% | 0.100
test68 | 28.29% | 0.01% | 0.093
test69 | 37.14% | 0.17% | 0.102
test70 | 29.15% | 0.11% | 0.089
average | 28.39% | 0.07% | 0.099

**Comment by lhy1024** [comment]
@disksing

**Comment by nolouch** [comment]
I think we imporve it after 5.0. close fistly.
