### ISSUE TITLE
Region size separation when importing data with release3.0

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#2071]
After a week of testing, it was basically determined that region size will separation without #1823 when speed is default.

### Cluster
tidb * 1 + tikv * 6 + pd * 3

### Config
```
config set high-space-ratio 0.05
config set low-space-ratio 0.25  
config set location-labels ""
```
### Branch 
#1991 #1816 cherry pick #1886+#1890
#1992 #1823 cherry pick #1886+#1890
tikv #tikv/6240

## Result 
<p align="center">
  <img src="https://user-images.githubusercontent.com/19542290/71617826-d0e7f380-2bf7-11ea-82b5-332076c38069.png"><br> 
  Figure 1: balance-test region size pr1991
</p>
<p align="center">
  <img src="https://user-images.githubusercontent.com/19542290/71617832-dba28880-2bf7-11ea-8cb9-014226db1984.png"><br> 
  Figure 2: balance-test operator pr1991
</p>

In the three sets of tests, the balance-region always fails to converge, and the largest region size  is twice the smallest. After turning off go-ycsb, it slowly converged after 20 hours. We think that black list block region balance.

<p align="center">
  <img src="https://user-images.githubusercontent.com/19542290/71617861-0987cd00-2bf8-11ea-9d0d-b94cf4b682f4.png"><br> 
  Figure 3: balance-test operator pr1991
</p>

There is no dispersion and volatility of Region size at slow speeds, indicating that # 1992 can adapt at low speeds.

**Comment by nolouch** [comment]
move to #2002
