### ISSUE TITLE
pd-ctl CAN NOT WORK!

### ISSUE THREAD

**Issue by roger-gs** [tikv/pd#2077]
I used ansible installed tidb-cluster,the version is v3.0.7,i use tools pd-ctl to control pd-server,but is can not work...
![image](https://user-images.githubusercontent.com/29142797/71705741-ca39c600-2e1b-11ea-8671-3a0053d28ac9.png)
this port is working...
![image](https://user-images.githubusercontent.com/29142797/71705775-f5bcb080-2e1b-11ea-83b3-8881e77f4590.png)

what can i do ??

**Comment by nolouch** [comment]
@roger-gs It looks like the connection is closed, do you make sure that the current PD is still alive?

**Comment by roger-gs** [comment]
@nolouch  PD is still alive, log file pd.log is printing like this:
![image](https://user-images.githubusercontent.com/29142797/72409487-e4bb5a00-37a0-11ea-871d-42aa170c6ff7.png)

**Comment by shafreeck** [comment]
@roger-gs It seems weird. Please check these below.
* Are all three instances of PD running?
* Which server is the leader of the cluster?
* How about using pd-ctl to connect to the leader directly?
* How about using curl: `curl http://your-leader:2379/pd/api/v1/cluster`?
* Are there any warnings or errors in the PD leader's log?

**Comment by rleungx** [comment]
Is this problem solved? @roger-gs
