### ISSUE TITLE
build: add a ci test about Dockerfile

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#2138]
### Describe your feature request related problem: 
Meet a broken change which makes `Dockerfile` do not work, we cannot found it immediately. like: #2137

### Describe the feature you'd like:

add a ci test to verify it.

**Comment by salman-bhai** [comment]
Hi just to understand are we looking at a smoke test something like this?
https://pythonspeed.com/articles/test-your-docker-build/

**Comment by nolouch** [comment]
Hi @salman-bhai , only add a test to make sure the docker image can be built. maybe add a build task on [travis](https://docs.travis-ci.com/user/docker/#building-a-docker-image-from-a-dockerfile).

**Comment by AnubhavUjjawal** [comment]
@nolouch could we add a `docker build` task to `Makefile's` https://github.com/tikv/pd/blob/c7aac753461a4ecbd136a05a108119008e4b5c8a/Makefile#L168 Then testing whether a docker image can be built or not will automatically be done in github workflow as one of the steps there in `.github/workflows/check.yaml` is `make check`?

**Comment by nolouch** [comment]
already finished.
