### ISSUE TITLE
 Supports some small regions(table) can not be merge.

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#2171]
## Description

Sometimes, some regions are hot but not large, do not merge them can improve performance. we want to specify some regions(table) can not be merge.

## Score

- 900

## Mentor

- @nolouch 

## Recommended Skills

- Go

## Learning Materials

- https://github.com/tikv/tikv/blob/master/docs/how-to/configure/region-merge.md

**Comment by mantuliu** [comment]
@nolouch My idea is to add a configuration parameter: MergeHotRegionInterval, the default value is 24 hours.
At each heartbeat of the region, a judgment logic is added. If the current region is hot, the last hot time of this reigion is stored in the memory. Maintain a map of hot regions or other data structures in memory. The merge scheduler adds a judgment condition to the region that needs to be merged, and determines whether the time when the region became hot last time is within the time range of MergeHotRegionInterval. If it is within this time range, this region will not be merged.
What do you think of this idea? This solution does not store related hot region information to disk. Some hot regions may be merged by mistake during the process of pd master-slave switch.

**Comment by nolouch** [comment]
Hi @mantuliu , are you still interested in solving this problem? We have encountered a situation where there is a small table with hot spots. After the split, we must prevent it from being merged.

**Comment by nolouch** [comment]
ongoing https://github.com/tikv/pd/issues/3839 closed this one.
