### ISSUE TITLE
Provide API to show the progress of stores which are going offline

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#2173]
## Description

Currently, it is hard for users to know how much time is left when offline a store. We should provide a way to give the estimated time to users when offline a store.

This entrance for the offline store can be found in https://github.com/tikv/pd/blob/427dd4c0a79b4fbdba26395f0acb5f460613aeab/server/api/store.go#L177. We set the store state to offline and leave it to replica checker to do the real scheduling operation. See https://github.com/tikv/pd/blob/427dd4c0a79b4fbdba26395f0acb5f460613aeab/server/schedule/checker/replica_checker.go#L64

And once a store is in an offline state, it cannot be a target for scheduling.

**Comment by hbina** [comment]
Can you update the link to the first reading material? And possibly update the Go documentations to https://pkg.go.dev/* as well.

**Comment by rleungx** [comment]
> Can you update the link to the first reading material? And possibly update the Go documentations to https://pkg.go.dev/* as well.

Updated. Please let me know if you have other questions or join our [slack channel](https://slack.tidb.io/invite?team=tikv-wg&channel=sig-scheduling&ref=github-sig) to discuss it with us.

**Comment by duduainankai** [comment]
Hi, I have read the related code and have a question.

- Does `estimated time when offline a store` mean the time that coordinator takes to move all the regions in the offline store to another one ?

**Comment by rleungx** [comment]
> Hi, I have read the related code and have a question.
> 
> * Does `estimated time when offline a store` mean the time that coordinator takes to move all the regions in the offline store to another one?

Yes. But we may offline multiple stores at a time.

**Comment by duduainankai** [comment]
> Yes. But we may offline multiple stores at a time.

So what you mean is that we should add an api to get the estimated time for moving all offline regions ?

In my understanding, move regions in offline store depending on the loop of `patrolRegions` to `ScanRegions`, but it seems not so easy or predictable to get estimated time ?

And I am also curious that why not add regions in the deleted store to `SuspectRegions` when delete a store ?

**Comment by rleungx** [comment]
> > Yes. But we may offline multiple stores at a time.
> 
> So what you mean is that we should add an api to get the estimated time for moving all offline regions ?
> 

Maybe provide an option to choose one store or all offline stores. 

> In my understanding, move regions in offline store depending on the loop of `patrolRegions` to `ScanRegions`, but it seems not so easy or predictable to get estimated time ?
> 

One possible way could be utilizing the statistic of finished offline* operators.

> And I am also curious that why not add regions in the deleted store to `SuspectRegions` when delete a store ?

Because those regions may not health enough, so we need to check them ASAP

**Comment by duduainankai** [comment]
> > > Yes. But we may offline multiple stores at a time.
> > 
> > 
> > So what you mean is that we should add an api to get the estimated time for moving all offline regions ?
> 
> Maybe provide an option to choose one store or all offline stores.
> 
> > In my understanding, move regions in offline store depending on the loop of `patrolRegions` to `ScanRegions`, but it seems not so easy or predictable to get estimated time ?
> 
> One possible way could be utilizing the statistic of finished offline* operators.

Sorry for my poor understanding, would like to give an example ?

> 
> > And I am also curious that why not add regions in the deleted store to `SuspectRegions` when delete a store ?
> 
> Because those regions may not health enough, so we need to check them ASAP

And I also didn't get this (sorry for my poor understanding again), it seems the `SuspectRegions` are check first, if we should check the regions in deleted store ASAP, then add them to SuspectRegions maybe a good choice ?

**Comment by rleungx** [comment]
> > > > Yes. But we may offline multiple stores at a time.
> > > 
> > > 
> > > So what you mean is that we should add an api to get the estimated time for moving all offline regions ?
> > 
> > 
> > Maybe provide an option to choose one store or all offline stores.
> > > In my understanding, move regions in offline store depending on the loop of `patrolRegions` to `ScanRegions`, but it seems not so easy or predictable to get estimated time ?
> > 
> > 
> > One possible way could be utilizing the statistic of finished offline* operators.
> 
> Sorry for my poor understanding, would like to give an example ?
> 

We can count the rate of finished offline* operators according to https://github.com/tikv/pd/blob/master/server/schedule/operator_controller.go#L123 and since we know the total number of offline region. Maybe we can get the estimated time?

> > > And I am also curious that why not add regions in the deleted store to `SuspectRegions` when delete a store ?
> > 
> > 
> > Because those regions may not health enough, so we need to check them ASAP
> 
> And I also didn't get this (sorry for my poor understanding again), it seems the `SuspectRegions` are check first, if we should check the regions in deleted store ASAP, then add them to SuspectRegions maybe a good choice ?

`SuspectRegions` is mainly used for split. And IMO, it's ok to put these regions into `SuspectRegions`.
