### ISSUE TITLE
offline is a misleading state

### ISSUE THREAD

**Issue by BusyJay** [tikv/pd#2450]
Currently, when deleting a node, PD will put the node to offline state first. But the node is actually online, it's just marked to be deleted.

A better alternatives is "leaving" as recommended by @CaitinChen. It has been used in the industry and can express the correct semantics.

4.0 is about to be released soon, it's better to change it at version 4.1 or 5.0.

/cc @nolouch @disksing

**Comment by rleungx** [comment]
We have introduced the `Removing` node state, and this state will be deprecated in the future. Close it for now.
