### ISSUE TITLE
Replication mode: state sync replicate not work when primary and dr disconected

### ISSUE THREAD

**Issue by disksing** [tikv/pd#2490]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
- setup replication mode to dr-auto-sync
- disconnect primary and dr DC

2. What did you expect to see?
switch the async and recover service in primary

3. What did you see instead?
cannot switch state. Because PD is also disconnected, state sync replication fails.

4. What version of PD are you using (`pd-server -V`)?
latest master

**Comment by 5kbpers** [comment]
My preliminary thought is to implement it with the [lease API of etcd](https://etcd.io/docs/v3.4.0/learning/api/#lease-api).
Each follower grants a lease which TTL is `wait_pd_timeout`, and renew the lease every `wait_pd_timeout` * 50%. After `wait_pd_timeout` * 95%, follower would think the replication state is not reliable.

**Comment by 5kbpers** [comment]
But there is the restriction is that getting the replication status and renewing the lease must be combined as an atomic operation.

**Comment by disksing** [comment]
> But there is the restriction is that getting the replication status and renewing the lease must be combined as an atomic operation.

em, sorry I don't get it. Why do we have this restriction?

**Comment by 5kbpers** [comment]
> > But there is the restriction is that getting the replication status and renewing the lease must be combined as an atomic operation.
> 
> em, sorry I don't get it. Why do we have this restriction?

😅 My original thought is that we should save the local replication mode status (stored in the file) before updating the lease.

**Comment by disksing** [comment]
I think it can be a stand alone feature, simply trace connection state between PD nodes, has nothing to do with replication mode. Then replication mode can use it to determine whether to switch state.

**Comment by nolouch** [comment]
fixed by https://github.com/tikv/pd/pull/2898/
