### ISSUE TITLE
Abnormal read traffic when insert without index and many magic number

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#2498]
![image](https://user-images.githubusercontent.com/19542290/83658346-ae1d9900-a5f4-11ea-9b18-67fa68010b88.png)
![image](https://user-images.githubusercontent.com/19542290/83658354-b1b12000-a5f4-11ea-9139-72ab57500688.png)
![image](https://user-images.githubusercontent.com/19542290/83658372-b675d400-a5f4-11ea-8658-1e2714349968.png)

**Comment by rleungx** [comment]
Does the problem still exist?

**Comment by lhy1024** [comment]
> Does the problem still exist?

maybe analyze
