### ISSUE TITLE
Support Store Leaving / Joining Progress & ETA

### ISSUE THREAD

**Issue by breezewish** [tikv/pd#2507]
### Describe your feature request related problem: 

 Scale-In and Scale-Out operation usually takes a very long time to finally finish. Progress is a must. Providing ETA (Estimated time of arrival) is even better.

### Describe the feature you'd like:

For stores being scaled-in or scaled-out, attach a metadata of leaving / joining progress to the store, or provide a way to query real time progress.

**Comment by rleungx** [comment]
Related to #2173 and #2174.

**Comment by rleungx** [comment]
Close it since it has been finished in https://github.com/tikv/pd/issues/4640#issuecomment-1063646606
