### ISSUE TITLE
Hot region scheduling considers adding QPS dimension

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#2520]
### Describe your feature request related problem
ref pingcap/tidb#18012
environment:
3 tikv + 1 pd + 1tidb
workload:
tpcc 30min （1000 or 500 warehouse）
the gRPC message is unbalanced
![image](https://user-images.githubusercontent.com/6428910/84029208-9a8f7b00-a9c4-11ea-9ae2-5eb908015d78.png)
![image](https://user-images.githubusercontent.com/6428910/84029265-b004a500-a9c4-11ea-9a7e-0cc3aff60a20.png)

But the leader of the hot region' writes flow looks:
![image](https://user-images.githubusercontent.com/6428910/84029342-cad71980-a9c4-11ea-891e-dfee116bd0df.png)

### Describe the feature you'd like
The QPS does not particularly present positively relate to the flows.
Consider introducing the QPS dimension for scheduling.

### Describe alternatives you've considered
- the request for write/read should be balanced

### Teachability, Documentation, Adoption, Migration Strategy

- Golang
- Rust

**Comment by nolouch** [comment]
cc @lhy1024 @HunDunDM

**Comment by nolouch** [comment]
ref https://github.com/pingcap/tidb/issues/18012

**Comment by XuHuaiyu** [comment]
Why the count of GRPC message sent to 172.16.5.132 is small, but the total write bytes on it is large?

**Comment by nolouch** [comment]
ref https://github.com/tikv/pd/issues/3869. close this one.
