### ISSUE TITLE
Reduce balance operator about empty region

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#2532]
### Describe your feature request related problem

There is a problem: cluster has many empty regions, we always see there are many operators of the balance region(because there has the store limit, so the balanced regions should be empty regions. )
![image](https://user-images.githubusercontent.com/6428910/84372021-1b40b800-ac0d-11ea-9572-be9efe9ab15d.png)
![image](https://user-images.githubusercontent.com/6428910/84372279-74105080-ac0d-11ea-9efc-bc75ff9621c4.png)

### Describe the feature you'd like
We may do not need to balance them.

### Teachability, Documentation, Adoption, Migration Strategy
- Go

**Comment by JmPotato** [comment]
> because there has the store limit, so the balanced regions should be empty regions

Sorry for my poor comprehension, what does this actually mean?

**Comment by nolouch** [comment]
@JmPotato I mean the balance operator is caused by the empty regions(the region size is `1`), maybe you can check the function `shouldBalance` in the `server/schedulers/utils.go`

**Comment by nolouch** [comment]
closed by https://github.com/tikv/pd/pull/3129
