### ISSUE TITLE
Placement Rules: support add `transfer-region` operator

### ISSUE THREAD

**Issue by disksing** [tikv/pd#2533]
## Development Task
From current API we cannot know each role of the peer, thus cannot support it when placement rules feature is enabled.

## Feature Request

The old way to use `transfer-region` is like following:
```sh
operator add transfer-region 126977 1 4 5
```

The request needs to point out the peer role on the store if the placement rule is enabled like following:
```sh
operator add transfer-region 126977 1 leader 4 follower 5 follower
```

**Comment by kavirajk** [comment]
If I understand correctly,  we need to support both storeIDs(1, 4, 5) and its roles (leader, follower) during transfer region.

I see two changes.
1. accept additional roles in `pd-ctl` and send it to API
2. accept additional roles at the API layer. [here](https://github.com/tikv/pd/blob/master/server/handler.go#L488)

Question: what exactly we do at the API layer, just check if those store ids match the roles that are passed before proceeding? or anything else?

any reference related to transfer-region/placement-rules would be nice!

**Comment by disksing** [comment]
Hi @kavirajk , in fact, this issue is not directly related to the placement rules feature.  Before the introduction of this feature, the long-existing replica role could only be _voter_ (means either _leader_ or _follower_), so it did not need to be specified in the API.

To fix this issue, besides the changes in `pd-ctl` side, at API layer you will need to read the request and determine in which stores the replicas of the region should be distributed, and their respective roles. After composing the target region state, you can call `operator.CreateMoveRegionOperator` to create the operator, inside `CreateMoveRegionOperator`, it uses `operator.Builder` to plan the detailed steps to transform to the target state.

We can support 4 types of roles:
- voter. Same as before
- learner. Need to set `peer.IsLearner=true`.
- leader. Need to make sure the target leader is the peer. (require some change to `CreateMoveRegionOperator`)
- follower. Need to make sure the target leader is not the peer. (require some change to `CreateMoveRegionOperator`)

**Comment by Yisaer** [comment]
clsoed in https://github.com/tikv/pd/pull/3047
