### ISSUE TITLE
Reduce the difference size amplification between the new node and the original node

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#2535]
### Describe your feature request related problem
Reduce the difference between the compression rate of the new node and the original node

![image](https://user-images.githubusercontent.com/6428910/84482225-ed6d7900-acc9-11ea-824e-2752ffb52d44.png)

### Describe the feature you'd like
the  size amplification should at the same level for the newly added node

### Describe alternatives you've considered
The ingest sst file is basically on the 5th and 6th layers. The zstd compression method is used. However, when the snapshot is generated, the lz4 compression is used by default, so that the ingest to the new tikv, it is assumed that most of the ingest to the lower Layer, the compression ratio does not change, it may cause the same store size calculation, the new tikv store used is larger

### Teachability, Documentation, Adoption, Migration Strategy
- Go/Rust/C++
- RocksDB

**Comment by rleungx** [comment]
Closed via https://github.com/tikv/tikv/pull/9947
