### ISSUE TITLE
PD as the external server of auto scaling

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#2556]
## Development Task
In order to allow the operator to combine some of the PD's distribution strategies for elastic scaling, let PD became an external service for the auto-scaler of the operator, elastic scaling according to the topology.

**Comment by disksing** [comment]
Hard for me to understand it... Could you describe it with more details?

**Comment by rleungx** [comment]
Closes it for now. If it is necessary, we can reopen it later.
