### ISSUE TITLE
Support changing store limit according to the label

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#2568]
Currently, we use the label to mark a store as a TiFlash store. It will be better to support changing store limit according to the label. We can specify the limit of stores for different labels.

**Comment by disksing** [comment]
@rleungx Please add more instructions (more context and some links) for _help-wanted_ issue.

**Comment by rleungx** [comment]
Oh, this issue can be closed at present. For the issue with the help-wanted label, I will add more detailed information next time.
