### ISSUE TITLE
evict-leader-scheduler may fail to persist configuration

### ISSUE THREAD

**Issue by disksing** [tikv/pd#2572]
It is a hypothetically speculated bug: when remove a store id from `evict-leader-scheduler`, PD first update the in-memory configuration and then persist it. If it fails to persist to etcd, the operation looks successful, but later when PD leader changes, the removed store id will come up again.

**Comment by rleungx** [comment]
Does https://github.com/tikv/pd/pull/2817 solve this problem?

**Comment by disksing** [comment]
No.

**Comment by nolouch** [comment]
maybe we can use etcd [`STM`](https://coreos.com/blog/transactional-memory-with-etcd3.html)?

**Comment by nolouch** [comment]
Could you take a look? @ZenoTan
