### ISSUE TITLE
PD can be interfered by other PDs (from another cluster)

### ISSUE THREAD

**Issue by lucklove** [tikv/pd#2606]
### What did you do?
See here: https://github.com/pingcap/tiup/issues/566

- deploy & start a cluster with 1 pd, 1 kv, 1 db
- scale-out pd
- destroy the cluster expect the scaled pd
- deploy & start the cluster with 1, pd, 1 kv, 1 db again

### What did you expect to see?
The cluster should bootstrap success

### What did you see instead?
KV can not start and it's log reports cluster id mismatch

### What version of PD are you using (`pd-server -V`)?
v4.0.0

**Comment by disksing** [comment]
Interesting! Does the PD address list configuration of TiKV contain both PD somehow?

**Comment by lucklove** [comment]
> Interesting! Does the PD address list configuration of TiKV contain both PD somehow?

Now, just one. In the new cluster, tikv doesn't know the old pd.

I guess the old pd send a join request to the new cluster... so....

**Comment by disksing** [comment]
> > Interesting! Does the PD address list configuration of TiKV contain both PD somehow?
> 
> Now, just one. In the new cluster, tikv doesn't know the old pd.
> 
> I guess the old pd send a join request to the new cluster... so....

I don't think _send a join request_ is possible, even if it did send a join request, it won't join successfully.

An interesting fact is that in the old PD's perspective, its leader is another PD, so it may redirect requests to the other PD, without  knowing that the other PD is a brand new one in a brand new cluster. I think this could be part of the reason of the problem.

**Comment by disksing** [comment]
hi @lucklove , after investigating, it turns out that the new cluster has the same cluster as the old one, so they have the same cluster id so they can communicate.
etcd has a configuration `--initial-cluster-token` to resolve this problem but PD did not expose this config.
We will support this config in PD and then you can set different token after clean up and deploy again.
