### ISSUE TITLE
TSO request may fail at the time of leader changing

### ISSUE THREAD

**Issue by JmPotato** [tikv/pd#2663]
## Bug Report

Under the current latest version of PD, TSO request may fail at the time of leader changing because `SyncTimestamp` is not yet completed but PD receives a TSO request at the same time. To fix this, we may need to check the leader lease and retry when loading TSO in memory fails rather than just return an error.

* https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/42068/pipeline
* https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/45040/pipeline/

![image](https://user-images.githubusercontent.com/1446531/87694576-f073f180-c7c0-11ea-89dd-7bd07c98121a.png)

## Notice for reopening

I reopen this issue because this bug still exists in the normal leader changing case. We may need to add a retry mechanism for PD client to address this question totally.

**Comment by nolouch** [comment]
Has it been fixed?

**Comment by JmPotato** [comment]
Fixed by https://github.com/pingcap/tidb/pull/19382
