### ISSUE TITLE
Placement Rules: support atomic helper api

### ISSUE THREAD

**Issue by xhebox** [tikv/pd#2680]
### Describe your feature request related problem

Hi, I am the mentee of the TiDB project `Define the Placement Rules in Sql`.

The current PD api makes it very hard to support this feature. Since rules will not be modified frequently, it is fine to have some extra helper APIs, such that we can avoid many problems.

For example, one statement may contain multiple rule definitions. The only way is to send HTTP request one rule by one rule. What if TiDB is down in the middle? Of course, it is possible to delete posted rules somehow later(a little bit hard). But posted rule may take effect before they are deleted.

Another example, it is good to use PD as the only source for placement rules storage. TiDB is distributed, thus there may be problems on synchronization/consistency. To update a rule, we need to get/modify/repost the old rule from PD. There is no guarantee for atomicity.

In another view, it is far better to send one HTTP request than sending many, many more requests.

I've checked that `RuleManager` is using an `RWMutex`. So it should not be hard to add new APIs.

### Describe the feature you'd like

+ An API for updating rules(overwrite modified part only)
+ An API for batch operations, uploading multiple add/delete/update in one HTTP request. So it ensures atomicity, and reduce the number of HTTP requests.

### PR track

#2688 #2699 

These api is not completely safe. See https://github.com/xhebox/pd/blob/delete/server/schedule/placement/rule_manager.go#L294-L299.

**Comment by nolouch** [comment]
Thanks, @xhebox. you are right. maybe you can help us to improve it if you are interested.

**Comment by xhebox** [comment]
@nolouch Is there anything special that I need to take care of?

**Comment by nolouch** [comment]
Maybe we can make it can be able to process multiple rules at once firstly. cc @disksing  @Yisaer

**Comment by xhebox** [comment]
Sounds good to me. My basic idea is to a generalized version of `SetRule`: `SetRules`. Before every rule is set in the map, the old value is pushed into a slice as a backup. In case there is an error, just apply the old values. Otherwise, we are done.

**Comment by nolouch** [comment]
@xhebox Do you consider handling failure situations, such as PD leader has down?

**Comment by disksing** [comment]
> Sounds good to me. My basic idea is a generalized version of `SetRule`: `SetRules`. Before every rule is set in the map, the old value is pushed into a slice as a backup. In case there is an error, just apply the old values(the slice). Otherwise, we are done.

Good idea.

**Comment by xhebox** [comment]
@nolouch Nope. Our previous discussion is based on the assumption - PD is not down. But TiDB should be able to have a retry if PD is down. This DDL job should be marked as failed.

**Comment by nolouch** [comment]
@xhebox  got it.

**Comment by xhebox** [comment]
My next target will be deletion.

After some discussions, a small change in SQL syntax leads to a way to implement `ALTER PLACEMENT` simply by deleting and adding rules. I can delete old rules, followed by a series of new rules definition. That is it.

But it should have simple pattern matching function(maybe wildcard, or simple prefix checking). The reason is https://github.com/pingcap/pd/issues/2680#issuecomment-664910593. To prevent TiDB reposting rules that have taken effects on PD, with a different ID, there is a fixed random number mixed into the ID of every rule.

The implementation idea will be same, just keep `oldRules` for backup. This idea can be generalized to `updateRules`, which needs one more map or slice of rules that needs to be persisted.

**Comment by xhebox** [comment]
Update API is still in consideration. Because I can first get all rules down, then process, then batch operations. Update seems optional. Maybe add a version to ruleManager will be better. I will consider it after further progress on TiDB.

And this issue is tracking the atomic safety issue introduced by me. Anyway, this issue will be inactive for a period of time.

**Comment by disksing** [comment]
Cool. BTW, the safety issue not introduced by you. I think it exists from the beginning.

**Comment by xhebox** [comment]
@disksing Let me report the case. It seems that I need two operations:

1. Reassign a new `ID` to a set of rules
2. Copy a set of rules and assign a new `ID`

One way is to get all rules down, locally process. And another way is to add a new update api or whatever. And here are some problems:

1. If I chose to get all rules down first, I need an extra increment counter/version to keep atomicity. How to attach that integer to the HTTP response?
2. Whatever choice you choose, PD needs to iterate over all rules, which can be a problem if there are lots of tables(meaning lots of rules).
`/config/rules/group` needs to compare groups, so do the new api. And TiDB operate rules for different databases/tables/partitions, this rises another comparison need(I only need to play with rules defined on this object, or the rules with a specific prefix).
Can there be something like a path/hierarchy store? For example, I want to store the rule with a path of `TiDB_DDL/db1/table1/partition0/$unique_id`. As a result, both the new update api and getRules can work on a small set of rules.
PD can make the `GroupID` as the path. Old `{GroupID: "g3", ID: "4"}` meaning store a rule with a path of `g3/4`. This seems back compatible.

**Comment by disksing** [comment]
Hi @xhebox Thanks you to bring up this issue. I'm thinking about introducing a new series of APIs to allow reading/writing placement rules configurations by groups.

The form is like this:

- `GET /config/placement-rules` read all rules by groups

return:
```
[
  {
    "group_id": "foo",
    "index": 0,
    "override": false,
    "rules":  [ /* rules in group foo */ ]
  },
  {
    "group_id": "bar",
    "index": 1,
    "override": true,
    "rules":  [ /* rules in group bar */ ]
  },
  ... other groups
]
```

- `GET /config/placement-rules/{group}` read rules from a group

returns

```
{
  "group_id": "foo",
  "index": 0,
  "override": false,
  "rules":  [ /* rules in group foo */ ]
},
```

- `POST /config/placement-rules/{group}` update a group

sends

```
{
  "group_id": "foo",
  "index": 1,
  "override": true,
  "rules":  [ /* rules  */ ]
},
```
It performs in a `replace` semantic which means it works just like first remove all old rules then set the received rules and finally the rules in the group will be the same as received config.

- `POST /config/placement-rules` update full configuration

sends

```
[
  {
    "group_id": "foo",
    "index": 0,
    "override": false,
    "rules":  [ /* rules in group foo */ ]
  },
  {
    "group_id": "bar",
    "index": 1,
    "override": true,
    "rules":  [ /* rules in group bar */ ]
  },
  ... other groups
]
```

It also performs in `replace` semantic.

- `DELETE /config/placement-rules/{group}` remove a group

It removes both configuration of the group and also all rules belong to the group.

----

Could you see if this new APIs can meet your needs? 

I prefer not to introduce the version number or CAS concept, which can make the API too complicated to use. In addition, the expected usage is that different clients focus on their own groups, so each group should have its own unique updater, then the load then save problem may not be a practical problem. (Maybe I am too idealistic, welcome further discuss about this)

**Comment by xhebox** [comment]
1. When TiDB truncates a partition, partition ID are changed(keyrange changed). The thing stops me from batching del/add is that I(or the RFC) want to update key-range only, but I do not know other fields of the old rules. I either needs to inform PD the key-range changes, or pull down old rules -> send updated rules.

An alternative is to store rules local copy on TiDB, like in the table metadata. But I am afraid of the synchronization problems among multiple tidb servers(I will ask my mentor later).

2. And, yes, I can store multiple groups with a flat hashmap of `groupID -> group`. One good properties of hierarchy path is that when I want to drop a database, I just need to delete all things under the path `db`. Otherwise, I need to delete `db`, `db/t1~db/tN`, `db/tN/p0~pN`. It still rises a problem when a large set of tables is created.
It will be the worst that if groups are not stored seperately. Like I said, It may need to iterate over all rules.

**Comment by disksing** [comment]
For the truncate partition problem, I think load old rules + save new rules is feasible (under the condition that there will not be multiple clients update the same rule). Store a local config copy is also an option. As far as I know, TiFlash does store a copy of rule (may not as the same format as PD's) and it checks rules in the background, if the PD configuration is accidentally modified, it can also be resynchronized.

For the second issue, I think we may support wildcard group id for `DELETE /config/placement-rules/{group}` API, just like delete rule by prefix feature.

**Comment by xhebox** [comment]
1. > under the condition that there will not be multiple clients update the same rule

It is confirmed that the ddl_worker is serial, or at least partially serial. Can not prevent user from destroying rules, though.
2. That is good. Even if you are storing a flat map `GroupID -> Group`, it is likely that this wildcard operation will be expensive. I saw that slack discussion on large numbers of tables at 8.15. So I am a bit sensitive to this penalty.

**Comment by disksing** [comment]
I think if the operation is not very frequent, we don't need to consider much about performance problems.
The APIs will be both available as they are serving different usage patterns.

**Comment by xhebox** [comment]
I see. So I can add rules by `/config/rules/batch`, alter/delete rules by this group api, pretty neat :).

OK, I am done with this issue. You can close it(need a new issue to track the safety bug). Or keep it to track the atomic safety bug of `/config/rules/batch`.

**Comment by disksing** [comment]
I think we can keep it.

**Comment by xhebox** [comment]
@disksing I have done some works on the rule cache, i.e. a local copy of rules on TiDB side.
One thing is that I can not update multiple groups at once. If I use `batch` api, I can not update `Index` and `Override` of groups. While it is probably fine, it is not so intuitive.
The reason not to use only one group is the possible large number of databases/tables(a large group at the end). That is a big cost on network transportation.

**Comment by disksing** [comment]
Good point. I didn't notice it... It seems we can add a parameter to `POST /config/placement-rules` API to control if we want to overwrite all groups or just the groups we post. How do think about it?

**Comment by disksing** [comment]
Maybe we should change `deleteByIDPrefix` to regexp too, to make it consistent.

**Comment by xhebox** [comment]
> It seems we can add a parameter to POST /config/placement-rules API.

An HTTP query parameter? Sounds good to me.

> Maybe we should change deleteByIDPrefix to regexp too, to make it consistent.

Consistency is neat. I agree with that. My point is that it is proposed to push the work to PD side, because TiDB does not have a local copy of rules. But now TiDB has one... Maybe we could just remove it after all works are done.

**Comment by xhebox** [comment]
@disksing OK, a gentle ping, I left a message on slack. Check this comment https://github.com/pingcap/tidb/pull/20166#discussion_r494004353. It may be good to set the groupID by ourselves.

**Comment by disksing** [comment]
Seems to be a good idea.

**Comment by xhebox** [comment]
@disksing @djshow832  Maybe another feature request for PD, or the RFC needs a compromise, or a complex solution needs to be done on TiDB side.

Background: https://github.com/pingcap/tidb/issues/20669#issuecomment-726603408 and https://github.com/pingcap/tidb/pull/21910.

Summary: I want a new semantic for the `override` of rules, to simplify the work of multi-level(schema/table/partition) bundles with inheritance: it will take effects in https://github.com/tikv/pd/blob/master/server/schedule/placement/rule_list.go#L159, i.e. in the same keyrange/region. Rules will first be filtered based on region, then group. And then another iteration for the new semantic.

`override` of bundles can keep its original semantic: user may not want to rely on the default bundle from PD, user may want a table not inherited from its schema.

**Detailed Description**:

GroupBundle API from PD makes it easy to implement a rule cache framework with the help of DDL schema synchronization framework. It is now pretty easy to organize rules in a managed fashion.

But ideally, I want a one to one correspondence between bundle <-> partition/table/schema to meet this requirement of tidb RFC[2020-06-24-placement-rules-in-sql.md]:

> Once the placement rules on a database or a partitioned table are changed, the inherited placement rules are also updated, but others are kept.

The easiest way to keep consistency of multiple instances(rules) is to keep only one single copy of rule. Take an example: a table has rules of 3 voters and 3 followers, so partitions of the table has 3 voters, 3 followers. Then I want to alter a specific partition to have only 2 followers, i.e. I want this special partition has 3 voters, 2 followers as a result.

Then, here comes the problem of inheritance: you will need `override: true` for the partition bundle to delete the old 3 followers rules, also you will need `override: false` for the partition bundle to inherit the 3 voters rules. And override between rules only takes effects in the same bundle, which is not helpful at all.

The only way is to copy the 3 voters rules from the table bundle to the partition bundle, i.e. what I have done in https://github.com/pingcap/tidb/pull/21910. The synchronization of rules becomes painful in this way.

**Comment by xhebox** [comment]
It is already implemented, now. so I am going to close it.
