### ISSUE TITLE
Placement Rules: Support Index and Override properties for Group

### ISSUE THREAD

**Issue by disksing** [tikv/pd#2721]
## Development Task

Sometimes, we want to control the overlay order of groups and sometimes we want specific group to override rules in other groups.

**Comment by djshow832** [comment]
Is there any scenario that groups don't need to override each other?
IMHO, new rules should always override old ones in all scenarios.

**Comment by xhebox** [comment]
@djshow832 Maybe in the process of some manual tests. Anyway, overriding is a small task compared to overlay order.

I think that he means TiDB can mark its rules with index `1` > the default rule with index `0`. So once TiDB starts to create rules, the default rule fails automatically.

**Comment by djshow832** [comment]
In original design, PD allows multiple sources of placement rules, including pd-ctl. But I don't think there's a need to distinguish them. It just complicates the system and confuses users.

**Comment by disksing** [comment]
There are different use scenarios. Normally, rules in different groups come from different sources.
Sometimes, the source of the rules needs to add some additional rules to the original rules. For example, TiFlash needs to add some extra learner peer on TiFlash nodes, without affecting original rules. In this case, `override` is false, which means that multiple groups take effect at the same time and do not interfere with each other.
In some other cases, the source of rules needs full control of data placement, then we will need to set `override` property for the group to disable other groups.

**Comment by disksing** [comment]
Task dismantling:
- [ ] consider group properties when calculating rule list
- [ ] ruleGroup load / save
- [ ] ruleGroup API + pd-ctl support
