### ISSUE TITLE
request scattering region considering table scattering distribution

### ISSUE THREAD

**Issue by Yisaer** [tikv/pd#2732]
### Describe your feature request related problem
Currently, the region scatter only consider the cluster-level region scatter distribution.  When there are multi sessions executing `split table`, it will cause the unbalance of the distribution(eg: leader) with single table's perspective.

Here's steps to reproduce (version v4.0.4):
1. enable `tidb_wait_split_region_finish` and `tidb_scatter_region` for each session.
2. execute `create table t1 (a int, b int,index idx1(a)) shard_row_id_bits = 10 pre_split_regions=8;` and `create table t2 (a int, b int,index idx1(a)) shard_row_id_bits = 10 pre_split_regions=8;` at same time by these 2 sessions.
3. check each table's leader distribution.

```sh
mysql> select count(s.region_id) cnt, s.index_name, p.store_id from INFORMATION_SCHEMA.TIKV_REGION_STATUS s join INFORMATION_SCHEMA.tikv_region_peers p on s.region_id = p.region_id where s.table_name = 't1' and p.is_leader = 1 group by index_name, p.store_id order by index_name,cnt desc;
+-----+------------+----------+
| cnt | index_name | store_id |
+-----+------------+----------+
|  42 | NULL       |        4 |
|  41 | NULL       |      105 |
|  40 | NULL       |      104 |
|  37 | NULL       |       88 |
|  35 | NULL       |      125 |
|  34 | NULL       |        1 |
|  27 | NULL       |        5 |
|   1 | idx1       |       88 |
+-----+------------+----------+
8 rows in set (0.06 sec)

mysql> select count(s.region_id) cnt, s.index_name, p.store_id from INFORMATION_SCHEMA.TIKV_REGION_STATUS s join INFORMATION_SCHEMA.tikv_region_peers p on s.region_id = p.region_id where s.table_name = 't2' and p.is_leader = 1 group by index_name, p.store_id order by index_name,cnt desc;
+-----+------------+----------+
| cnt | index_name | store_id |
+-----+------------+----------+
|  48 | NULL       |        5 |
|  40 | NULL       |      125 |
|  37 | NULL       |        1 |
|  35 | NULL       |      104 |
|  33 | NULL       |      105 |
|  32 | NULL       |       88 |
|  31 | NULL       |        4 |
|   1 | idx1       |        1 |
+-----+------------+----------+
8 rows in set (0.05 sec)
```

### Describe the feature you'd like
After splitting several tables, not only the cluster-level distribution is balanced, each single table's regions distribution is also balanced in concurrency cases.

**Comment by Yisaer** [comment]
One possible solution is to add an optional attributes in `ScatterRegionRequest` and http request post like `group (type string)`

If `group` is defined, region-scatter would scatter the region by group. If not defined, scatter will use the original logic. In this case, TiDB could set the tableID as the group so that the `split table` could be finally distributed balanced in the table level.

WDYT? @nolouch @disksing @rleungx @HunDunDM @lhy1024

**Comment by nolouch** [comment]
lgtm, BTW, you may need to gc the group. In most cases, a group may be useless if it is used once.

**Comment by Yisaer** [comment]
> lgtm, BTW, you may need to gc the group. In most cases, a group may be useless if it is used once.

nice catch.

**Comment by disksing** [comment]
sounds great. btw, maybe consider sending range(instead of many regions) directly in the future?
