### ISSUE TITLE
Move PD to github.com/tikv/pd

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#2758]
We are going to move PD to TiKV GitHub organization.
Our motivation is TiKV has a strong dependency on PD, they together form a distributed KV system.

Filing an issue to sort through what needs to be done:

- [x] Announce to TiDB/TiKV communities. (11 AM, UTC+8, August 17, 2020)
- [x] Transfer ownership
- [x] Update all internal `github.com/pingcap/pd` import paths in all branches
- [x] Set up new CIs, Bots in New Org
- [x] Reconfigure automated testing: Travis, Jenkins, Circle...
- [x] Update the `import paths` and `go.mod` of all downstream dependent projects in `pingcap`

Some relative issues:

- Can all the released TiDB versions still compile successfully?
Yes. github will [redirect all requests to the new URL](https://github.blog/2013-05-16-repository-redirects-are-here/
) and go mod download still works.
- Consider canceling the [semantic Import mechanism](https://github.com/golang/go/wiki/Modules#semantic-import-versioning) in PD
 Because we meet some problem like: Will cause cherry-pick to conflict with the lower version branch of a release, Weird dependency problems like `pd` and `pd/v4` appeared at the same time in one repo, Need to resolve lots of dependency problem after we bump to a higher version

**Comment by HunDunDM** [comment]
If we want to use vanity imports, we may need [https://github.com/GoogleCloudPlatform/govanityurls](https://github.com/GoogleCloudPlatform/govanityurls).

**Comment by disksing** [comment]
Can we close it now?

**Comment by nolouch** [comment]
yes
