### ISSUE TITLE
RegionInfo.Clone and FitRegion consume too much cpu in ruleLeaderFitFilter

### ISSUE THREAD

**Issue by Yisaer** [tikv/pd#2783]
### What did you do?
The user previously used pd v4.0.4 and found that heartbeat region event qps become lower. After downgrading to v4.0.0, the qps become normal. The cpu profile have been captured for both running pd with v4.0.4 and v4.0.0 version. We found that ruleLeaderFitFilter consume too much cpu resources in v4.0.4 comparing v4.0.0.

The placementRule is enabled and only have default rule. 

### What did you see instead?

RegionInfo.Clone and FitRegion consume too much cpu in ruleLeaderFitFilter.

![image](https://user-images.githubusercontent.com/13427348/90470059-0b81aa80-e14d-11ea-83c4-3bb5e936213c.png)

Here is the cpu profile for v4.0.4

[profile(1).gz](https://github.com/tikv/pd/files/5088196/profile.1.gz)

Here is the cpu profile for v4.0.0

[profile-400.gz](https://github.com/tikv/pd/files/5088200/profile-400.gz)

### What version of PD are you using (`pd-server -V`)?
v4.0.4

**Comment by nolouch** [comment]
![image](https://user-images.githubusercontent.com/6428910/90496555-8f9d5780-e178-11ea-9a9f-395b47862618.png)
It always has many `no-target-stores` events in 4.0.4 version.
