### ISSUE TITLE
Add a pd-ctl command to manipulate ServiceGCSafePoint

### ISSUE THREAD

**Issue by overvenus** [tikv/pd#2786]
## Feature Request

Add a command to manipulate ServiceGCSafePoint, including list and delete.

### Describe your feature request related problem

We find TiDB GC safepoint stops forwarding sometimes,  and it turns out TiCDC's ServiceGCSafePoint stops it.
For now, there is no way to inspect ServiceGCSafePoint in PD, and it is hard to debug if it happens.

### Describe the feature you'd like

```
$pd-ctl service-gc-safepoint list
$pd-ctl service-gc-safepoint delete xxx
```

### Describe alternatives you've considered

No.

### Teachability, Documentation, Adoption, Migration Strategy

N/A

**Comment by disksing** [comment]
what is the execution logic of the command? Do we need to start an etcd client?

**Comment by overvenus** [comment]
Yes, as etcd kv is the only API that could list all ServiceGCSafepoint. Or we could add a few HTTP APIs to list and delete.
