### ISSUE TITLE
The PD api `/pd/api/v1/members` show the wrong result

### ISSUE THREAD

**Issue by jyz0309** [tikv/pd#2809]
### What did you do?
I use `tiup playground nightly` to create a cluster. Then when I try to use  `tiup playground scale-out --pd 2` to scale out the num of pd, the pd api `curl http://127.0.0.1:2379/pd/api/v1/members` the members slice in the response will not show me the correct answer(just have 2 pd).And the `tiup playground display will show me the correct answer`(3 pd) 

#### a recipe for reproducing the error:
use `tiup playground nightly` to create a cluster
`tiup playground scale-out --pd 2` to scale out pd
use `curl http://127.0.0.1:2379/pd/api/v1/members` and check members slice in the response
`tiup playground display` to check the answer

### What did you expect to see?
`curl http://127.0.0.1:2379/pd/api/v1/members` will show me the correct answer.
### What did you see instead?
`curl http://127.0.0.1:2379/pd/api/v1/members` result is different with `tiup playground display`

### What version of PD are you using (`pd-server -V`)?
4.1.0-alpha

**Comment by july2993** [comment]
```
2020/08/20 19:04:57.532 grpclog.go:60: [warning] grpc: addrConn.createTransport failed to connect to {http://127.0.0.1:58653 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:58653: connect: connection refused". Reconnecting...   [2020/08/20 19:04:57.533 +08:00] [FATAL] [main.go:93] ["join meet error"] [error="there is a member that has not joined successfully"] [stack="github.com/pingcap/log.Fatal\n\t/Users/pingcap/gopkg/pkg/mod/github.com/pingcap/log@v0.0.0-20200511115504-543df19646ad/global.go:59\nmain.main\n\t/Users/pingcap/workspace/build-darwin-amd64-4.0/go/src/github.com/pingcap/pd/cmd/pd-server/main.go:93\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"]
```
when scale-out 2 pd
this is caused by the second one failed to start,  the `uptime` in the display is not right, we should show that the process is down.

currently, you can scale it one by one.
`tiup playground scale-out --pd 1`
wait for a while for the new instance to join and scale one again.

**Comment by jyz0309** [comment]
> `tiup playground scale-out --pd 1`

it work. thx 👍
