### ISSUE TITLE
Way to avoiding Alloc test error by `address already in use`

### ISSUE THREAD

**Issue by Yisaer** [tikv/pd#2839]
### Describe your feature request related problem

In current ci unit test, we will often meet `address already in use` error by `tempurl.Alloc`.  Though we set `-p 1` for the go test, we could still meet this problem (see example [here](https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/pd_test/runs/7221/nodes/38/steps/106/log/?start=0)). One way to avoid this problem is to ensure that we should never use the same address during the test.

### Describe the feature you'd like

One possible solution to achieve this target is to persist the address we have been used in a temporary file so that each test process will check their address whether have been used by other test process. To share the temporary file path by multiple test process, we can set its path into ENV.

As we only meet this problem in ci test, excluding the local test. We can use a ENV as a switch to control whether `Alloc` would persist and check the address in local file. Of course only the CI environment would set this ENV.

### Describe alternatives you've considered

We can create the tempFile and set tempFile into ENV path during CI process before the test beginning. As we are using `-p 1` param for the go test, we don't need to consider the concurrency visting to the file between multi process. In the future, we can remove the `-p 1 `limit and using `flock` to handle the concurrency visit to the file by multi process.

**Comment by Yisaer** [comment]
WDYT @nolouch @disksing @HunDunDM @rleungx

**Comment by disksing** [comment]
I think it is a good idea.

**Comment by Yisaer** [comment]
Another reason why we meet `address already used` is possibly related to `TIME_WAIT` socket status.  As our ci test environment might be used by other test process yet, there might exist the situations that the ports which used by the current test process might have been used and released by the former test process and its status is still `TIME_WAIT`.

One way to avoid this situation is to check the socket status after Alloc, if the target port status is `TIME_WAIT`, we will directly discard it and re alloc new status.

**Comment by Yisaer** [comment]
As #2841 is merged, we will observe ci status for about 1 week. If the error doesn't appear anymore, we will be going close this issue.

**Comment by rleungx** [comment]
This issue doesn't happen for a long time, close it for now.
