### ISSUE TITLE
placement: Use the Bundle API in pd-ctl

### ISSUE THREAD

**Issue by disksing** [tikv/pd#2863]
## Development Task

The new Bundle API (https://github.com/tikv/pd/pull/2846) is suitable to do batch updates. We can change pd-ctl's `load/save' commands to use Bundle API.

**Comment by xhebox** [comment]
Anyone progress? I can pick up this issue.

**Comment by disksing** [comment]
@xhebox It is not started yet. Welcome to contribute! If you have any more questions or need any help please feel free to discuss with us in this issue or in slack :)
