### ISSUE TITLE
refactor task: move `heartbeatStreams` to `server/schedule/hbstream`

### ISSUE THREAD

**Issue by disksing** [tikv/pd#2882]
### Problem
`heartbeatStreams` is a utility to help to handle heartbeat streams with tikv stores. It is implemented in `server/heartbeat_streams.go` and tests in `server/heartbeat_streams_test.go`.
As the `server/schedule` package needs to use `heartbeatStreams` (to push operators), we introduced some interfaces (`opt.HeartbeatStream` and `opt.HeartbeatStreams`).

### How to fix
Move the `heartbeatStreams` to another package (could be `server/schedule/hbstream`) then we can avoid using interfaces.

**Comment by duduainankai** [comment]
I would like to take this one if it's not been assigned.

**Comment by disksing** [comment]
@duduainankai Assigned to you! If you encounter any problems, please contact us here or on slack.

**Comment by duduainankai** [comment]
@disksing Hi, I have found some problem and maybe we would need more discussion.

- If we move heartbeatStreams to `server/schedule/hbstream`, `server` package would import `hbstream` package and `hbstream` would also import `server` at `regionHeartbeatCounter`, so it became cycle import. And move `regionHeartbeatCounter` out of `server` package seems not a good idea in my understanding.

-  Some mock test is based on mock an implementation of heartbeatstream and heartbeatstreams interface, such as mockstream. If we delete the interfaces and using a struct in `heartbeatStreams`, it seems not so easy to keep the mock implementation ?

Please correct me if I misunderstand what you mean. And actually I want to know the benefit after we avoid using interfaces.

**Comment by disksing** [comment]
I think it would be a good idea to create a new `metrics.go` in `hbstream` and declare a new metric `regionHeartbeatStreamCounter`.
I didn't realize the second issue before. I guess the first step we can remove the `HeartbeatStreams` interface and keep `HeartbeatStream`.

**Comment by duduainankai** [comment]
- Not only the metrics is imported from server, `TestActivity` in `heartbeat_stream_test` also uses `server` struct and it seems not removable ?

- `HeartbeatStreams` also has a mock implementation in mockstream. Remove the interface means we should use the `heartbeatStreams` in test, is it right ?

**Comment by disksing** [comment]
> * Not only the metrics is imported from server, `TestActivity` in `heartbeat_stream_test` also uses `server` struct and it seems not removable ?

I would like to change the test and make it test the `heartbeatStreams` more directly, without the need of creating a server instance. If it is too complex, you can keep `heartbeat_stream_test.go` and handle it later :)

> * `HeartbeatStreams` also has a mock implementation in mockstream. Remove the interface means we should use the `heartbeatStreams` in test, is it right ?

Right. I think we can use `heartbeatStreams` directly.
