### ISSUE TITLE
Refactor task: remove `ScheduleOptions`

### ISSUE THREAD

**Issue by disksing** [tikv/pd#2923]
## Development Task

Since https://github.com/tikv/pd/issues/2884 is fixed, [ScheduleOptions](https://github.com/tikv/pd/blob/ef8949587ce31e4c0d81f753e7fd1567a833abbb/server/statistics/schedule_options.go#L25) can be removed too. All usages should be able to be replaced by `*config.PersistOptions`.

**Comment by duduainankai** [comment]
I have finish this, maybe it can be assigned to me.

**Comment by disksing** [comment]
@duduainankai oh, thanks!

**Comment by duduainankai** [comment]
Should comment "/assign" be able to do self assign ?

**Comment by disksing** [comment]
> Should comment "/assign" be able to do self assign ?

Yes, you can use `/assign` to assign an issue to yourself. Or simply comment to claim an issue is also fine!
