### ISSUE TITLE
Provide a way to implement the Local TSO Allocator leader election priority

### ISSUE THREAD

**Issue by JmPotato** [tikv/pd#2943]
### Describe your feature request related problem

Part of #2759. For more details about TSO Allocator, please look at this [document](https://docs.google.com/document/d/1t4D2M5W0dqduNTey1aTute4umuEQrKazU-ipSwFAaLM/edit#heading=h.qolqioffe8ac) (In Chinese).

For the PD leader election priority, we can do this by changing the etcd leader to make the PD leader been changed because we have a constrain between the PD leader and etcd leader. But for the Local TSO Allocator leader election priority, we don't have such an easy way to move a Local TSO Allocartor leader to another.

### Describe the feature you'd like

We need to provide a new way to guarantee the following rules:

1. For example, the PD server with `dc-location="dc-1"` needs to be elected as the allocator leader with the highest priority.
2. If all PD servers with `dc-location="dc-1"` are down, then the other PD servers of DC could be elected.

We can implement this feature by introducing an extra procedure that will write some keys and values into etcd to make the election priority been guaranteed.

For Local TSO Allocator follower:

1. Each `AllocatorManager` keeps checking if its priority is higher than the current Local TSO Allocator leader by reading the leader key from etcd.
2. If it's true and `AllocatorManager` have an uninitialized Local TSO Allocator, it means this allocator is able to become the DC's Local TSO Allocator with a higher priority. Then it will write into etcd with a key-value pair like `dc-location/dc-1/next-leader: member-id`.
3. While campaigning a Local TSO Allocator leader, the `AllocatorManager` will check the corresponding `dc-location/dc-1/next-leader: member-id` key-value pair. If the member ID is not itself, it will not continue trying to campaign the leader.

For Local TSO Allocator leader:

1. While it keeps maintaining its leadership, it will also check the `dc-location/dc-1/next-leader`, then it will find that the value is not its member ID, which will make it step down and become a follower.

### Teachability, Documentation, Adoption, Migration Strategy

**Comment by Yisaer** [comment]
Before discussing the design, could you give some information or examples why local tso leader need priority?

**Comment by disksing** [comment]
I think 1-4 could be merged to:
Each `AllocatorManager` keeps check if itself's priority is higher than current tso leader, if true, it can do step4 directly.

**Comment by JmPotato** [comment]
> I think 1-4 could be merged to:
> Each `AllocatorManager` keeps check if itself's priority is higher than current tso leader, if true, it can do step4 directly.

Edited. PTAL!

**Comment by disksing** [comment]
LGTM

**Comment by Yisaer** [comment]
The design LGTM
