### ISSUE TITLE
refactor task: move `server/heartbeat_stream_test.go` to `server/schedule/hbstream`

### ISSUE THREAD

**Issue by disksing** [tikv/pd#2963]
## Development Task

Derived from https://github.com/tikv/pd/issues/2882
It requires some more updates to the unit test to make it possible to move to the new location, so we do it in a separated PR.

**Comment by disksing** [comment]
Please take a look @duduainankai

**Comment by disksing** [comment]
Hi @duduainankai I have proposed a PR to fix this issue. You may want to help review or pick other `help-wanted` issues :)

**Comment by duduainankai** [comment]
Sorry for the slow response since a busy week (I was about to write the code :(
