### ISSUE TITLE
collectHealthStatus() in server/cluster/cluster.go doesn't handle removed member

### ISSUE THREAD

**Issue by donbowman** [tikv/pd#2964]
### What did you do?

I have a pd cluster, it had pd-0/1/2 in it. it accidentally got a pd-3 somehow. I did a pd-ctl member delete on pd-3.
The /metrics endpoint still has a pd-3 even tho it no longer exists.

The reason is in server/cluster/cluster.go:

```
func (c *RaftCluster) collectHealthStatus() {
        members, err := GetMembers(c.etcdClient)
        if err != nil {
                log.Error("get members error", errs.ZapError(err))
        }
        unhealthy := CheckHealth(c.httpClient, members)
        for _, member := range members {
                if _, ok := unhealthy[member.GetMemberId()]; ok {
                        healthStatusGauge.WithLabelValues(member.GetName()).Set(0)
                        continue
                }
                healthStatusGauge.WithLabelValues(member.GetName()).Set(1)
        }
}
```

i think this function needs to unset the others before it starts, since it only iterates over current members.

### What did you expect to see?

I expect to see gauge for current members only.

### What did you see instead?

I saw the current members and the no-longer present one pd-3

### What version of PD are you using (`pd-server -V`)?

4.0.4

**Comment by disksing** [comment]
Thanks @donbowman . We will take a look.

**Comment by donbowman** [comment]
thanks so much for so fast result!
