### ISSUE TITLE
Split Regions handled by PD

### ISSUE THREAD

**Issue by Yisaer** [tikv/pd#2965]
### Describe your feature request related problem
Currently, the split table(regions) in tidb is constructed by following 2 steps:
1. Notify tikv to split regions
2. Notify pd to scatter regions

This solution has several problems listed below which will let the time cost for the whole splitting table become unstable and rather time-consuming.
1. split region without any checking ( see detailed in https://github.com/tikv/pd/issues/2733)
2. any application who wants to using scattering API with pd need to handles `backoff`

Also, as suggested by https://github.com/tikv/pd/issues/2732#issuecomment-682360248 , PD could receive the [startKey,endkey) range directly instead of regionID which could reduce the calling times.

### Describe the feature you'd like

1. PD support split regions (split keys) API with backoff and checking ability.
   - [x] implement region splitter skeleton https://github.com/tikv/pd/pull/3062
      - [x] implement sending splitting operator and watch regions changing. https://github.com/tikv/pd/pull/3072
      - [x] support asserting region valid https://github.com/tikv/pd/pull/3072
      - [x] support splitting regions in concurrency https://github.com/tikv/pd/pull/3113
   - [x] expose the region splitter by Http API. https://github.com/tikv/pd/pull/3078
2. PD support scatter regions[startKey, endKey) API with backoff and checking ability.
   - [x] region scatter supports relocate regions by keyranges or regionID. https://github.com/tikv/pd/pull/3028
   - [x] expose region scatter by Http API. #3051

The API shall be released in v5.0.

**Comment by Yisaer** [comment]
PTAL @nolouch

**Comment by nolouch** [comment]
LGTM
