### ISSUE TITLE
Record the API modification history

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#2971]
### Describe your feature request related problem

Sometimes, we want to know what kind of operations the user did. It's not convenient for us to find them through the log. The log may also be deleted. 

### Describe the feature you'd like

We should provide a way to record the modification of the PD settings through API. One possible way is to implement a middleware like [`CombinedLoggingHandler`](https://godoc.org/github.com/gorilla/handlers#CombinedLoggingHandler) but provide persistent operation. We also need to provide pd-ctl commands to show history and delete history easily. Besides, we need to limit the number of history we should keep.

The ideal output of pd-ctl might be:
```
>> history show
{
     "[16/Sep/2020:19:17:24 +0800] 127.0.0.1 username POST /pd/api/v1/config HTTP/1.1 body(maybe)"
     ...
}
```
Other kinds of formats are also ok as long as it can be understood.
We can use `history limit <number>` to limit the number of history we keep.

### Teachability, Documentation, Adoption, Migration Strategy

https://github.com/gorilla/handlers can be a reference. 
We can implement this middleware in `api` package. 
Once we implement the middleware, we can use it for all handlers which accept POST/DELETE method. e.g.
```
apiRouter.Handle("/config", handlers.HistoryHandler(io.Writer, http.HandlerFunc(confHandler.Post))).Methods("POST")
```

**Comment by rleungx** [comment]
WDYT @disksing @nolouch

**Comment by disksing** [comment]
where should we store the history?

**Comment by rleungx** [comment]
> where should we store the history?

Can we store it in etcd?

**Comment by disksing** [comment]
I think we can. But we should be careful not to store too much data.

**Comment by rleungx** [comment]
Now, we have the audit log for HTTP API, close it.
