### ISSUE TITLE
pdctl store command supports to filter the tombstone stores

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#3005]
## Development Task
In some situations, we want to know the tombstone stores, but the stores are not displayed in the store command by default. extend the stores command such as:
```
store --state=Up
store --state=Offline
store --state=Down
store --state=Tombstone
```

**Comment by disksing** [comment]
Notes for contributor:
- PD server API [supports filter by state]( https://github.com/tikv/pd/blob/a56a9d2d7ae31db4e51193ccbeb4881d8087e446/server/api/store.go#L581)
- you will need to update the [store command of pd-ctl](https://github.com/tikv/pd/blob/master/tools/pd-ctl/pdctl/command/store_command.go)
- new unit tests can be added [here](https://github.com/tikv/pd/blob/master/tests/pdctl/store/store_test.go)

**Comment by duduainankai** [comment]
I walk through the code, it seems that pd server already supports filter by state ?

So what I need to do is adding the `state` flag in pd-ctl ?

**Comment by duduainankai** [comment]
And I didn't find `down` state in https://github.com/pingcap/kvproto/blob/master/pkg/metapb/metapb.pb.go .

Should we bump the version or do other things to meet it ?

**Comment by disksing** [comment]
> I walk through the code, it seems that pd server already supports filter by state ?
> 
> So what I need to do is adding the `state` flag in pd-ctl ?

Yes.

> And I didn't find `down` state in https://github.com/pingcap/kvproto/blob/master/pkg/metapb/metapb.pb.go .
> 
> Should we bump the version or do other things to meet it ?

`Down` is a slightly different state. A down store is persisted as `Up` and speculated as `Down` by store heartbeat time dynamically. Maybe 3 states (Up/Offline/Tombstone) is enough. /cc @nolouch Any suggestion?
