### ISSUE TITLE
Support multi-client TSO benchmark

### ISSUE THREAD

**Issue by JmPotato** [tikv/pd#3024]
### Describe your feature request related problem

The `pd-tso-bench` now only run the benchmark with one single PD client. In order to get more useful performance data, I suggest adding a multi-client TSO benchmark into the `pd-tso-bench`.

### Describe the feature you'd like

Support multi-client TSO benchmark in `pd-tso-bench`.

**Comment by JmPotato** [comment]
@nolouch WDYT?

**Comment by nolouch** [comment]
looks good to me!
