### ISSUE TITLE
Add panel about distribution of region keys and bytes

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#3026]
I am not sure whether its format is suitable, I think we can adjust the hot peer threshold by used it

**Comment by lhy1024** [comment]
![image](https://user-images.githubusercontent.com/19542290/94145612-640f3a80-fea5-11ea-929f-e4c03f557f08.png)

**Comment by lhy1024** [comment]
heatmap
![image](https://user-images.githubusercontent.com/19542290/94224743-c90a7500-ff25-11ea-8cd2-de6799cf74ec.png)

**Comment by nolouch** [comment]
Are there only hot spots or all?

**Comment by nolouch** [comment]
Are there only hot spots or all?

**Comment by lhy1024** [comment]
> Are there only hot spots or all?

There is all region.

And I prepare to add an interval statistic with the same method

**Comment by lhy1024** [comment]
![image](https://user-images.githubusercontent.com/19542290/94233632-c7977780-ff3a-11ea-9197-7a30d4c3163e.png)

**Comment by disksing** [comment]
looks great!
