### ISSUE TITLE
Add an interface to check the status of paused scheduler.

### ISSUE THREAD

**Issue by 3pointer** [tikv/pd#3052]
### Describe your feature request related problem
To solve https://github.com/pingcap/br/issues/549, when br pause the scheduler with a specified delay. we only know the request is succeed or not. then it's not easy for br to add integration test to test the status of scheduler.

### Describe the feature you'd like
It's better to have an interface to know whether the scheduler paused succeed or not.

**Comment by rleungx** [comment]
Does that mean we should provide an API such as `curl GET http://127.0.0.1:2379/pd/api/v1/schedulers/balance-hot-region-scheduler/status` to show the status of this scheduler?

**Comment by 3pointer** [comment]
yes, it seems work for this issue. or maybe provide other API (http://127.0.0.1:2379/pd/api/v1/paused-schedulers/) to let the user know the paused schedulers' status
