### ISSUE TITLE
placement rules: imporve bundle API

### ISSUE THREAD

**Issue by disksing** [tikv/pd#3054]
## Development Task

We have introduced the bundle API to update placement rules. There is an issue that the `Group` field of received `Rule` may not match the id of the group. I have sent a PR to fix it previously (https://github.com/tikv/pd/pull/2957) but it seems to be not good enough (see https://github.com/tikv/pd/issues/2680#issuecomment-700400319).

To make greater, we can support setting `Group` field automatically when it is unset. Note that when `Group` is set but different from expected group id, we should still report an error.

**Comment by nolouch** [comment]
Can we close this issue?
