### ISSUE TITLE
The define of unhealthy is different in `core` and `schedule`

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#3063]
## Question Report

The define of unhealthy is different in `core` and `schedule`.

In `core/store.go`:
```
// IsUnhealth checks if a store is unhealth.
func (s *StoreInfo) IsUnhealth() bool {
	return s.DownTime() > storeUnhealthDuration
}
```
`storeUnhealthDuration` is **10min**

In `schedule/filters.go` ,
```
func (f *healthFilter) filter(opt opt.Options, store *core.StoreInfo) bool {
	if store.IsBusy() {
		return false
	}
	return store.DownTime() <= opt.GetMaxStoreDownTime()
}
```
`GetMaxStoreDownTime` is usually **30min**

### What version of PD are you using (`pd-server -V`)?
master, v4.0.x

**Comment by rleungx** [comment]
Hmmm, why this issue is defined as a bug?

**Comment by lhy1024** [comment]
> Hmmm, why this issue is defined as a bug?

emmm, What label do you think is reasonable？

**Comment by disksing** [comment]
It's probably just the naming that's confusing here.

`store.IsUnHealthy` is only put in the API/metrics output for the user to see, to alert the user that the node may be abnormal; `healthFilter` is to determine if the node should be replicated after it is unavailable.

**Comment by rleungx** [comment]
This issue has been stale and `healthFilter` is replaced by `StoreStateFilter`. Close it.
