### ISSUE TITLE
Region store command is not consistent with store command

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#3065]
### What did you do?

Use pd-ctl region store command to show the regions of a store.

### What did you expect to see?

From store command, it shows there are two regions in this store.
<img width="1134" alt="a5de0267-12a3-41c3-8958-6edf6dcdfd01" src="https://user-images.githubusercontent.com/35896542/95809691-fd619c00-0d41-11eb-9ce8-6dd83ee9eb71.png">

The region store command should list these two regions.

### What did you see instead?

But actually, it shows nothing:
<img width="730" alt="4d1a6a08-af55-40b0-abee-ee07659d20fc" src="https://user-images.githubusercontent.com/35896542/95809827-4285ce00-0d42-11eb-9bb7-80223427f1cc.png">

The reason why it shows nothing is that we only get the leaders and followers. And we should get learners also. See https://github.com/tikv/pd/blob/6a418cee3dc8358e10872ee19fc5470d522d102f/server/core/region.go#L784

### What version of PD are you using (`pd-server -V`)?
v3.0.5

**Comment by johanavril** [comment]
hi @rleungx , I want to work on this, thank you
