### ISSUE TITLE
Enhance the API to get disabled scheduler easily

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#3067]
### Describe your feature request related problem

For now, we can get the running or paused schedulers according to API. But we cannot directly get the disabled schedulers. The only way to get these disabled schedulers is by using config show command.

### Describe the feature you'd like

It's better to enhance our existed API to support getting the disabled scheduler directly.

**Comment by duduainankai** [comment]
May I ask the definition of `disabled schedulers` ? 

Does it mean the schedulers that are not allowed to schedule ?

**Comment by rleungx** [comment]
We have a config for each scheduler, you can find it by running `config show all` in pd-ctl.  There is a field named disable in each scheduler. e.g.
```
    "schedulers-v2": [
      {
        "type": "balance-region",
        "args": null,
        "disable": false,
        "args-payload": ""
      },
      {
        "type": "balance-leader",
        "args": null,
        "disable": false,
        "args-payload": ""
      },
      {
        "type": "hot-region",
        "args": null,
        "disable": false,
        "args-payload": ""
      },
      {
        "type": "label",
        "args": null,
        "disable": false,
        "args-payload": ""
      }
    ],
```


When its value is true, it won't be created in the PD start process.

**Comment by duduainankai** [comment]
Got

**Comment by duduainankai** [comment]
I will have a try.
