### ISSUE TITLE
read bytes on hot leader is inconsistent with hot region's leader distribution

### ISSUE THREAD

**Issue by CheneyDing** [tikv/pd#3097]
## Bug Report
![image](https://user-images.githubusercontent.com/24471884/96875942-6667b300-14aa-11eb-87b4-507a0cc33659.png)

### What did you do?

test hot region

### What did you expect to see?
read bytes on hot leader regions should match with leader distribution

### What did you see instead?
not match

### What version of PD are you using (`pd-server -V`)?
ai-sche-4ea1991
todo: test on master

**Comment by lhy1024** [comment]
I think we can add more detail

**Comment by CheneyDing** [comment]
same k8s cluster topology and go-ycsb config with [issue 3098](https://github.com/tikv/pd/issues/3098)

**Comment by nolouch** [comment]
It's according to flows on the region, not the region numbers.
