### ISSUE TITLE
Support a signature when modifying the configuration

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#3111]
### Describe your feature request related problem

We often encounter a problem, it is impossible to know who a configuration change comes from, especially when this configuration causes problems.

### Describe the feature you'd like

we should support a feature that signature when modifying the configuration. If modifying from `pd-ctl`, it means from admin.
If modifying by api, we need the user to provide a signature so that we can add it to the log

**Comment by lhy1024** [comment]
Furthermore, for those who call HTTP API and write ETCD, we can consider asking users to provide a signature, which will also facilitate us to add audit

**Comment by rleungx** [comment]
We can enable audit log now, close it.
