### ISSUE TITLE
Do not remove the down peer until the normal peers are enough

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#3117]
### Describe your feature request related problem

Currently, when a region has down peer (the region's leader does not receive the heartbeat), we will handle it if the duration is beyond the `max-store-down-time`. See https://github.com/tikv/pd/blob/6dc21259f151f1447bdddff5d9951e8f9a2d551d/server/schedule/checker/replica_checker.go#L85

We will try to replace this peer with a new peer. 
https://github.com/tikv/pd/blob/6dc21259f151f1447bdddff5d9951e8f9a2d551d/server/schedule/checker/replica_checker.go#L229-L239

But if there is something wrong after the learner is added, there will have 4 peers (include 1 learner). Once it enters the checker again, the PD will remove the down peer instead due to the number of peers is beyond the max replicas.
https://github.com/tikv/pd/blob/6dc21259f151f1447bdddff5d9951e8f9a2d551d/server/schedule/checker/replica_checker.go#L218

In this case, the region will have three peers and two normal peers, and one learner. 

### Describe the feature you'd like

I think a better way is to make sure there are enough normal peers then remove the down peer.

**Comment by rleungx** [comment]
PTAL @disksing @HunDunDM @nolouch

**Comment by disksing** [comment]
Good idea.
