### ISSUE TITLE
Compatible with replication setting  after placement rule is enabled

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#3140]
## Feature request
We can set the replication config with `pdctl` if the placement rules is disabled, like:
```
>> pd-ctl config set max-replicas 1
successful!
```
But if we enable the placement rules, the replication of the other config will become invalid:
```
>> pd-ctl config set enable-placement-rules true
>> pd-ctl config set max-replicas 1
Failed to set config: [400] "cannot update MaxReplicas when placement rules feature is enabled, please update rule instead"
```
This issue is want to let `config set` also work if the placement rules only have one default rule.

**Comment by duduainankai** [comment]
Sorry for the slow response.

Does  `placement rules only have one default rule`  means we have one placement rule and the `StarKey` and `EndKey` are both nil ?

And I am supposed to update the `count` of rule when update `max-replicas` which is missing from current mr.

**Comment by nolouch** [comment]
already finished.
