### ISSUE TITLE
The statistics of read keys does not match the RocksDB keys flows

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#3158]
### What did you do?

Use sysbench oltp_read_write to test.

### What did you expect to see?

The key flows are balanced in both PD and TiKV view.

### What did you see instead?

<img width="1894" alt="Screen Shot 2020-11-05 at 2 37 54 PM" src="https://user-images.githubusercontent.com/35896542/98206876-af713a00-1f75-11eb-89e1-50ed408c093c.png">
<img width="1895" alt="Screen Shot 2020-11-05 at 2 38 16 PM" src="https://user-images.githubusercontent.com/35896542/98206884-b435ee00-1f75-11eb-8c7f-8e8bf649ac5b.png">

### What version of PD are you using (`pd-server -V`)?

**Comment by lhy1024** [comment]
BTW, the first image is instant speed without solved

**Comment by rleungx** [comment]
Close it since it's stale.
