### ISSUE TITLE
Executing "make retool-setup" on release-3.1 failed

### ISSUE THREAD

**Issue by lilinghai** [tikv/pd#3171]
### What did you do?
execute the command on the branch of release-3.1
`make retool-setup`

### What did you expect to see?
successfully
### What did you see instead?
```
retool: fatal err: execution error on "go get -d github.com/golangci/golangci-lint/cmd/golangci-lint": package 4d63.com/gochecknoglobals/checknoglobals: unrecognized import path "4d63.com/gochecknoglobals/checknoglobals": reading https://4d63.com/gochecknoglobals/checknoglobals?go-get=1: 404 Not Found
: failed to 'go get' tool: exit status 1
make: *** [retool-setup] Error 1
```
### What version of PD are you using (`pd-server -V`)?
release-3.1

**Comment by rleungx** [comment]
Since our release-3.1 branch is not going to maintain, close it for now.
