### ISSUE TITLE
Balance region improvement 

### ISSUE THREAD

**Issue by disksing** [tikv/pd#3204]
## Development Task
- [x] Add WMA/HMA filters #3183 
- [x] Add MaxFilter: https://github.com/tikv/pd/pull/3193
- [ ] Use average available for score calculating https://github.com/tikv/pd/pull/3227
- [ ] Consider store available deviation when balance
- [ ] Use new region score formula

**Comment by lhy1024** [comment]
It will solve https://github.com/tikv/pd/issues/2002

**Comment by nolouch** [comment]
also relative https://github.com/tikv/pd/issues/2071

**Comment by rleungx** [comment]
We have already used the v2 score formula in the release v5.0.0.
