### ISSUE TITLE
PD should limit the size of target-region of merge operation

### ISSUE THREAD

**Issue by Little-Wallace** [tikv/pd#3229]
### What did you do?

PD merged multiple regions to a large region because it did not limit the max size of target-region.  The configueration `max-merge-region-size` only limited source region. 
![image](https://user-images.githubusercontent.com/16376959/100573416-b55b0080-3312-11eb-99ed-032988ee8dae.png)
![image](https://user-images.githubusercontent.com/16376959/100573459-ce63b180-3312-11eb-8e10-0b182488c146.png)

### What version of PD are you using (`pd-server -V`)?
4.0.9

**Comment by nolouch** [comment]
cc @rleungx

**Comment by rleungx** [comment]
I think we have a config named `enable-one-way-merge` to pick up a smaller region as the target.

**Comment by Little-Wallace** [comment]
Yes... But I think we still need to limit the size of target-region....
