### ISSUE TITLE
Bug: PD follower got error "Got too many pings from the client"

### ISSUE THREAD

**Issue by hunterlxt** [tikv/pd#3230]
## Bug Report

PD follower log got errors "Got too many pings from the client". Unlike tikv and tidb, they are responsible for establishing grpc server by itself, PD uses the grpc server provided by etcd, so the parameters cannot be set.  This error may occur when the client and server parameters `PermitWithoutStream` are not uniform.

**Comment by HunDunDM** [comment]
A similar issue [tidb#17870](https://github.com/pingcap/tidb/issues/17870)

**Comment by hunterlxt** [comment]
> A similar issue [tidb#17870](https://github.com/pingcap/tidb/issues/17870)

similar but not same, this is an issue between pds.
