### ISSUE TITLE
scheduler config should return scheduler not found when the scheduler is not existed

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#3241]
### What did you do?

Use `scheduler config evict-leader-scheduler` in pd-ctl when there is no evict-leader-scheduler

### What did you expect to see?

404 scheduler not found

### What did you see instead?

[404] 404 page not found

### What version of PD are you using (`pd-server -V`)?
v4.0.8

**Comment by zz-jason** [comment]
404 is an HTTP error code, better not to mix it with scheduler error in PD 😂

**Comment by rleungx** [comment]
Hmmm... the original 404 error is not very clear, so in PD we usually use our custom error message.

**Comment by glkappe** [comment]
@rleungx https://github.com/pingcap/docs-cn/pull/4992
