### ISSUE TITLE
Question: How to remove a Region?

### ISSUE THREAD

**Issue by Ryan-Git** [tikv/pd#3246]
code base 3.0.5

Due to some reason, I want to remove a region from PD. Read through `clusterInfo.handleRegionHeartbeat`, region info saves into `c.core.Regions`(which is a in-memory map) and `c.kv`(which persists to etcd and leveldb). I just removed the region from these two places.

Everything seems fine until reboot/leader change(still not sure which). The deleted region comes up again. What do I miss?

One thing I noticed is the region syncer. Maybe the original follower doesn't reload region from etcd so it's not aware of the deletion?

**Comment by Ryan-Git** [comment]
defaults to save to leveldb and sync from leader, so as I guessed follower don't know the deletion... close this.

**Comment by rleungx** [comment]
The region is reported by TiKV through heartbeat, it cannot be deleted from PD directly.
