### ISSUE TITLE
(CRT-D0017) Incomplete condition detected

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#3272]
## Description
Some conditions become unsafe when not exhaustive. For example, in the following example, the array `xs` may be of zero length, but not necessarily `nil` (say, when `xs := make([]someType, 0)`). Hence, the second part of the condition will panic if there are no elements yet. ```go xs != nil …

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/tikv/pd/issue/CRT-D0017/occurrences/](https://deepsource.io/gh/tikv/pd/issue/CRT-D0017/occurrences/)

**Comment by lhy1024** [comment]
can we close it?
