### ISSUE TITLE
Reduce hot read region scheduling during rolling upgrade TiKV

### ISSUE THREAD

**Issue by HunDunDM** [tikv/pd#3298]
### Describe your feature request related problem

In the [test of issue #3050](https://github.com/tikv/pd/issues/3050#issuecomment-749996426), it can be observed that the `hot-write-move-peer` basically disappeared after the PR #3200 was merged when rolling restart TiKV. But there are still many `hot-read-move-peer`. The latency during rolling restart may still can be improved.

![image](https://user-images.githubusercontent.com/19789302/102972824-a3960300-4536-11eb-8e32-5b4667efc323.png)

QPS
  * ![image](https://user-images.githubusercontent.com/19789302/102971945-42b9fb00-4535-11eb-972b-4c3dad559c44.png)
  * Base (The data source is 600 sysbench logs within 10 minutes of the corresponding time)
    | | |
    | :-- | -- |
    | tps | 17455.70 |
    | tps-jitter-sd | 7.66% |
    | tps-jitter-kmean(k=2) | 27.88% |
    | tps-jitter-rand-percent(p=10.00%) | 4.81% |
    | p99-lat | 100.69ms |
    | p99-lat-jitter-sd | 44.28% |
    | p99-lat-jitter-kmean(k=2) | 146.49% |
    | p99-lat-jitter-rand-percent(p=10.00%) | 29.66% |
  * Rolling restart after merging #3200
    | | |
    | :-- | -- |
    | tps | 16864.37 |
    | tps-jitter-sd | 14.96% |
    | tps-jitter-kmean(k=2) | 59.01% |
    | tps-jitter-rand-percent(p=10.00%) | 8.36% |
    | p99-lat | 103.37ms |
    | p99-lat-jitter-sd | 352.09% |
    | p99-lat-jitter-kmean(k=2)|2240.71% |
    | p99-lat-jitter-rand-percent(p=10.00%)|27.73% |

### Describe the feature you'd like

Reduce the unnecessary scheduling.

### Describe alternatives you've considered

Disable move-peer hotspot scheduling during rolling restart

### Teachability, Documentation, Adoption, Migration Strategy

- Go

**Comment by MimeLyc** [comment]
refresh
