### ISSUE TITLE
Make ID allocator monotonic

### ISSUE THREAD

**Issue by disksing** [tikv/pd#3303]
### Describe your feature request related problem
Currently, the ID allocator is guaranteed not to allocate duplicated IDs, but when PD leader changes multiple times, the IDs may not be monotonic.

### Describe the feature you'd like

We can sync allocator once PD becomes leader.

### Describe alternatives you've considered

none.

### Teachability, Documentation, Adoption, Migration Strategy

none.

**Comment by BusyJay** [comment]
When is the bug introduced? Or what versions are affected?

**Comment by BusyJay** [comment]
It should probably be marked as bug instead. `state_id` in replication mode also uses the same id allocator, which breaks the assumption that it increases at every step.
