### ISSUE TITLE
unknown shorthand flag: 'd' in -d for pd-ctl

### ISSUE THREAD

**Issue by overvenus** [tikv/pd#3341]
## Bug Report

`-d` flag is missing, likely a compatibility bug.

### What did you do?

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/4483/pipeline/67#step-536-log-69

### What version of PD are you using (`pd-server -V`)?

master branch

**Comment by rleungx** [comment]
Since there is something wrong with this flag and it hasn't been used for a long time. We are going to remove this flag. See #3349

**Comment by rleungx** [comment]
Closed via #3349
