### ISSUE TITLE
Peer role should be string instead of number

### ISSUE THREAD

**Issue by BusyJay** [tikv/pd#3372]
### What did you do?

Enable joint consensus and check some region in joint state

### What did you expect to see?

Peers show with exact role name.

### What did you see instead?

Peers with role set to number:
```
{
  "id": 5995753,
  "store_id": 8,
  "role": 2
}
```

### What version of PD are you using (`pd-server -V`)?
Nightly

**Comment by HunDunDM** [comment]
Modification from `kvproto` has some impact and may introduce compatibility issues.

**Comment by HunDunDM** [comment]
Is it ok to only adjust the output of `pd-ctl`?

**Comment by BusyJay** [comment]
It may be another problem that output of pd-ctl is not consistent with curl.
