### ISSUE TITLE
More audit logs for PD API

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#3383]
### Describe your feature request related problem

We cannot know the source operator of the PD API. 

### Describe the feature you'd like

Add more detailed source information of the PD API.  such as `add scheduler` and `remove schedule`, it's may be caused by the user or the tools(like BR).

### Describe alternatives you've considered

add an audit middware.

### Teachability, Documentation, Adoption, Migration Strategy
- Go

**Comment by CabinfeverB** [comment]
Closed since #5592 has been finished.
