### ISSUE TITLE
Can we expose the getBasicCommand

### ISSUE THREAD

**Issue by xhebox** [tikv/pd#3419]
## Feature Request

https://github.com/tikv/pd/blob/master/tools/pd-ctl/pdctl/ctl.go#L63-L100, the root command for pd-ctl. Exposing it is good for integration tests. I want to use it in another project, and I do not want to use `os.Exec` or init all these commands by myself.

PD internally will init a new command for tests: https://github.com/tikv/pd/blob/master/tests/pdctl/helper.go#L40-L67. Instead of making a helper in tests packages, why not just expose the root command.

**Comment by disksing** [comment]
+ my vote
