### ISSUE TITLE
Regions get merged into huge regions after restoring cluster using BR

### ISSUE THREAD

**Issue by tennix** [tikv/pd#3443]
### What did you do?

I've restored a cluster using BR from backup, after the restoration, we've found some huge regions as large as 6GB. These regions were not split afterwards. I've also enabled hibernate regions for TiKV after the restoration success.

### What did you expect to see?

The region size is normal. And at least the huge region got split.

### What did you see instead?

There are huge regions as large as 6GB
<img width="691" alt="image" src="https://user-images.githubusercontent.com/7932127/109128258-46af0700-778a-11eb-9bf5-a90127eaebe1.png">

### What version of PD are you using (`pd-server -V`)?

PD and TiKV version is v4.0.9
BR is using this commit hash: https://github.com/pingcap/br/commit/804aa908719748888010edaa944757b82f99f4df

<img width="1561" alt="image" src="https://user-images.githubusercontent.com/7932127/109127525-80cbd900-7789-11eb-9365-ec78aadb767c.png">
<img width="1547" alt="image" src="https://user-images.githubusercontent.com/7932127/109129027-1caa1480-778b-11eb-93b6-963cd359e9e2.png">

The restoration succeeded at 01:09:41, and hibernate region was enabled at 01:25:39

**Comment by overvenus** [comment]
There is a bug in old BR, it does not update region size after ingest SST. And the hash given above shows the bug affects the restore. It is fix in https://github.com/pingcap/br/pull/702.

**Comment by Yisaer** [comment]
I think this could be closed now?
