### ISSUE TITLE
The distribution provided by region scatter is not balanced.

### ISSUE THREAD

**Issue by Yisaer** [tikv/pd#3450]
### What did you do?
1. tiup playground --pd 1 --pd.binpath /xx/pd-server --kv 6 --db 1 --tiflash 0
2. run the statement following:
```sh
mysql> create table t(id int);
Query OK, 0 rows affected (0.20 sec)

mysql> SPLIT TABLE t BETWEEN (0) AND (1000000000) REGIONS 200;
+--------------------+----------------------+
| TOTAL_SPLIT_REGION | SCATTER_FINISH_RATIO |
+--------------------+----------------------+
|                199 |                    1 |
+--------------------+----------------------+
1 row in set (9.08 sec)

mysql> select count(s.region_id) cnt, s.index_name, p.store_id from INFORMATION_SCHEMA.TIKV_REGION_STATUS s join INFORMATION_SCHEMA.tikv_region_peers p on s.region_id = p.region_id where s.table_name = 't' and p.is_leader = 0 group by index_name, p.store_id order by index_name,cnt desc;
+-----+------------+----------+
| cnt | index_name | store_id |
+-----+------------+----------+
| 100 | NULL       |       13 |
| 100 | NULL       |        1 |
|  94 | NULL       |        3 |
|  41 | NULL       |        8 |
|  38 | NULL       |       14 |
|  27 | NULL       |        2 |
+-----+------------+----------+
6 rows in set (0.03 sec)
```

### What did you expect to see?
The distribution should be balanced.

### What did you see instead?
imba

### What version of PD are you using (`pd-server -V`)?
master 1f200cbc

**Comment by Yisaer** [comment]
The imbalance of the distribution mainly caused by 3 reasons:

1. The filter was too strict:

https://github.com/tikv/pd/blob/0e15869c568d0a6db7d2d674cebe7dd9d316985f/server/schedule/region_scatterer.go#L402-L405

The `StoreState` Filter will filter the store which exceed some limitations like `max-snapshot` or `max-pending-peer` if the `MoveRegion` was enabled. This was too strict for the region scatter case.

2. The wrong usage for `reset`

https://github.com/tikv/pd/blob/0e15869c568d0a6db7d2d674cebe7dd9d316985f/server/schedule/region_scatterer.go#L310-L314

When the candidates stores was empty, the `context` would be reset so as the count for each store. This logic is unnecessary and cause the final distribution wrong either.

3. The wrong usage of `put`

https://github.com/tikv/pd/blob/0e15869c568d0a6db7d2d674cebe7dd9d316985f/server/schedule/region_scatterer.go#L327-L328

https://github.com/tikv/pd/blob/0e15869c568d0a6db7d2d674cebe7dd9d316985f/server/schedule/region_scatterer.go#L347-L351

The count would be plus one when the candidate stores was picked. However, if the operator was failed to be created, the deviation between the recorded count and the reality distribution would be larger.

**Comment by nolouch** [comment]
Need to closed?
