### ISSUE TITLE
Unify the KV interface call

### ISSUE THREAD

**Issue by JmPotato** [tikv/pd#3453]
### Describe your feature request related problem

We have a KV interface definition and some KV storage wraps in [server/kv](https://github.com/tikv/pd/tree/master/server/kv). However, some of the PD codes are using etcd client directly rather than using the KV interface.

### Describe the feature you'd like

We should unify the KV interface call in PD. And furthermore, base on the unified KV storage, we could richer KV storage options for different cases. For example, for the test purpose, we can simply provide a KV storage based on a map struct to speed up the tests and reduce resource consumption.

**Comment by JmPotato** [comment]
After diving into the codes, I think this is a change that we should discuss first. The amount of work is not small.

**Comment by rleungx** [comment]
Perhaps we can expose some APIs for external use so that the other component can use it instead of directly using etcd client.
