### ISSUE TITLE
The version tag of release-5.0 and master should be updated

### ISSUE THREAD

**Issue by JmPotato** [tikv/pd#3479]
## Bug Report

The version info current `pd-server` on `release-5.0` and `master` holds may affect the functionality.

### What did you do?

- `make build` on `release-5.0` or `master`.
- `./bin/pd-server -V`

### What did you expect to see?

`Release Version` should equal to or bigger than 5.0.

### What did you see instead?

<img width="491" alt="图片" src="https://user-images.githubusercontent.com/1446531/111177391-21712400-85e5-11eb-90e0-d242cb2175ad.png">

**Comment by rleungx** [comment]
Now, we have the right tag.
