### ISSUE TITLE
pd-ctl hangs when using ssh to execute

### ISSUE THREAD

**Issue by mahjonp** [tikv/pd#3492]
### What did you do?

![image](https://user-images.githubusercontent.com/3251373/111747215-0430a400-88ca-11eb-8448-3ad69589b103.png)

### What did you expect to see?

Return the result as keying this command on the remote host

### What did you see instead?

Command hangs

### What version of PD are you using (`pd-server -V`)?

```
Release Version: v4.0.11
Edition: Community
Git Commit Hash: 96efd6f402361f2f84e39ea5b3a7a6f6b10acfb1
Git Branch: heads/refs/tags/v4.0.11
UTC Build Time:  2021-02-25 04:39:55
```

**Comment by rleungx** [comment]
Is it duplicated with https://github.com/tikv/pd/issues/3318?

**Comment by mahjonp** [comment]
> Is it duplicated with #3318?

OMG, it's the same issue, and the workaround is ok for me.
