### ISSUE TITLE
metrics: the statistic of pending operator is negative

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#3519]
### What did you do?

Test hot region scheduler

### What did you expect to see?

the num of pending operator is not negative

### What did you see instead?
![image](https://user-images.githubusercontent.com/19542290/112278210-8f8ca980-8cbd-11eb-98ae-0c28e9ea66fd.png)

### What version of PD are you using (`pd-server -V`)?
master

**Comment by rleungx** [comment]
Does this problem still exist?

**Comment by lhy1024** [comment]
It's caused by `delta`, we should use `rate`.
