### ISSUE TITLE
Unstable hot region scheduler after load base split

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#3527]
### What did you do?

```
[root@tidb-bench-0 case2]# cat test.sh 
for i in {1..3}
do
echo $i
mysql -h10.68.208.230 -P4000 -u root < reset.sql
sysbench --rand-type=uniform --table_size=10000 --range_size=100 --point_selects=0 --sum_ranges=0 --order_ranges=0 --distinct_ranges=0 --config-file=config oltp_read_only prepare
sysbench --rand-type=uniform --table_size=10000 --range_size=100 --point_selects=0 --sum_ranges=0 --order_ranges=0 --distinct_ranges=0 --config-file=config oltp_read_only run
sleep 600
done

```

### What did you expect to see?

stable hot region schedule

### What did you see instead?

![image](https://user-images.githubusercontent.com/19542290/112443976-81f02600-8d88-11eb-8489-495f623e53e3.png)

left is 5.0 and right is 4.0 and I found byte is drop

![image](https://user-images.githubusercontent.com/19542290/112466070-6264f780-8da0-11eb-9161-9db4e5b2b360.png)

### What version of PD are you using (`pd-server -V`)?

tikv is 5.0 with 52f658a 
pd is 5.0 with 9a70cb5
pd is 4.0 with 5b5bc83

**Comment by nolouch** [comment]
It's may expect as the coprocess cache is enabled.

**Comment by lhy1024** [comment]
![image](https://user-images.githubusercontent.com/19542290/112464929-11a0cf00-8d9f-11eb-9d68-d67ec8d2fb59.png)

I run the same test with copr cache disable, there is no traffic drop and no scheduling jitter.

However, we should note that 5.0 has copr cache enabled by default.
