### ISSUE TITLE
metrics: the num of balance leader scheduler is negative

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#3561]
### What did you do?

Test go-ycsb in 5.0

### What did you see instead?

![image](https://user-images.githubusercontent.com/19542290/113390342-19c2c500-93c4-11eb-8c03-e7915dbf76b9.png)

### What version of PD are you using (`pd-server -V`)?

5.0-GA

**Comment by rleungx** [comment]
Fixed by https://github.com/tikv/pd/pull/4015.
