### ISSUE TITLE
metrics: the num of operator limit is always zero

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#3562]
### What did you do?

Test go-ycsb in 5.0 and there is a lot of balance leader operator and balance region operator

### What did you see instead?

![image](https://user-images.githubusercontent.com/19542290/113390568-9655a380-93c4-11eb-9335-1a0c86ee81fb.png)

### What version of PD are you using (`pd-server -V`)?

5.0-GA

**Comment by rleungx** [comment]
I think it's expected

**Comment by lhy1024** [comment]
Only when the operator exceeds the limit will this monitor be displayed
