### ISSUE TITLE
Consider evict leader after offline the store

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#3563]
### Describe your feature request related problem

TiKV snapshot has an IO limit of `100MB/s`. it's may become a bottleneck for sending snapshots. in the big cluster, we have encountered it about add learner too slow.

### Describe the feature you'd like

- Consider evicting leader after offline the store, then we can get snapshot from anthoer store.

### Teachability, Documentation, Adoption, Migration Strategy

- Go

**Comment by xuhui-lu** [comment]
Hey @nolouch, is this issue still open? If so, I can spend some time this week to help implement it.

**Comment by nolouch** [comment]
Thanks, @xuhui-lu, you can do it. and if you have any problem, you can ask about this issue.

**Comment by rleungx** [comment]
> Hey @nolouch, is this issue still open? If so, I can spend some time this week to help implement it.

There is a case that needs to pay attention to. If the number of offline stores is more than the rest, evict leaders may be not a good way.

**Comment by xuhui-lu** [comment]
> > Hey @nolouch, is this issue still open? If so, I can spend some time this week to help implement it.
> 
> There is a case that needs to pay attention to. If the number of offline stores is more than the rest, evict leaders may be not a good way.

oh, right. If the number of offline stores is more than the rest, evict leaders will lead to continuous election failures.

**Comment by nolouch** [comment]
maybe the better solution is the follower replica https://github.com/tikv/raft-rs/issues/136.
