### ISSUE TITLE
Consider allowing to set the replication config when there are many rules

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#3568]
### Describe your feature request related problem

Currently, we cannot set the replication configuration if there is exist a non-default rule. such as:
```
❯ tiup playground nightly --tiflash 1 --monitor
❯ mysql --host 127.0.0.1 --port 4000 -u root -p
--------------------------------------------------------
mysql> use test;
mysql> create table t(a int);
mysql> ALTER TABLE t SET TIFLASH REPLICA 1;
--------------------------------------------------------
❯ ./bin/pd-ctl config set max-replicas 2

Failed to set config: [400] "cannot update MaxReplicas or LocationLabels when placement rules feature is enabled and not only default rule exists, please update rule instead"
```
### Describe the feature you'd like
Do not report error, change the default rule.

### Describe alternatives you've considered
 
- Need to judge the negative impact

### Teachability, Documentation, Adoption, Migration Strategy

- Go

**Comment by bufferflies** [comment]
ok let me try

**Comment by bufferflies** [comment]
I do not know it is a bug if I modify default rule ,but replicate-rule is not update
