### ISSUE TITLE
strictly-match-label will be useless once we enable the placement rule

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#3578]
### What did you do?

Set the `strictly-match-label` to true. And then enable the placement rules. There is only a default rule in the cluster.

### What did you expect to see?

`strictly-match-label` can work well.

### What did you see instead?

`strictly-match-label` is useless. See https://github.com/tikv/pd/blob/3c81817831e9c7890ab8807c93491193498e48fc/server/cluster/cluster.go#L988-L991

### What version of PD are you using (`pd-server -V`)?
master

**Comment by bufferflies** [comment]
ok let me try it

**Comment by bufferflies** [comment]
I think it must check location label if strictly-match-label is enable, so it should remove placement rule condition.
