### ISSUE TITLE
[pd] cannot update member, while 1/3 pd down

### ISSUE THREAD

**Issue by Tammyxia** [tikv/pd#3579]
### What did you do?

1. Deploy tidb cluster, 3x pd, 3x tikv, 2x tidb, 3x cdc
2. When check cdc sync task, many warning about "[pd] cannot update member".
3.  Check tidb cluster status:
![image](https://user-images.githubusercontent.com/78345569/114161833-1054d200-995b-11eb-8512-a180c5d562a8.png)

### What did you expect to see?
Since there are 2 pd still are alive, pd should be available when cdc calls pd api.
### What did you see instead?
![image](https://user-images.githubusercontent.com/78345569/114162023-45f9bb00-995b-11eb-9cfd-15e8cfb03a4d.png)

### What version of PD are you using (`pd-server -V`)?
Release Version: v5.0.0
Edition: Community
Git Commit Hash: 687acfc8db8378e01e47ab21dd38473a3ff8d800
Git Branch: heads/refs/tags/v5.0.0
UTC Build Time:  2021-04-06 04:41:02

**Comment by HunDunDM** [comment]
Why is it critical?

**Comment by rleungx** [comment]
It is only a warning log which means we cannot update the member information through "this" PD. And we still can update the information through the others.

**Comment by jebter** [comment]
> Why is it critical? @jebter

I thought the service was affected, as if I made a mistake

**Comment by rleungx** [comment]
I don't think this issue is fixed.

**Comment by HunDunDM** [comment]
Sorry, I got the link wrong

**Comment by HunDunDM** [comment]
The component needs to use the repaired PD to complete the repair.
