### ISSUE TITLE
there is huge gap between low space kv and  high space kv where  there has few space.

### ISSUE THREAD

**Issue by bufferflies** [tikv/pd#3589]
## Bug Report

there is huge gap between diferent space. if the small store has no space, but it's score is lower than the high space store,so PD do not balance region from it to high space store, so it will offline because of no space left

![image](https://user-images.githubusercontent.com/23159587/114695315-0e6d8300-9d4e-11eb-8ebc-664375ada59b.png)
 

### What did you do?

 it will can move out some region  after it's score bigger than the bigger space store to avoid store offline 

### What did you expect to see?
I want the low space store's score will increse rapidly when it has few space,
### What did you see instead?
![image](https://user-images.githubusercontent.com/23159587/114695799-96538d00-9d4e-11eb-97f7-a98e13171c83.png)

### What version of PD are you using (`pd-server -V`)?
master

**Comment by nolouch** [comment]
fixed.
