### ISSUE TITLE
score version default is V

### ISSUE THREAD

**Issue by bufferflies** [tikv/pd#3608]
## Bug Report
I think score default version set V2 is better than V1 

### What did you do?
change default condition ,see: 
https://github.com/tikv/pd/blob/9d9c8eedca3a97ae5d2dd9e146f178ec041030d3/server/core/store.go#L248-L256

### What did you expect to see?
default to be set V2
### What version of PD are you using (`pd-server -V`)?
master

**Comment by nolouch** [comment]
Better to use `v1` to keep compatibility.
