### ISSUE TITLE
PD 'pd_config_status' mertics content repetition

### ISSUE THREAD

**Issue by buggithubs** [tikv/pd#3609]
### What did you see instead?

![image](https://user-images.githubusercontent.com/11624213/115180036-3f133b00-a107-11eb-92f4-ed9e86e56349.png)

### What version of PD are you using (`pd-server -V`)?

PD V5.0.0

**Comment by nolouch** [comment]
I think it's caused by leader changed or the remain metrics in Prometheus, it should be clean after for a while.
