### ISSUE TITLE
Upgrade Go version to 1.16

### ISSUE THREAD

**Issue by tisonkun** [tikv/pd#3672]
## Development Task

So far, PD development uses Go 1.13 which is end of life for a while. Also for supporting running on Apple M1 silicon, it is required to upgrade to 1.16.

@CadmusJiang and @zhouqiang-cl are in charge for upgrading Go version to 1.16 and most of validation works are done manually. Hopefully we get it done in this month.

This also supports TiDB stacks to upgrade Go version to 1.16 https://github.com/pingcap/tidb/issues/22198

**Comment by CadmusJiang** [comment]
Get go1.16 image:  `docker pull hub.pingcap.net/pingcap/centos7_golang-1.16:latest`

**Comment by purelind** [comment]
@tisonkun  pd jenkins ci already upgrade go version from 1.13 to 1.16.4 (only branch master)

**Comment by tisonkun** [comment]
@zhouqiang-cl  I think we should reopen this issue and create a pr target to it for upgrade `go.mod`.
