### ISSUE TITLE
Failed replicas are not added to new store

### ISSUE THREAD

**Issue by BusyJay** [tikv/pd#3684]
### What did you do?

A store was corrupted, so I stop the node, remove all data, and then using pd-ctl to run `store delete store_id`. And then redeploying a new TiKV instance on the same node with different port.

### What did you expect to see?

All pending/down replicas will be placed in the *new empty* node. Because those data will have to be placed back to the new node in the end to reach balance, it's a waste of resource to place them in other nodes.

### What did you see instead?

Replicas are paced on all nodes instead.

### What version of PD are you using (`pd-server -V`)?
v5.0.1

**Comment by cosven** [comment]
/severity moderate 

Feel free to change the severity ~

**Comment by nolouch** [comment]
It's by design. We priority to recover the region health.

**Comment by BusyJay** [comment]
What's the difference in time? In my test, if all new replicas are scheduled to TiKV, it takes 10 hours to recover 3TiB data. And with random scheduling recovery, it takes 17 hours to reach final balance and offline-peer-region-count never goes to zero till the end. My experiment result shows neither the design goal "recover the region health" is achieved nor random schedule can reduce vulnerable window.
