### ISSUE TITLE
Moving Peer does not consider the free space of the target store when merging Region

### ISSUE THREAD

**Issue by HunDunDM** [tikv/pd#3686]
### What did you do?

On a large cluster with less free space, delete a certain amount of data.

### What did you expect to see?

Region-Merge and Balance-Region work normally.

### What did you see instead?

![image](https://user-images.githubusercontent.com/19789302/118491843-faa0ac80-b751-11eb-88f7-85a297620112.png)
![image](https://user-images.githubusercontent.com/19789302/118492287-74d13100-b752-11eb-8598-1a8fc691f203.png)

### What version of PD are you using (`pd-server -V`)?

* v5.0.1

**Comment by nolouch** [comment]
ptal @CabinfeverB

**Comment by nolouch** [comment]
staled, reopen if needed.
