### ISSUE TITLE
evict leader not clear all leaders on target store

### ISSUE THREAD

**Issue by BusyJay** [tikv/pd#3690]
### What did you do?

Use tiup playground to deploy a cluster with 3 nodes. And then kill one node, apply evict leader scheduler on another.
```
% tiup playground v5.0.1 --tikv 3
# create a table and insert 60 rows.
% kill pid_of_tikv_3
% pd-ctl -i
> scheduler add evict-leader-scheduler 1
> store 1
```

### What did you expect to see?

The leader count of store 1 will go to 0 quickly.

### What did you see instead?

The leader count of store 1 is stuck at 4. I pick a region and find no scheduling log from either PD log or TiKV log. If I add the operator manually, the region can be evicted successfully.

### What version of PD are you using (`pd-server -V`)?
Release Version: v5.0.1
Edition: Community
Git Commit Hash: ea1449c7c693d94661b3c60d35b8679ebfb3da34
Git Branch: heads/refs/tags/v5.0.1
UTC Build Time:  2021-04-23 05:58:55

**Comment by rleungx** [comment]
Fixed by https://github.com/tikv/pd/pull/4096
