### ISSUE TITLE
configurations are not hidden

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#3738]
### What did you do?

config show

### What did you expect to see?

 some barely used configurations are hidden

### What did you see instead?

![image](https://user-images.githubusercontent.com/19542290/120649297-2be9de00-c4af-11eb-931e-fa07ed5771c6.png)

### What version of PD are you using (`pd-server -V`)?
```
/ # ./pd-server --version
Release Version: v5.1.0-alpha-9-g29cfdd98-dirty
Edition: Community
Git Commit Hash: 29cfdd985cae1511f25f944567d01fee939e85d2
Git Branch: master
UTC Build Time:  2021-06-03 08:51:09
```

**Comment by rleungx** [comment]
I think you are using pd-ctl with the old version.

**Comment by lhy1024** [comment]
> I think you are using pd-ctl with the old version.

right
