### ISSUE TITLE
Reduce the conflict when multiple scheduling is running

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#3778]
## Background

Scenario 1: Due to the drop table operation, a large number of merge operations are continuously occurring, and the balance-leader is restricted by the leader-schedule-limit, resulting in the conflict.

Scenario 2: store limit is shared by multiple schedulers. 

## details
| |  Store Limit - Add Peer| Store Limit -Remove Peer  | leader-schedule-limit |  hot-region-schedule-limit | merge-schedule-limit| region-schedule-limit | replica-schedule-limit |
|  ----  | ----  | --- | ----  | --- |  ----  | --- |  --- |
| BalanceLeader  | × | × |  √ | × | × | × | × |
| BalanceRegion  | √ | √ |  × | × | × | √ | × |
| EvictLeader | × | × |  √ | × | × | × | × |
| HotRegion | √ |  √ |  √ |  √ | × |  √ | × |
| Label | 
| ScatterRange | √ |  √ |  √ | × | × |  √ | × |
| learnerChecker| × | × |  × | × | × | × | × |
| replicaChecker | √ |  √ |  × | × | × |  √ | √ |
| ruleChecker | √ |  √ |  × | × | × |  √ | √ |
| mergeChecker | √ |  √ |  √ | × | √ |  √ | × |

- [ ] Consider do not influence with each other, such as `hot-region`.
- [ ] Improve the shared behavior for the `store limit`, such as allow preemption with priority.

**Comment by rleungx** [comment]
Also some existed problems can be found in https://github.com/tikv/pd/issues/3807

**Comment by bufferflies** [comment]
Also some existed problems can be found in #3749

**Comment by bufferflies** [comment]
there are two way to solved the problem that schedulers influenced each other:
one way: one operator enter to operator control should have one OpKind, the priority is blow:
         OpMerge>OpHotRegion>OpLeader>OpRegion
the other way: modify the scheduler/checker isAllowed condition, such as:
	balance region scheduler: count(OpRegion)-count(OpMerge)-count(OpHotRegion)<region scheduler limit

**Comment by bufferflies** [comment]
the relation between OpKind with scheduler(checker) is blow:
![image](https://user-images.githubusercontent.com/23159587/123762216-29837400-d8f5-11eb-8283-37ace1ad36fe.png)

**Comment by bufferflies** [comment]
Letremove-extras-peer not limit #3865

**Comment by lhy1024** [comment]
@bufferflies Can we close it?
