### ISSUE TITLE
After the expansion of the large cluster is completed, the leader is found to be unbalanced

### ISSUE THREAD

**Issue by Lily2025** [tikv/pd#3789]
### Minimal reproduce step (Required)?

1. deploy a v5.0.1 tidb cluster with 3pd 8db 29kv.
2. run workload and expand a TiKV
3. After a period of time, the number of leaders does not change，but not be balanced

### What did you expect to see?
After the expansion is completed，the leaders and regions are balanced between TiKVs

### What did you see instead?
After the expansion is completed，the number of leaders  were not balanced
The yellow line represents the expanded node
![Lark20210617-153452](https://user-images.githubusercontent.com/84712107/122352325-9d329200-cf81-11eb-88af-d918701e5560.png)

### What version of PD are you using (`pd-server -V`)?
[root@IDC-172-16-6-7 pd-2379]# bin/pd-server -V
Release Version: v5.1.0-alpha-28-gf6b61bad-dirty
Edition: Community
Git Commit Hash: f6b61bad356a053f6e934c93a62376c27f0858e8
Git Branch: release-5.1-hotfix
UTC Build Time:  2021-06-10 06:33:51

**Comment by rleungx** [comment]
Would you like to share more information like operators and scheduler panel?

**Comment by nolouch** [comment]
From @Lily2025  , This cluster has many empty regions. the reason is the `region count` not balance, it is in expect.
