### ISSUE TITLE
Microsecond cannot be printed

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#3799]
### What did you do?

Just start a cluster.

### What did you expect to see?

```
[2021/06/18 13:19:26.950 +08:00] [INFO] [cluster.go:297] ["load regions"] [count=1] [cost=100µs]
```
### What did you see instead?
```
[2021/06/18 13:19:26.950 +08:00] [INFO] [cluster.go:297] ["load regions"] [count=1] [cost=100<C2><B5>s]
```
### What version of PD are you using (`pd-server -V`)?
master

**Comment by xuhui-lu** [comment]
hey @rleungx May I pick this ticket up?

**Comment by rleungx** [comment]
> hey @rleungx May I pick this ticket up?

Sure!

**Comment by JmPotato** [comment]
@xuhui-lu Hello, any updates now?

**Comment by xuhui-lu** [comment]
sorry, i failed to replay it locally, and didn't fix it yet.

**Comment by nolouch** [comment]
@rleungx  cloud you replay it?

**Comment by JmPotato** [comment]
Resolved according to https://serverfault.com/questions/414760/how-to-make-the-less-command-handle-utf-8. It's about the charset setting of `less`, and PD has nothing to do with this bug.
