### ISSUE TITLE
One node is scaled down on a large cluster, and the offline is not completed after 20 hours

### ISSUE THREAD

**Issue by Lily2025** [tikv/pd#3800]
## Bug Report

1. deploy a v5.1.0 tidb cluster with 3pd 8db 30kv.
2. run workload and shrinking a TiKV
3. shrinking a TiKV at 6/17 17:49

### What did you expect to see?
Complete offline in a short time

### What did you see instead?
the offline is not completed after 20 hours
![111](https://user-images.githubusercontent.com/84712107/122517665-e4cd2280-d042-11eb-8788-6f8031e95a53.png)

### What version of PD are you using (`pd-server -V`)?
[root@IDC-172-16-6-7 pd-2379]# bin/pd-server -V
Release Version: v5.1.0-alpha-28-gf6b61bad-dirty
Edition: Community
Git Commit Hash: f6b61bad356a053f6e934c93a62376c27f0858e8
Git Branch: release-5.1-hotfix
UTC Build Time: 2021-06-10 06:33:51

**Comment by nolouch** [comment]
under investigation

**Comment by nolouch** [comment]
Cannot reproduce.

**Comment by rleungx** [comment]
I'm going to close this issue since it cannot reproduce.
