### ISSUE TITLE
The TSO tests is running too long

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#3838]
## Development Task
![image](https://user-images.githubusercontent.com/6428910/124548396-3b6a9700-de60-11eb-8b8e-4af204dc61ce.png)
It takes about 8 minutes. This took too long.

**Comment by nolouch** [comment]
cc @JmPotato

**Comment by JmPotato** [comment]
<img width="609" alt="图片" src="https://user-images.githubusercontent.com/1446531/124710371-42140f80-df2f-11eb-933e-36c5147fbd0b.png">

It seems that the `testAllocatorSuite` and `testLocalTSOSuite` comsume the most time.
