### ISSUE TITLE
PD can not be ready to serve after election a new leader

### ISSUE THREAD

**Issue by Little-Wallace** [tikv/pd#3847]
### Describe your feature request related problem
![image](https://user-images.githubusercontent.com/16376959/124894372-2af81f00-e00e-11eb-8982-c89c039c71a3.png)
![image](https://user-images.githubusercontent.com/16376959/124894413-33e8f080-e00e-11eb-892a-40612ba3d691.png)

As the pictures show:
PD became ready to serve requests at 11:01:19, but it had became leader at 11:01:11. It means that PD was not available during this 8 seconds.

### Describe the feature you'd like

I need PD to be  higher available. So the 8 second time during election and `ready to serve` should be shorter than now.

**Comment by nolouch** [comment]
It's caused by the read index is dropped, which causes the read request is blocked until timeout. the default timeout is 5s+2*election-imeout

**Comment by nolouch** [comment]
refer to https://github.com/etcd-io/etcd/issues/12680

**Comment by nolouch** [comment]
ref #3847
