### ISSUE TITLE
hot region should work if hot region schedule is disable

### ISSUE THREAD

**Issue by bufferflies** [tikv/pd#3879]
## Bug Report

I find hot region api will not work if hot region schedule is disable 
### What did you do?
schedule remove balance-hot-region-scheduler, See:
https://github.com/tikv/pd/blob/48963369ef04efaa9144eff27135c9ae14429a80/server/cluster/coordinator.go#L444-L456

### What did you expect to see?

hot region api should not be contorlled by  hot region schedule config

**Comment by bufferflies** [comment]
it should be noticed that hot region must run, the stLoadInfos will have some data, otherwise it will wrong . See:
https://github.com/tikv/pd/blob/48963369ef04efaa9144eff27135c9ae14429a80/server/schedulers/hot_region.go#L1044

**Comment by rleungx** [comment]
I have tried to fix it before but it needs some refactoring. The problem is that such store load information and these related functions should be put into the statistics module instead of the hot scheduler.

**Comment by bufferflies** [comment]
ref #4149
