### ISSUE TITLE
upgrade from v3.0.20 to v4.0.14, in overview page, pd tab, metrics are  displayed fail and report Only queries that return single series/table is supported

### ISSUE THREAD

**Issue by seiya-annie** [tikv/pd#3894]
### What did you do?

upgrade from v3.0.20 to v4.0.14,
check monitors in grafana

### What did you expect to see?
metrics are displayed well

### What did you see instead?
 report Only queries that return single series/table is supported error

### What version of PD are you using (`pd-server -V`)?
Release Version: v4.0.14
Edition: Community
Git Commit Hash: 0c1246dd219fd16b4b2ff5108941e5d3e958922d
Git Branch: heads/refs/tags/v4.0.14
UTC Build Time:  2021-07-17 05:37:22
[tidb@101 ~]$

**Comment by seiya-annie** [comment]
<img width="953" alt="截屏2021-07-21 下午5 57 29" src="https://user-images.githubusercontent.com/53471087/126485731-afc3b9d2-e26c-4110-a9dd-8cadea95b304.png">

**Comment by nolouch** [comment]
There may be a problem with the data or the grafana version during the time when the upgrade was launched, and see the environment has been automatically becoming normal:
![image](https://user-images.githubusercontent.com/6428910/126582093-6b3d4f04-f56a-45fd-b0ee-e0bbbc0552f7.png)

**Comment by nolouch** [comment]
@mayjiang0203 It works after the upgrade timepoint. there are two types of data during the upgrade. To display normally:
waiting for the old data to be GC, or the selected time period is only covers the new version. I don't think this issue needs to be processed because it will automatically become normal.

**Comment by seiya-annie** [comment]
still exist in 5.2.0
<img width="1267" alt="截屏2021-08-11 下午5 02 44" src="https://user-images.githubusercontent.com/53471087/129001404-bbc6bbae-f509-42ed-b4fe-515b2a371081.png">

**Comment by nolouch** [comment]
@mayjiang0203  you should waiting for the old data to be GC.
