### ISSUE TITLE
dr-auto-sync will be sync only one zone exsit

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#3924]
### What did you do?

![image](https://user-images.githubusercontent.com/6428910/127603239-7cde76c8-d1b2-4c73-8bab-3b58ea369d30.png)
start up one zone, and the another zone do not startup.
### What did you expect to see?
async model.
### What did you see instead?
```
➜  pd git:(master) curl http://127.0.0.1:30058/pd/api/v1/replication_mode/status
{
  "mode": "dr-auto-sync",
  "dr-auto-sync": {
    "label_key": "",
    "state": "sync",
    "state_id": 4
  }
}
```

### What version of PD are you using (`pd-server -V`)?
master

**Comment by mayjiang0203** [comment]
/ # ./pd-ctl --version
Release Version: v5.2.0-nightly
Edition: Community
Git Commit Hash: 9c0ea3279695bd714cfb0a933badff2cc1d4bb6e
Git Branch: heads/refs/tags/v5.2.0-nightly
UTC Build Time:  2021-08-16 10:40:56
