### ISSUE TITLE
merge region should work if all stores has low  disk space 

### ISSUE THREAD

**Issue by bufferflies** [tikv/pd#3938]
## Bug Report
I find merge checkout can not work if all store has no disk space. 

### What did you do?
1. write data into tidb
2. drop database 

the empty region can not merge after 2 days 

the region status:
![image](https://user-images.githubusercontent.com/23159587/127837198-be13fd89-219e-4cb2-ba0e-37ec8cfd1de1.png)

the target filter
![image](https://user-images.githubusercontent.com/23159587/127837257-dde7cdd8-be51-487d-b439-98adbcdb68f7.png)
the operator :
![image](https://user-images.githubusercontent.com/23159587/127837304-02139059-2d94-4b72-b64a-d02251968907.png)

3. one store add \

the region status:
![image](https://user-images.githubusercontent.com/23159587/127836918-886512a9-a963-4589-986c-4e76c846bc77.png)

the operator :
![image](https://user-images.githubusercontent.com/23159587/127836864-779e1f63-2e4f-467b-8685-46b9c9fc0eeb.png)

### What did you expect to see?
merge checker can work if all store has no space 

### What version of PD are you using (`pd-server -V`)?
version: master

**Comment by bufferflies** [comment]
I suspect merge can not work if the neighboring region locates in low space store because merge need region leader are in same store

**Comment by rleungx** [comment]
Can you upload the merge checker monitor?

**Comment by bufferflies** [comment]
![image](https://user-images.githubusercontent.com/23159587/127842966-61c5a134-b3e9-42ac-89cd-c2f0ca861691.png)

**Comment by rleungx** [comment]
Seems there are lots of abnormal replicas.

**Comment by bufferflies** [comment]
the cause is store label problem
