### ISSUE TITLE
pd-ctl: support `show` and `list` in `pd-ctl config` and `pd-ctl scheduler config`

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#3951]
### Describe your feature request related problem
![image](https://user-images.githubusercontent.com/19542290/128166168-ee7be5bb-65e7-4bd7-8e74-87b25d6aa5c7.png)
![image](https://user-images.githubusercontent.com/19542290/128166265-49deb21f-6b07-4f2e-a020-8710486b935d.png)

It bothers me.

### Describe the feature you'd like

Supported `show` and `list` at the same time.

### Teachability, Documentation, Adoption, Migration Strategy

Go

**Comment by rleungx** [comment]
Perhaps, we can unify them by using show or list.

**Comment by lhy1024** [comment]
> Perhaps, we can unify them by using show or list.

Maybe `show` is better?

**Comment by matchge-ca** [comment]
> I think for this change, we need to:
> 
> 1. The list still can use, and show warning "The command will be deprecated after version 5.4.0, please use config show"，and we can remove it in 5.4.0
> 2. Update the document.

Ok, to summarize:
- Add `show` sub command as part of `scheduler config balance-hot-region-scheduler`
- Add warning message `The list command will be deprecated after version 5.4.0, use show command instead.` when `list` is being used
- Create an issue ticket to disable `list` command targeting v5.4.0
- Update `pd-ctl` document (Require another issue ticket)
