### ISSUE TITLE
config: check whether is valid for config of hot scheduler in http

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#3952]
### Describe your feature request related problem

After #3920, we only check config for config of hot scheduler in pd-ctl, we also need check it in http

### Teachability, Documentation, Adoption, Migration Strategy

Go

**Comment by aidendou** [comment]
hi @lhy1024, I am onboarding to TiDB at work, trying to take some of the PD issues. For this particular one, are we just looking to be able to get the hot region scheduler config via restful api?

**Comment by lhy1024** [comment]
> hi @lhy1024, I am onboarding to TiDB at work, trying to take some of the PD issues. For this particular one, are we just looking to be able to get the hot region scheduler config via restful api?

Now we can configure the hot scheduler via http, but we don't check if the setting is valid

**Comment by njuwelkin** [comment]
Let me repeat the requirement, just to avoid mis-understandings.
On the client side(pd-ctl), we do http request validations like  below:
`
if priority != schedulers.BytePriority && priority != schedulers.KeyPriority && priority != schedulers.QueryPriority {
    ....
}
if priority == schedulers.QueryPriority && key == "write-peer-priorities" {
    ....
}
`
But actually we need do this on server side. For example, maybe can do it in handler AddScheduler().

Am I right? Or It's actually a more complex issue than what I though?

**Comment by lhy1024** [comment]
> 



> Let me repeat the requirement, just to avoid mis-understandings. On the client side(pd-ctl), we do http request validations like below: `if priority != schedulers.BytePriority && priority != schedulers.KeyPriority && priority != schedulers.QueryPriority { .... } if priority == schedulers.QueryPriority && key == "write-peer-priorities" { .... }` But actually we need do this on server side. For example, in handler AddScheduler().
> 
> Am I right? Or It's actually a more complex issue than what I though?

yes, we hope to check if the setting is valid when set config via http.

**Comment by njuwelkin** [comment]
i'd like to fix this, pls assign to me.

**Comment by njuwelkin** [comment]
i'd like to fix this, pls assign to me.
