### ISSUE TITLE
DR auto sync should not block write in async mode 

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/pd#3955]
### What did you do?
Interrupt network of dr cluster during run workload- sysbench.

### What did you expect to see?
Should unblock write after pd change mode to async.

### What did you see instead?
Still block write, and tps of sysbench stay in 0 until pd mode change to sync-recover due to network recover.

>>>here is log from test client.
[2021/08/05 10:09:22.094 +08:00] [INFO] [pdutil.go:406] ["pd mode change state from sync to async, current stateId:143835"]
[ 70s ] thds: 1 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 75s ] thds: 1 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 80s ] thds: 1 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 85s ] thds: 1 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 90s ] thds: 1 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 95s ] thds: 1 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 100s ] thds: 1 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00

### What version of PD are you using (`pd-server -V`)?
/ # /pd-server -version
Release Version: v5.2.0-alpha-61-g730853bd
Edition: Community
Git Commit Hash: 730853bd0dedc6e401a890cb8bfe839d4c88722f
Git Branch: master
UTC Build Time:  2021-08-04 09:18:56

**Comment by nolouch** [comment]
Confirm with @mayjiang0203 , 
It's caused by the error configuration.

**Comment by mayjiang0203** [comment]
It caused by config 2 replicas in dr cluster, while one replica in primary cluster.
