### ISSUE TITLE
DR-autosync:Should not block write in async mode after down one tikv network in primary cluster.

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/pd#3960]
### What did you do?
				//Test steps:
				//1.down br network
				//2.After replica mode change to async
				//3.down one tikv in primary cluster
				//4.Up br network
				//5.up the down tikv in step 3 in primary cluster

Primary cluster: 3 tikv，DR cluster: 2 tikv. 

### What did you expect to see?
Should not block write after step 3.

### What did you see instead?
![image](https://user-images.githubusercontent.com/9443637/128805422-4fd1e4ce-ac13-4d42-96f5-2b23d1ef87d7.png)

### What version of PD are you using (`pd-server -V`)?
/ # /pd-server -V
Release Version: v5.2.0-alpha-61-g730853bd
Edition: Community
Git Commit Hash: 730853bd0dedc6e401a890cb8bfe839d4c88722f
Git Branch: master
UTC Build Time:  2021-08-04 09:18:56

**Comment by nolouch** [comment]
The test case is not as expected. there is a region that has two replicas located in the down store, one is tc1, and another one is tc2.

**Comment by mayjiang0203** [comment]
Since the cluster work in Majority mode act same like this, so accept this result.
