### ISSUE TITLE
evict-leader-scheduler may cause that PD cannot offline Store

### ISSUE THREAD

**Issue by HunDunDM** [tikv/pd#3998]
### What did you do?

* Create a cluster
* Create `evict-leader-scheduler` for a lot of Stores.
* Offline a Store

### What did you expect to see?

* The Store state becomes Tombstone.

### What did you see instead?

* The Store status remains Offline.

### What version of PD are you using (`pd-server -V`)?

* v5.0.1

**Comment by lhy1024** [comment]
maybe we need to add `move leader` for `evict-leader-scheduler`

**Comment by HunDunDM** [comment]
It cannot completely solve this issue.

**Comment by nolouch** [comment]
@AndreMouche  Would you help to solve this issue?

**Comment by AndreMouche** [comment]
It seems we have already fixed this issue in master, here is my test steps:
1. evict leader on store 1
```
» scheduler add evict-leader-scheduler 1
Success!
» store 1
{
  "store": {
    "id": 1,
    "address": "127.0.0.1:20161",
    "version": "5.4.0-alpha",
    "status_address": "127.0.0.1:20181",
    "git_hash": "cb5cb230e77665e017853ce9292162c5fd250cbb",
    "start_timestamp": 1647934885,
    "deploy_path": "/Users/wuxuelian/workspace/tikv/target/release",
    "last_heartbeat": 1648018539943302000,
    "state_name": "Up"
  },
  "status": {
    "capacity": "460.4GiB",
    "available": "315.5GiB",
    "used_size": "6.407GiB",
    "leader_count": 38,
    "leader_weight": 1,
    "leader_score": 38,
    "leader_size": 2993,
    "region_count": 38,
    "region_weight": 1,
    "region_score": 5153.193036757978,
    "region_size": 2993,
    "slow_score": 1,
    "start_ts": "2022-03-22T15:41:25+08:00",
    "last_heartbeat_ts": "2022-03-23T14:55:39.943302+08:00",
    "uptime": "23h14m14.943302s"
  }
}

```

delete store 1
```
» store delete 1
Success!
» store 1
{
  "store": {
    "id": 1,
    "address": "127.0.0.1:20161",
    "version": "5.4.0-alpha",
    "status_address": "127.0.0.1:20181",
    "git_hash": "cb5cb230e77665e017853ce9292162c5fd250cbb",
    "start_timestamp": 1647934885,
    "deploy_path": "/Users/wuxuelian/workspace/tikv/target/release",
    "last_heartbeat": 1648018579949624000,
    "node_state": 2,
    "state_name": "Offline"
  },
  "status": {
    "capacity": "460.4GiB",
    "available": "315.5GiB",
    "used_size": "6.407GiB",
    "leader_count": 35,
    "leader_weight": 1,
    "leader_score": 35,
    "leader_size": 2831,
    "region_count": 35,
    "region_weight": 1,
    "region_score": 4874.26427509766,
    "region_size": 2831,
    "slow_score": 1,
    "start_ts": "2022-03-22T15:41:25+08:00",
    "last_heartbeat_ts": "2022-03-23T14:56:19.949624+08:00",
    "uptime": "23h14m54.949624s"
  }
}
```

get store 1 's status again and I find the status is `Tombstone` as we expected. 
```
» store 1
{
  "store": {
    "id": 1,
    "address": "127.0.0.1:20161",
    "version": "5.4.0-alpha",
    "status_address": "127.0.0.1:20181",
    "git_hash": "cb5cb230e77665e017853ce9292162c5fd250cbb",
    "start_timestamp": 1647934885,
    "deploy_path": "/Users/wuxuelian/workspace/tikv/target/release",
    "last_heartbeat": 1648018629962273000,
    "node_state": 3,
    "state_name": "Tombstone"
  },
  "status": {
    "capacity": "460.4GiB",
    "available": "315.4GiB",
    "used_size": "5.675GiB",
    "leader_count": 0,
    "leader_weight": 1,
    "leader_score": 0,
    "leader_size": 0,
    "region_count": 0,
    "region_weight": 1,
    "region_score": 0,
    "region_size": 0,
    "slow_score": 1,
    "sending_snap_count": 2,
    "start_ts": "2022-03-22T15:41:25+08:00",
    "last_heartbeat_ts": "2022-03-23T14:57:09.962273+08:00",
    "uptime": "23h15m44.962273s"
  }
}
```

**Comment by AndreMouche** [comment]
Oh， I'm failed to reproduce the issue on v5.0.1, any suggestions? @HunDunDM

**Comment by AndreMouche** [comment]
So， here is the failed case for 3-replication clusters:
1. we have 4 `tikv`: store1,store2,store3,store4
2. store1 evict leader
3. store2 evict leader
4. store3 evict leader
5. offline store4 success
It can't work...

Maybe we  can fix the issue by the following steps:
1. When `pd` receives a request `evict leader`, make sure there is enough healthy store to store the leader.
2. When `pd` receives a request `delete/offline store`, make sure there is enough healthy store,  here we should consider the `evict leader` stores, to make sure there is enough `tikv` to store the leaders(at least 1 store)
3. When we check the rule to find a new leader, if there is no healthy store, try to use `EnableForceTargetLeader` to move the leader to a healthy store that may be marked with `evict-leader`.(For example, we have 4 stores totally, now 3 stores are marked with `evict leader`, and the left 1 store is physically-broken)


cc @HunDunDM @nolouch

**Comment by nolouch** [comment]
fixed by https://github.com/tikv/pd/pull/4775
