### ISSUE TITLE
Add cache layer for placement.FitRegion

### ISSUE THREAD

**Issue by Yisaer** [tikv/pd#4025]
## Development Task

`placement.FitRegion` will consume lots of cpu resources, which would be the scheduling bottleneck in a large cluster with tiflash. This issue introducing cache layer for the `placement.FitRegion` If the calculating variables are not changed, and the region is already in a stable status, we could cache the result in cache layer after calculating by `FitRegion` and use the cache result in next time.

1. [x] introducing `version` in rule, version will be added each time rule updated.
2. [x] introducing `cache layer` for FitRegion
3. [x]  avoding re-calculating if we get cached result from FitRegion

**Comment by rleungx** [comment]
I think we have done this job? @Yisaer

**Comment by rleungx** [comment]
Close it since it has been finished.
