### ISSUE TITLE
Why not support setting store_state to Tombstone?

### ISSUE THREAD

**Issue by qiaohao9** [tikv/pd#4039]
### What did you do?

1. phsycally destroyed tikv data_dir
2. store state is set to `offline`
3. set store to `Tombstone` 

```shell
$ curl -X POST http://10.1.20.221:2379/pd/api/v1/store/5/state?state=Tombstone
```

### What did you expect to see?

the store is set to `Tombstone` successfully.

### What did you see instead?

```shell
[root@localhost ~]# curl -X POST http://10.1.20.221:2379/pd/api/v1/store/5/state?state=Tombstone
"invalid state Tombstone"
```

why only support `Up` and `Offline`, it's confused me in the AskTUG [手动删除tidb-data下面的pd和tikv目录，如何恢复](https://asktug.com/t/topic/68469/17)

https://github.com/tikv/pd/blob/20b00a7c4933e307c5423da0c5047250259e19e9/server/api/store.go#L223-L229

But pd can set state to tombstone actually

https://github.com/tikv/pd/blob/20b00a7c4933e307c5423da0c5047250259e19e9/server/cluster/cluster.go#L1040-L1075

### What version of PD are you using (`pd-server -V`)?

```text
[root@localhost ~]# tiup ctl:v5.1.1 pd -V
Starting component `ctl`: /root/.tiup/components/ctl/v5.1.1/ctl pd -V
Release Version: v5.1.1
Edition: Community
Git Commit Hash: 7cba1912b317a533e18b16ea2ba9a14ed2891129
Git Branch: heads/refs/tags/v5.1.1
UTC Build Time:  2021-07-23 01:16:35
```

**Comment by nolouch** [comment]
There is an issue with it: https://github.com/tikv/pd/issues/3076
we support physically destroyed to replace it.
