### ISSUE TITLE
Show CPU usage for each Region 

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#4042]
## Development Task
For easy to find the CPU-sensitive hot region
 
- [x] https://github.com/tikv/tikv/pull/10789
- [ ] https://github.com/tikv/pd/pull/5696

**Comment by lhy1024** [comment]
any update? @JmPotato

**Comment by JmPotato** [comment]
> any update? @JmPotato 

Since the region CPU metering is on by default now on TiKV side, I think we can push this PR move on.
