### ISSUE TITLE
Store the histroy hot regions

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#4066]
## Development Task
history hot region helps us to find the hotspot issues, we can persist hot information for a period of time for preservation.
* Implemention PRs:
    1. tikv/pd/pull/4019
    2. tikv/pd/pull/4020
    3. tikv/pd/pull/4021

**Comment by qidi1** [comment]
Add pr to fix cluster bug.
* #4121

**Comment by qidi1** [comment]
docs PRs:
* pingcap/docs-cn/pull/7163
* pingcap/docs/pull/6627

**Comment by rleungx** [comment]
Close it. For more details, see https://github.com/pingcap/tidb/issues/25281.
