### ISSUE TITLE
evict-leader may leave leaders when the cluster has down-peers

### ISSUE THREAD

**Issue by HunDunDM** [tikv/pd#4093]
### What did you do?

* Start a cluster with 3 TiKV (tikv-1, tikv-2, tikv-3)
* Let the tikv-3 be forced to shutdown, and wait for the PD to think that the TiKV is down
* Add evict-leader-scheduler for tikv-2

### What did you expect to see?

* All leaders are on tikv-1

### What did you see instead?

* Some Leaders are on tikv-2
* It will cause TiKV to be blocked from restarting

### What version of PD are you using (`pd-server -V`)?

* master d9c6086

**Comment by mayjiang0203** [comment]
severity Moderate

**Comment by HunDunDM** [comment]
related #1005
