### ISSUE TITLE
schedule statics  metrics not clear 

### ISSUE THREAD

**Issue by bufferflies** [tikv/pd#4094]
### Describe your feature request related problem
scheduler some metrics is not clear such as 
![image](https://user-images.githubusercontent.com/23159587/132462731-2e600b57-6bd0-4e70-9c4f-e04114b804d8.png)

the relation between skip、total、  schedule,no-place is not clear 

### Describe the feature you'd like
some metrics needs refine

**Comment by bufferflies** [comment]
In past, the relation is

![image](https://user-images.githubusercontent.com/23159587/132465738-8be20aed-9b83-43d3-b015-359e8fb1f8da.png)

**Comment by rleungx** [comment]
I have already raised an issue before. See https://github.com/tikv/pd/issues/3058.
