### ISSUE TITLE
support abort deleting a store

### ISSUE THREAD

**Issue by BusyJay** [tikv/pd#4098]
### Describe the feature you'd like

It's possible that user accidentally deletes a undesired store. Currently, there is an undocumented way to abort the operation by:
```
curl -X POST http://<ip>:<port>/pd/api/v1/store/<store_id>/state?state=Up
```
. The operation is dangerous as it allows changing state manually. A more safe way is providing a public and well documented command/API to abort the operation.

**Comment by HunDunDM** [comment]
PD above v5.0 only allows Store state to change from `Offline` to `Up`. Attempts to change `Tombstone` to `Up` will fail.
