### ISSUE TITLE
Adding admin operator is not restricted by store limit

### ISSUE THREAD

**Issue by HunDunDM** [tikv/pd#4135]
### Describe your feature request related problem

![image](https://user-images.githubusercontent.com/19789302/133736567-add6eede-2d68-497b-87ca-6b5fc05034e1.png)

### Describe the feature you'd like

Adding admin operator is not restricted by store limit

**Comment by aidendou** [comment]
is this considered fixed by this [PR](https://github.com/tikv/pd/pull/4649/files#diff-9ab121d4ebedea8515d8482955d3142b9b6f4728eb14e29ba048d10b7dbd6d09)?
