### ISSUE TITLE
Update Region Meta in advance during ReportBatchSplit

### ISSUE THREAD

**Issue by HunDunDM** [tikv/pd#4157]
### Describe your feature request related problem

After the split occurs in the Region, Heartbeat is relied on to update the Region Meta. The Range hole will be generated during the update, and the Region corresponding to the Range cannot be queried in a short time.

When the PD heartbeat processing is not fast enough, the problem will be magnified.

### Describe the feature you'd like

Update Region Meta in advance during `ReportBatchSplit`

**Comment by sticnarf** [comment]
Is there any plan or design doc for these enhancement? I am a bit curious about the handling or rollback if split fails at TiKV.

**Comment by HunDunDM** [comment]
> Is there any plan or design doc for this enhancement? I am a bit curious about the handling or rollback if split fails at TiKV.

`ReportBatchSplit` should happen after the split is successful? Because of correctness issues, `AskBatchSplit` is not used.

**Comment by Connor1996** [comment]
So you mean to update the region meta after `AskBatchSplit`?

**Comment by nolouch** [comment]
> So you mean to update the region meta after `AskBatchSplit`?

Yes, `AskBatchSplit` will be more timely. If there is a bottleneck in heartbeat processing, a separate RPC can be processed with a higher priority.

**Comment by CabinfeverB** [comment]
@bufferflies do we need to reopen because of the revert of 6867
