### ISSUE TITLE
ScheduleConfig is not loaded from storage

### ISSUE THREAD

**Issue by xingyong** [tikv/pd#4188]
### What did you do?

Execute this command, and restart pd, src-tolerance-ratio will go back to the default value 1.05
/pd-ctl scheduler config balance-hot-region-scheduler set src-tolerance-ratio 2

The reason is that schedule config is persisted by SaveScheduleConfig(), but not reloaded anywhere. The LoadScheduleConfig() is not called at all. 

### What did you expect to see?
src-tolerance-ratio will keep to be the manual set value.

### What did you see instead?
src-tolerance-ratio is 1.05 after pd restarts.

### What version of PD are you using (`pd-server -V`)?
master

**Comment by sylzd** [comment]
If the config `schedule.tolerant-size-ratio` may solve it?

**Comment by rleungx** [comment]
@xingyong I cannot reproduce this problem in the latest master. Would you like to try it again? `LoadScheduleConfig()` is not used anymore because we will load the config through https://github.com/tikv/pd/blob/02848d2660ee105a7bef9e02f485a588132abc4f/server/cluster/coordinator.go#L315

**Comment by rleungx** [comment]
I'm going to mark this issue as a question. If this problem still exists, feel free to ping me.

**Comment by rleungx** [comment]
Close it since it's stale
