### ISSUE TITLE
PD HTTP API self-protection

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#4207]
### Describe your feature request related problem

PD is the most important metadata service center of the cluster, and it also includes TSO services. PD needs to have certain self-protection capabilities, among which, we need to limit the access rate of some heavy APIs. here, we focus HTTP API first.

### Describe the feature you'd like

Consider add middleware, use ratelimiter to limit the rate of the HeavyAPIs request, such as `/hotspot/regions/history` 

### Teachability, Documentation, Adoption, Migration Strategy

- [middleware](https://chai2010.gitbooks.io/advanced-go-programming-book/content/ch5-web/ch5-03-middleware.html)

**Comment by CabinfeverB** [comment]
refer #4480, Closed since most tasks has been finished.
