### ISSUE TITLE
Can not go get pd : package github.com/tikv/pd: build constraints exclude all Go files

### ISSUE THREAD

**Issue by Ehco1996** [tikv/pd#4225]
### What did you do?

`go get github.com/tikv/pd@master`

### What did you expect to see?
go get success

### What did you see instead?

```bash
➜ go get github.com/tikv/pd@master
github.com/tikv/pd: no Go source files
package github.com/tikv/pd: build constraints exclude all Go files in /Users/ehco/.gvm/pkgsets/go1.16.8/global/pkg/mod/github.com/tikv/pd@v1.1.0-beta.0.20211019031642-b4c1804adbec

```
### What version of PD are you using (`pd-server -V`)?

master

### My speculation

seems `pkg/dashboard/uiserver/`   lose some file

in the code in go mod package: , 
```bash
Documents/code/pd@v1.1.0-beta.0.20211019031642-b4c1804adbec  via 🐹 v1.16.8 
➜ ls pkg/dashboard/uiserver
embedded_assets_rewriter.go
```

but in master:

```bash
pd on  master via 🐹 v1.16.8
➜ ls pkg/dashboard/uiserver
embedded_assets_handler.go  embedded_assets_rewriter.go
```

**Comment by rleungx** [comment]
`embedded_assets_handler.go` is downloaded from `tidb-dashboard`. And can you describe your requirement？

**Comment by Ehco1996** [comment]
> `embedded_assets_handler.go` is downloaded from `tidb-dashboard`. And can you describe your requirement？

thanks for you reply
my requirement is upgrade the [pd](https://github.com/pingcap/tidb/blob/00054d86cc3284ac5206d0c89968d324294c387c/go.mod#L69) in the tidb dependency, so that i can use new API of pd-client
