### ISSUE TITLE
After set store limit to 1w, offline process hung for more than 8 hours

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/pd#4226]
### What did you do?
Set pd parameters as following.
  "replica-schedule-limit": 2048,
    "scheduler-max-waiting-operator": 100,
/ # /pd-ctl store limit
{
  "1": {
    "add-peer": 100000000,
    "remove-peer": 100000000
  },
  "10": {
    "add-peer": 100000000,
    "remove-peer": 100000000
  },

### What did you expect to see?
Offline should works fine.
### What did you see instead?
![image](https://user-images.githubusercontent.com/9443637/138022972-8a18be56-4219-4acf-9edb-ac9f58fe9eaa.png)

### What version of PD are you using (`pd-server -V`)?
4.1.15

**Comment by bufferflies** [comment]
it is solved by #4139
