### ISSUE TITLE
After recover from one az down, Down peer hung for more than 1 hours.

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/pd#4227]
### What did you do?
	//Run workload
	cmdlist := StartWorkload(ctxg, tc, sysBench, runtime, g, []string{})
	oltppkg.WaitFor(ctxg, "waiting for workload running", 5*time.Minute)

	//Set pd config
	pd := Try(pdclient.NewPDClient(tc)).(*pdclient.Client)
	Try(pd.SetSchedulerConfig("max-store-down-time", "5m0s"))

	//Inject chaos
	oltppkg.LogAndBy("Step 2: Inject one az down periodically")
	c := chaos.Chaos{
		Name:           "azdown",
		Tc:             tc,
		ExperimentSpec: chaos.FailureExperiment(15*time.Minute, "@every 20m"),
		SelectorOpts:   chaos.SelectAllTiKVInOneAZ("zone1"),
	}
	Try(c.Run())

	//Delete chaos and let workload run 10min
	oltppkg.SleepWithCtx(ctxg, 10*time.Minute)
	Try(c.Clean())
	oltppkg.WaitFor(ctxg, "waiting for workload running", 5*time.Minute)

	//Waiting for region healthy
	oltppkg.LogAndBy("Step 3: Waiting region healthy.")
	Eventually(func() bool {
		return oltppkg.CheckRegionHealth(tc)
	}, 60*time.Minute, 1*time.Minute).Should(BeTrue())

### What did you expect to see?
Down peer can back to 0 in 1 hours.

### What did you see instead?
Count of down peer keep stoping at 94 for more than 1 hour, back to 0 after restart the tikv pod.
![image](https://user-images.githubusercontent.com/9443637/138081173-a0d7f3cd-2b41-46b4-8703-7a12ce4a7837.png)

### What version of PD are you using (`pd-server -V`)?
/ # /pd-ctl -V
Release Version: v5.0.1
Edition: Community
Git Commit Hash: ea1449c7c693d94661b3c60d35b8679ebfb3da34
Git Branch: heads/refs/tags/v5.0.1
UTC Build Time:  2021-04-23 05:59:50
/ # /tikv-server -V
TiKV
Release Version:   5.0.1
Edition:           Community
Git Commit Hash:   e26389a278116b2f61addfa9f15ca25ecf38bc80
Git Commit Branch: heads/refs/tags/v5.0.1
UTC Build Time:    2021-04-23 08:24:13
Rust Version:      rustc 1.51.0-nightly (bc39d4d9c 2021-01-15)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release

**Comment by bufferflies** [comment]
It will reopen when the problem happen again
