### ISSUE TITLE
pd-ctl: add more information about scheduler

### ISSUE THREAD

**Issue by w41ter** [tikv/pd#4231]
### Describe your feature request related problem

First:

» scheduler show
[
  "balance-leader-scheduler",
  "balance-region-scheduler",
  "evict-leader-scheduler",
  "label-scheduler",
  "balance-hot-region-scheduler"
]

In the output of `scheduler show`, I couldn't figure out which store the evict-leader-scheduler belongs to.

Second:

» scheduler show --status
Usage:
  pd-ctl scheduler show [flags]

Flags:
  -h, --help            help for show
      --status string   the scheduler status

What is the valid value of `--status`? maybe we could list all acceptable values in the usage?

**Comment by CabinfeverB** [comment]
For the first problem, more info can be found by using the command `scheduler config`. 
eg. `scheduler config  evict-leader-scheduler`
```
{
  "store-id-ranges": {
    "60": [
      {
        "start-key": "",
        "end-key": ""
      }
    ]
  }
}
```

**Comment by CabinfeverB** [comment]
For the second problem, #4453 maybe has fixed it

**Comment by rleungx** [comment]
Close it since #4452 is merged.
