### ISSUE TITLE
PD should refuse  change store limit after set store-limit-mode==auto

### ISSUE THREAD

**Issue by bufferflies** [tikv/pd#4276]
### What did you do?
1. set store-limit-mode auto 
2. store limit all 10 remove-peer ==>change succ 
3. store limit ==> remove-peer:100 

change failed 

### What did you expect to see?
it should refuse the request of store limit in store-limit-mode==auto;

**Comment by rleungx** [comment]
When you change the store limit in auto mode, the mode will be changed once the operation successes.

**Comment by nolouch** [comment]
remote it in document.

**Comment by rleungx** [comment]
I'm going to remove this feature from pd-ctl user document. See https://github.com/pingcap/docs-cn/pull/7429

**Comment by rleungx** [comment]
> When you change the store limit manually in auto mode, the value will be overridden.

**Comment by bufferflies** [comment]
Ok, it will ignore the limit scene.
