### ISSUE TITLE
Fix the defer leak inside the connectionCtxs updater

### ISSUE THREAD

**Issue by JmPotato** [tikv/pd#4279]
### What did you do?

See https://github.com/tikv/pd/blob/e5d7be15786a1a369106131962b835c4e5736891/client/client.go#L686

It's a `defer` inside a loop, which will cause resource leak.

### What did you expect to see?

Close the unused ticker in a proper way ASAP.

### What did you see instead?

Resource leak.

### What version of PD are you using (`pd-server -V`)?

e5d7be1

**Comment by mayjiang0203** [comment]
Since it occur before GA
/severity Moderate
