### ISSUE TITLE
Unify the key path management

### ISSUE THREAD

**Issue by JmPotato** [tikv/pd#4284]
### Describe your feature request related problem

PD server will store many different keys into the backend etcd storage in terms of different usage. However, the key path management now is very chaotic. For example, we have two different places to make a bootstrap time key.

https://github.com/tikv/pd/blob/e5d7be15786a1a369106131962b835c4e5736891/server/util.go#L138-L140

https://github.com/tikv/pd/blob/e5d7be15786a1a369106131962b835c4e5736891/server/core/storage.go#L129-L132

Besides, the etcd kv is initialized with the `rootPath`, the developer may easily miss out on this point to access a key with the wrong key path.

https://github.com/tikv/pd/blob/e5d7be15786a1a369106131962b835c4e5736891/server/kv/etcd_kv.go#L42-L48

### Describe the feature you'd like

We better introduce a data structure or interface to provide a unified key path management feature.

**Comment by rleungx** [comment]
Some compatibility problems also need to be considered.

**Comment by JmPotato** [comment]
Another problem with the same root case: https://github.com/tikv/pd/issues/4109

**Comment by JmPotato** [comment]
Another problem with the same root case: https://github.com/tikv/pd/issues/4109
