### ISSUE TITLE
Continuously update the tidb dashboard (release-5.3)

### ISSUE THREAD

**Issue by baurine** [tikv/pd#4300]
# Development Task

Before every version greater than 5.3 is released, we need to update the [tidb-dashboard](https://github.com/pingcap-incubator/tidb-dashboard). This issue is to track the update actions of each version.

Before each version is released, we need to do:

- Update `tidb-dashboard` to the latest release version.
- Record version information in this issue.
- Move this issue to the next release milestone.

### Version Information

| PD Version | TiDB Dashboard Version |
|------------|-------------------------|
| v5.3.0         | v2021.11.08.1   |

### Previous Versions

- release-4.0 #3021 
- release-5.0 #3573 
- release-5.1 #3863 
- release-5.2 #4247

**Comment by HunDunDM** [comment]
Replaced by this [wiki](https://github.com/pingcap/tidb-dashboard/wiki/TiDB-Dashboard-%C3%97-PD-Version-Matrix).
