### ISSUE TITLE
DR Auto-Sync: missing DR_STATE files for newly added(scaled-out) PD nodes

### ISSUE THREAD

**Issue by tshqin** [tikv/pd#4327]
### What did you do?

1. setup DR Auto-Sync deployment with only 1 PD node, there will be a DR_STATE in the PD data directory.
2. scale-out 2 new PD nodes.
3. the DR_STATE files are missing on the new PD nodes, even you wait for a while.
unless you make a failure on the DR nodes, wait until the replication mode automatically changed to async, then you remove the failure and replication mode changes again, and you will see the DR_STATE file appears on each node.

### What did you expect to see?
the DR_STATE should appear on any newly added PD nodes

### What version of PD are you using (`pd-server -V`)?
```
Release Version: v5.2.2
Edition: Community
Git Commit Hash: 02139dc2a160e24215f634a82b943b2157a2e8ed
Git Branch: heads/refs/tags/v5.2.2
UTC Build Time:  2021-10-20 06:03:52
```

**Comment by mayjiang0203** [comment]
Can't reproduce it, so mark it moderate.
/severity moderate
