### ISSUE TITLE
Verify better hot scheduler default parameter values

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#4332]
## Development Task

- [x] Write Leader use `[qps, bytes]`
- [x] Change `strict-picking-store` from `true` to `false`

Need to verify.

**Comment by nolouch** [comment]
cc @lhy1024

**Comment by lhy1024** [comment]
Change strict-picking-store from true to false?

**Comment by lhy1024** [comment]
it is closed by #5590. In 6.4, the priority of write leader use `[qps, bytes]`, and we introduce v2 region rank formula, it will replace `strict-picking-store`
