### ISSUE TITLE
unstable test `regionSyncerTestSuite.TestRegionSyncer`

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#4348]
## Development Task
`regionSyncerTestSuite.TestRegionSyncer` easy to failed.
details: https://ci2.pingcap.net/blue/organizations/jenkins/pd_test/detail/pd_test/3446/pipeline

**Comment by HunDunDM** [comment]
ref #4294

**Comment by rleungx** [comment]
https://ci2.pingcap.net/blue/organizations/jenkins/pd_test/detail/pd_test/3506/ happened again

**Comment by nolouch** [comment]
ref https://github.com/tikv/pd/pull/4360

**Comment by rleungx** [comment]
Closed via #4360.
