### ISSUE TITLE
TiDB Dashboard key visual service stopped error

### ISSUE THREAD

**Issue by shhdgit** [tikv/pd#4361]
### What did you do?

The dashboard of a cluster that was started within a minute and restarted may not use key viz.
![middle_img_v2_022d603a-a78e-4224-8afa-9a2b2831958g](https://user-images.githubusercontent.com/11549583/142874382-861ec2bd-0765-48ef-b295-8279b50a474c.png)

Related PR at tidb-dashboard: https://github.com/pingcap/tidb-dashboard/pull/1065#event-5651952393

### What did you expect to see?

Key viz works fine in the dashboard.

### What did you see instead?

Key viz stopped.

### What version of PD are you using (`pd-server -V`)?
5.3.0

**Comment by rleungx** [comment]
@HunDunDM PTAL, thanks.

**Comment by HunDunDM** [comment]
fixed by #4425
