### ISSUE TITLE
CPU is not balanced always while running oltp write only

### ISSUE THREAD

**Issue by Lily2025** [tikv/pd#4404]
### What did you do?
1、br import another data，kill br when br is running
2、import data again：s3://benchmark/sysbench-32-10000000
3、run sysbench write only 
sysbench --mysql-user=root --db-driver=mysql --time=0 --report-interval=10 --mysql-db=test --mysql-host=tc-tidb.glh-512-zvzbw --mysql-port=4000 --threads=64 --tables=32 --table-size=10000000 --mysql-ignore-errors=2013 oltp_write_only run

### What did you expect to see?
all CPU are balanced

### What did you see instead?
CPU is not balanced always while running oltp write only
![OnJcWaHhRH](https://user-images.githubusercontent.com/84712107/144004725-a34b15e6-91a1-4a10-a067-60cbd2c6edb5.png)

### What version of PD are you using (`pd-server -V`)?
/ # ./pd-server -V
Release Version: v5.1.2
Edition: Community
Git Commit Hash: b6d8d5a01ecc022441ca11b866647c94b5cb435d
Git Branch: heads/refs/tags/v5.1.2
UTC Build Time:  2021-09-27 02:49:05

**Comment by lhy1024** [comment]
![image](https://user-images.githubusercontent.com/19542290/144005574-d9f11490-f0b2-4f92-91cb-1bcf4c15ba40.png)
![image](https://user-images.githubusercontent.com/19542290/144005619-7c406f21-61c1-4c18-8b79-62b93fc0b2d3.png)
some hot peer are not identified

**Comment by lhy1024** [comment]
![image](https://user-images.githubusercontent.com/19542290/144014886-c259e86e-e81e-422b-9396-4af5b5f27c8a.png)

![image](https://user-images.githubusercontent.com/19542290/144014518-ad12c3e7-b986-4030-86be-cdd8db7cf2fb.png)

abnormal exited BR pause scheduler.
