### ISSUE TITLE
Add parameter prompt for scheduler show --status

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#4405]
There is no prompt for `scheduler show --status` command to indicate the value of status. See:

```
» scheduler show --status
Usage:
  pd-ctl scheduler show [flags]

Flags:
  -h, --help            help for show
      --status string   the scheduler status

flag needs an argument: --status
```

**Comment by lhy1024** [comment]
It is better to clarify that `scheduler show` includes all the status including pause, if this parameter is not added
