### ISSUE TITLE
Performance dropped after start scheduling than pause scheduling in 5.1.2 version 

### ISSUE THREAD

**Issue by Lily2025** [tikv/pd#4407]
### What did you do?
1、br import another data，kill br when br is running
2、import data again：s3://benchmark/sysbench-32-10000000
3、run sysbench，found CPU was not balanced（root case：scheduler was paused（https://github.com/tikv/pd/issues/4406））
4、recover scheduler Manually
5、CPU was more balanced than step 3，but still was not balanced，and QPS dropped，99 duration Increased

### What did you expect to see?
Performance can not dropped after recover scheduling than pause scheduling

### What did you see instead?
Performance dropped after recover scheduling than pause scheduling
![image](https://user-images.githubusercontent.com/84712107/144174540-c242c742-3696-4933-8c47-556ecb8bcd6f.png)
![image](https://user-images.githubusercontent.com/84712107/144174271-dba39f07-fed7-4e08-84d5-30c8fea46700.png)

### What version of PD are you using (`pd-server -V`)?
/ # ./pd-server -V
Release Version: v5.1.2
Edition: Community
Git Commit Hash: b6d8d5a
Git Branch: heads/refs/tags/v5.1.2
UTC Build Time: 2021-09-27 02:49:05

**Comment by lhy1024** [comment]
According to the available logs, we can see `resume scheduler` was sent in the BR, but the corresponding scheduler of PD is still paused.

There is no better way to troubleshoot this, so we added some logs in #4452.
