### ISSUE TITLE
Removing voter from 2 voter replicas raft group would make region unavailable

### ISSUE THREAD

**Issue by w41ter-l** [tikv/pd#4411]
### What did you do?

Remove a voter from 2 voter replicas.  Details in https://github.com/tikv/tikv/issues/10595.

### What did you expect to see?

Region shouldn't be unavailable.

### What did you see instead?

A region would be unavailable.

**Comment by PatrickNicholas** [comment]
This is part of work in tikv: https://github.com/tikv/tikv/pull/11502

**Comment by PatrickNicholas** [comment]
This is part of work in tikv: https://github.com/tikv/tikv/pull/11502

**Comment by HunDunDM** [comment]
Need to solve #4444 first.
