### ISSUE TITLE
`pd-ctl` supports `operator explain`

### ISSUE THREAD

**Issue by HunDunDM** [tikv/pd#4418]
### Describe your feature request related problem

Sometimes, I want to know why some schedule operators cannot be generated.

### Describe the feature you'd like

`pd-ctl operator explain`, likes `pd-ctl operator add`.

Check whether the current PD can naturally generate this schedule operator. If not, then explain what prevents it. The operator is not actually performed.

```
❯ pd-ctl operator explain --help
explain an operator

Usage:
  pd-ctl operator explain [command]

Available Commands:
  add-learner     add a region learner on specified store
  add-peer        add a region peer on specified store
  merge-region    merge source region into target region
  remove-peer     remove a region peer on specified store
  transfer-leader transfer a region's leader to the specified store
  transfer-peer   transfer a region's peer from the specified store to another store
```
### Describe alternatives you've considered

`pd-ctl operator add --explain`, and optimize the result, ref #4135. However, this operator is an admin operator and has fewer restrictions.

### Teachability, Documentation, Adoption, Migration Strategy

* Golang

**Comment by nolouch** [comment]
Good Idea！
