### ISSUE TITLE
TiKV cpu usage is not balance after upgrade from 5.2.3 to 5.3.0

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/pd#4419]
### What did you do?

Workload: sysbench 64 threads, write only workload
Env: 3 pd (4 core CPU/8G memory),, 4 tikv (8 core CPU/16G memory), 2 tidb (8 core CPU/16G memory),

### What did you expect to see?
Should act same with data before upgragde.

### What did you see instead?
After upgrade, qps drop from 25K to 22K, some may cause by tikv is not balance as it do before.
![image](https://user-images.githubusercontent.com/9443637/144374936-add1596a-ae0f-4dce-b0e5-38cd4817c0ca.png)

![image](https://user-images.githubusercontent.com/9443637/144374376-08c82804-ccc6-4c56-9f27-5ee142f465bd.png)

### What version of PD are you using (`pd-server -V`)?
/ # /pd-server -V
Release Version: v5.3.0
Edition: Community
Git Commit Hash: fe6fab9268d2d6fd34cd22edd1cf31a302e8dc5c
Git Branch: heads/refs/tags/v5.3.0
UTC Build Time:  2021-11-22 10:50:33

**Comment by nolouch** [comment]
I think is not a bug, may some behavior changed. I change it to be a question. If you have any questions you can reply to this issue.

**Comment by mayjiang0203** [comment]
![image](https://user-images.githubusercontent.com/9443637/146721453-2f4339d7-1e49-495c-a37f-d06fe7af1d6e.png)
Same workload and same cluster configuration, can't reproduce it. As we can see from above picture, now tikv cpu is balance.

**Comment by lhy1024** [comment]
It is possible that the performance is different between stores in the previous tests. Before scheduling, the requests were uneven, and the store with low performance happened to have fewer requests; after scheduling, the store with low performance had more requests.

**Comment by lhy1024** [comment]
I will close it and feel free to reopen it.
