### ISSUE TITLE
Incorrect behavior when using `pd-ctl` to pause the scheduler

### ISSUE THREAD

**Issue by HunDunDM** [tikv/pd#4420]
### What did you do?

`pd-ctl scheduler pause balance-hot-region-scheduler`

### What did you expect to see?

An error is reported, or the scheduler is paused permanently, or the schedule is paused for thirty minutes by default.

### What did you see instead?

Actually equivalent to executing `pd-ctl scheduler resume balance-hot-region-scheduler`.

### What version of PD are you using (`pd-server -V`)?

v5.3.0

**Comment by disksing** [comment]
Report an error.
