### ISSUE TITLE
 store heartbeat report larger than max (2320821 vs 2097152)

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#4429]
### What did you see?
![image](https://user-images.githubusercontent.com/6428910/144809466-3aaedd31-f210-4907-a88f-174296832010.png)

[in etcd](https://github.com/etcd-io/etcd/blob/29292aa7bdafaf65cb5e054591fe0ff07b36f5ee/server/etcdserver/api/v3rpc/grpc.go#L69-L71): 

```
	opts = append(opts, grpc.MaxRecvMsgSize(int(s.Cfg.MaxRequestBytes+grpcOverheadBytes)))
	opts = append(opts, grpc.MaxSendMsgSize(maxSendBytes))
	opts = append(opts, grpc.MaxConcurrentStreams(maxStreams))
```

[DefaultMaxRequestBytes = 1.5 * 1024 * 1024 ]( https://github.com/etcd-io/etcd/blob/29292aa7bdafaf65cb5e054591fe0ff07b36f5ee/server/embed/config.go#L58)

grpcOverheadBytes = 0.5 * 1024* 1024

So the recvMessage max size is 2 * 1024 * 1024, equal `2097152`

### What version of PD are you using (`pd-server -V`)?
- 5.1, 5.2, 5.3

**Comment by rleungx** [comment]
We can customize the `max-request-bytes` now. And the default value has been changed to 150MB. If there is still a problem, please reopen this issue.
