### ISSUE TITLE
core: hot history region storage cant get is_leader info and format error

### ISSUE THREAD

**Issue by qidi1** [tikv/pd#4449]
### What did you do?

when we use  `TIDB_HOT_REGIONS_HISTORY` table to get hot region history info,The `isLeader` field is always false,and The `startKey` and `endKey` fields formatted like `dIAAAAAAAAD/aF9ygAAAAAD/CrGkAAAAAAD6` is also not what we want to see

### What did you expect to see?

we expect to get  `isLeader`  info and  The `startKey` and `endKey` fields formatted like `dIAAAAAAAAD/aF9ygAAAAAD/CrGkAAAAAAD6` can be see like this `7480000000000001FF8800000000000000F8`.

**Comment by rleungx** [comment]
Closed via #4450.
