### ISSUE TITLE
Improve the speed of the balance-leader-scheduler

### ISSUE THREAD

**Issue by HunDunDM** [tikv/pd#4454]
### Describe your feature request related problem

The current scheduler can only execute 6K times per minute due to the limitation of [MinScheduleInterval](https://github.com/tikv/pd/blob/v5.3.0/server/schedulers/base_scheduler.go#L32), so the balance-leader operator can only generate 6K times per minute. When the cluster has 50 * 10K regions, it takes tens of minutes to complete the balance-leader after rolling restart.

### Describe the feature you'd like

When the number of leaders differs greatly, support one scheduler to generate multiple operators.

### Describe alternatives you've considered

Decrease `MinScheduleInterval` for balance-leader-scheduler.

### Teachability, Documentation, Adoption, Migration Strategy

* Go

**Comment by nolouch** [comment]
We can batch the operator similar https://github.com/tikv/pd/pull/4008.

**Comment by rleungx** [comment]
Duplicated with #4610.
