### ISSUE TITLE
sync tikv config

### ISSUE THREAD

**Issue by bufferflies** [tikv/pd#4459]
## Enhancement Task
Config supports `region-max-size` property. This value should only be set by file not by api.

**Comment by bufferflies** [comment]
The operator will be cancel if it's started time duration excceed than timeout time(10m). 
I think one operator includes moving a 10Gb's region step will be can be calculate by: the generator sst + transfer sst + apply sst. And the generator sst  will cancel if retry time excceed than 5 and the transfer sst has fluid control（100Mb/s)

**Comment by bufferflies** [comment]
I think the timeout  value should be conservative.  The value can use the below formula： 
duration=10m+ （regionSize/Mb /100Mb/s) *(receiving_count+sending_count)*5 =10*60+ regionSize*6*5/100s=600+ regionSize*0.3
if region size is 10g, the duration should be  ： 600+10*1000*0.3=3600s=2h

**Comment by lhy1024** [comment]
There may be some operators buildup that prevents other operators from executing properly.

**Comment by BusyJay** [comment]
What if the region size is not initialized before the operator is created?

**Comment by bufferflies** [comment]
The size of one region  will be 1MB if region reports without size. So if the real size of region is bigger like 1GB not 1Mb, the operator will be cancel because of timeout.
