### ISSUE TITLE
TiDB Dashboard unexpected pd request header & ErrMissingWhereClause error

### ISSUE THREAD

**Issue by shhdgit** [tikv/pd#4465]
## Bug Report

There are 2 known dashboard issues:
- https://github.com/pingcap/tidb-dashboard/pull/1069
- https://github.com/pingcap/tidb-dashboard/pull/1065

It's a bug fix version.

![image](https://user-images.githubusercontent.com/6428910/146710149-27bc842c-116c-418f-a9dc-6a103b651260.png)

### What did you do?

- After profiling pd, the pd client always carry unexpected header `PD-Allow-follower-handle: true`. 
- We will get a ErrMissingWhereClause error in keyviz if restart TiDB Dashboard twice in 1 min.

### What did you expect to see?

No errors

### What version of PD are you using (`pd-server -V`)?

4.0.16, 5.0.5, 5.1.3

**Comment by rleungx** [comment]
Seem it has already been fixed, close it.
