### ISSUE TITLE
Support to view http request audit log

### ISSUE THREAD

**Issue by srstack** [tikv/pd#4468]
### Describe your feature request related problem

Record the relevant information of the http request and record it in the audit log, which is convenient for quickly locating the problem in the event of a fault

### Describe the feature you'd like

display the request source ip , source port  and request path.

**Comment by rleungx** [comment]
We are planning to do it. You can find more detailed information in https://github.com/tikv/pd/issues/3383.

**Comment by rleungx** [comment]
Closed since #4601 has been finished.
