### ISSUE TITLE
`LeaderPriority` and `GitHash` are actually not available through `GetMembers` of GRPC

### ISSUE THREAD

**Issue by HunDunDM** [tikv/pd#4473]
### What did you do?

In the definition of [pdpb.Member of kvproto](https://github.com/pingcap/kvproto/blob/d0692eebe1ed1827811b24a377a45b3bed58f15b/proto/pdpb.proto#L327~L330), there are fields such as `leader_priority`, `deploy_path`, `binary_version`, `git_hash`.

They are in the return of `GetMembers`.

### What did you expect to see?

They can be obtained through the GRPC.

### What did you see instead?

In fact, they can only be obtained through the API.

ref [server/api/member.go#L62](https://github.com/tikv/pd/blob/v5.3.0/server/api/member.go#L62)

### What version of PD are you using (`pd-server -V`)?

v5.3.0

**Comment by HunDunDM** [comment]
Maybe this is a behavior in design, but it may lead to incorrect use.

**Comment by rleungx** [comment]
I think it is intended. Change the type to enhancement.
