### ISSUE TITLE
Refactor hot region related modules

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#4477]
## Motivation
We recently encountered a scheduling problem caused by the statistics module, see the issue for details: https://github.com/tikv/pd/issues/4390

statistics is an important module for scheduling, it is basic and important. I see some problems:
- Difficult Maintain. For example, hot cache statics have many flags and states, it's hard to maintain.
- Lack Test. This module is best to prevent problems through a unit test. the unit test should be enhanced.
- More Robust. Statistics is also the sensor in the feedback system. we should make it more robust even the heartbeat frequency is changed.

**Comment by nolouch** [comment]
Relative:

- [ ] https://github.com/tikv/pd/issues/4463

**Comment by lhy1024** [comment]
@rleungx Can we close it?
