### ISSUE TITLE
`pd-ctl` should provide command to check paused scheduler status

### ISSUE THREAD

**Issue by matchge-ca** [tikv/pd#4487]
## Enhancement Task
The current `pd-ctl` only expose whether a scheduler is paused or not, it should also be able to provide following information for better understanding of the scheduler status:
- How long a scheduler has been paused
- How long a scheduler will be resumed

**Comment by bufferflies** [comment]
resumed should be work immediately, so it should not need to know the duration.

**Comment by matchge-ca** [comment]
@HunDunDM @bufferflies I need some suggestions on the implementation:
- How long a scheduler has been paused: the `scheduleController` doesn't store the time when the `delayUntil` is assigned, but user can find similar information from the pd log that has been implemented in this PR (https://github.com/tikv/pd/pull/4452)
- How long a scheduler will be resumed: this is doable by comparing the value of `delayUntil` and current timestamp. However, it requires an API change, either an new flag to retrieve the TTL value of a paused scheduler **OR** change the return format/value of `scheduler show --status paused` 
For example:
  - New flag `--ttl` under `scheduler show`
    ```
    pd-ctl scheduler show --status paused --ttl
    [
        "balance-hot-region-scheduler", 100
    ]
    ```
  - Change the return format
      ```
    pd-ctl scheduler show --status paused
    [
          "balance-region-scheduler", 85,
          "balance-hot-region-scheduler", 100
    ]
    ```
- There is also a minor bug/flaw in the `pauseOrResumeScheduler` func. It doesn't validate based on the keywords (`pause` or `resume`), but based on the value of `delay`, so users can execute following command and pause the scheduler for 20 seconds instead of resume it, worth an issue to fix it or this will be improved in APIv2?
``` pd-ctl scheduler resume balance-region-scheduler 20```

Any thought? Thanks.

**Comment by HunDunDM** [comment]
> `How long a scheduler has been paused`

Is it okay to store `time.now` when storing `delayUntil`?

> How long a scheduler will be resumed

```

> `pd-ctl scheduler resume balance-region-scheduler 20`

fixed by #4421

**Comment by bufferflies** [comment]
> Thanks

how about the response show the time unit:
`[
    "balance-hot-region-scheduler", 100s
]`

**Comment by matchge-ca** [comment]
> > `How long a scheduler has been paused`
> 
> Is it okay to store `time.now` when storing `delayUntil`?

Sure, we can store the unix time when pause the scheduler

> 
> > How long a scheduler will be resumed
> 
> ```
> [
>     "balance-hot-region-scheduler", 100
> ]
> ```
> 
> This is not a valid JSON. Maybe add an API or put it in APIV2 better? @rleungx

What do you mean by `not a valid JSON`? 
@rleungx any comment on we should include this change in current API or API v2?
