### ISSUE TITLE
`delta()` should not be used in counter

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#4489]
## Bug Report

According to https://prometheus.io/docs/prometheus/latest/querying/functions/#delta: _"delta should only be used with gauges"_.
But we have some counters that use the delta function which may cause the wrong results. These metrics can be found in `pd.json`.

### What did you see instead?

Like previous issue: https://github.com/tikv/pd/issues/3561

Another one is the region heartbeat in the test cluster:
<img width="917" alt="Screen Shot 2021-12-22 at 5 10 43 PM" src="https://user-images.githubusercontent.com/35896542/147067238-fcab6474-ea3b-4519-b8af-26222bf19867.png">

### What version of PD are you using (`pd-server -V`)?
master

**Comment by BenMusch** [comment]
Hi! I'm onboarding to TiDB at work and trying to ramp up to PD. I'm happy to take this as a first issue. Let me know if I need to do anything to assign to myself
