### ISSUE TITLE
Setting store limit by label is supported unexpectedly in v4.0

### ISSUE THREAD

**Issue by HunDunDM** [tikv/pd#4507]
### What did you do?

The following code was found on `release-4.0`:

https://github.com/tikv/pd/blob/v4.0.16/server/api/store.go#L503~L515

### What did you expect to see?

`release-4.0` should not support setting store limit by labels.

### What did you see instead?

Some codes related to `labels` are left, although they have no practical effect.

related #2697 #3088

### What version of PD are you using (`pd-server -V`)?

v4.0.16

**Comment by nolouch** [comment]
Should we remove it on 4.0？
