### ISSUE TITLE
An idle PD server can have about 80% CPU utilization

### ISSUE THREAD

**Issue by BusyJay** [tikv/pd#4524]
### What did you do?

1. Deploy a cluster with 1 PD, 1TiKV and 1 TiDB.
2. Load some data.
3. Stop the load and watch.

### What did you expect to see?

PD should be idle and CPU utilization should be near 0.

### What did you see instead?

It seems always busy doing something.

![image](https://user-images.githubusercontent.com/1701473/147668186-86ab22d8-2874-4796-8b27-3f4714a2b88c.png)

### What version of PD are you using (`pd-server -V`)?
v5.3.0

**Comment by rleungx** [comment]
Would you like to do profiling?

**Comment by nolouch** [comment]
Unable to reproduce.

**Comment by BusyJay** [comment]
I can reproduce by `tiup playground --tiflash 0`. In that case, the usage of pd-server keeps around 20% without any workload in v5.4.0.

**Comment by nolouch** [comment]
@BusyJay That's caused by some background check

**Comment by nolouch** [comment]
staled, will reopen if active.
