### ISSUE TITLE
Imbalanced read results in instability of sysbench select_random_ranges/select_random_points performance (-25%~8%)

### ISSUE THREAD

**Issue by Yui-Song** [tikv/pd#4529]
## Bug Report

Imbalanced read results in instability of sysbench select_range_point performance (-25%~8%, compared with the baseline)

### What did you do?

1. Deploy a cluster
2. Turn on prepare plan cache
3. Run sysbench select_range_point

### What did you expect to see?
The TPS of multiple tests are stable.

### What did you see instead?
![origin_img_v2_ccf16cb0-9285-4318-96de-49e648d5a2bg](https://user-images.githubusercontent.com/84501897/147808445-6cba07cc-4be9-41ef-b0dd-77d70e572c7d.png)

TPS：37778
![middle_img_v2_df923f3d-2744-485d-9067-88babb8154bg](https://user-images.githubusercontent.com/84501897/147809246-361fd9ce-0c22-4af5-bc98-aa121ff930d5.png)
![middle_img_v2_8df9678b-bd03-4478-b6f7-1d3fcbbd066g](https://user-images.githubusercontent.com/84501897/147809249-980f26dd-5207-40e6-bee0-1cd9751401be.png)

TPS：54453
![middle_img_v2_19fcb3d1-ae09-4a3e-8faa-98f82e6bba6g](https://user-images.githubusercontent.com/84501897/147809271-d544e101-284c-4181-8c22-062b2550c1a7.png)

![middle_img_v2_5e512be1-6cd5-409f-b25b-80d72710054g](https://user-images.githubusercontent.com/84501897/147809276-a174548b-65e6-4c3f-988e-cab9019fa3ab.png)

### What version of PD are you using (`pd-server -V`)?
commit ae23d409c528a836ae6d98cd174689c38ad19f2d

**Comment by Yui-Song** [comment]
/found/automation

**Comment by nolouch** [comment]
We need some time to fix this issue.

**Comment by lhy1024** [comment]
After the optimization of the 6.3 and 6.4 versions, these two loads have been basically stable.


![img_v2_54681919-32bc-4e8e-80e4-49c34068d5eg](https://user-images.githubusercontent.com/19542290/200756319-23726743-b0b3-4842-b901-7ff3c74233e2.jpg)
In daily run, there will be no 25% drop. 

![image](https://user-images.githubusercontent.com/19542290/200756496-7ad083ac-ab69-4f0a-a6ae-5f949085c0b7.png)

In the comparison test, select_random_ranges (6tidb3tikv), 6.4 vs. 6.3 can increase by 19%, select_random_points (3tidb3tikv) is stable in 6.3, and the performance difference between 6.3 and 6.4 is not big. 

However, it is worth noting that select_random_ranges is affected by the result of splitting region. If there are still regions that are difficult to schedule after the split, the hot-region-scheduler may still not find the optimal result, so theoretically there is room for further improvement.
