### ISSUE TITLE
restful api: unify '_' and '-'

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#4598]
https://github.com/tikv/pd/blob/e2635a60920c71d0f86aa5d12d04cbf154b1907e/server/api/router.go#L228
https://github.com/tikv/pd/blob/e2635a60920c71d0f86aa5d12d04cbf154b1907e/server/api/router.go#L247

there are some '_' in API, whether is it better to replace them with '-'

**Comment by rleungx** [comment]
`query_range` is specified by Prometheus, we cannot use `-` here.
