### ISSUE TITLE
Speed up balance leader

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#4610]
## Development Task
Currently, balance leader only have max ops 100 op/s. we want to increase the speed when a big cluster restart (2M regions).

one way like:  https://github.com/tikv/pd/pull/4008

**Comment by nolouch** [comment]
cc @CabinfeverB, Would you like to take a look? ptal @rleungx

**Comment by CabinfeverB** [comment]
I will take a look

**Comment by CabinfeverB** [comment]
### Describe alternatives you've considered
Add a `Batch` param like #4008 that the scheduler can generate multi operators.

Subtasks
- [ ] #4652
- [ ] add `balance-leader` config handler and improve config
- [ ] support config `balance-leader` in pd-ctl

**Comment by CabinfeverB** [comment]
cc @mayjiang0203
