### ISSUE TITLE
Error logs printed when closing a client

### ISSUE THREAD

**Issue by SandyXSD** [tikv/pd#4629]
## Bug Report

Error logs printed when closing a client.
### What did you do?

Close a client. Code to reproduce:
```
func main() {
	client, _ := tikv.NewTxnClient([]string{"localhost:2379"})
	fmt.Println("Create OK")
	client.Close()
	fmt.Println("Close OK")
}
```
### What did you expect to see?
Client closed gracefully.

### What did you see instead?
Error log:
[ERROR] [client.go:750] ["[pd] fetch pending tso requests error"] [dc-location=global] [error="[PD:client:ErrClientGetTSO]context canceled"] [stack="github.com/tikv/pd/client.(*client).handleDispatcher\n\t/root/go/pkg/mod/github.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/client/client.go:750"]

### What version of PD are you using (`pd-server -V`)?
```
tiup pd -version
Starting component `pd`: /root/.tiup/components/pd/v5.3.0/pd-server -version
Release Version: v5.3.0
Edition: Community
Git Commit Hash: fe6fab9268d2d6fd34cd22edd1cf31a302e8dc5c
Git Branch: heads/refs/tags/v5.3.0
UTC Build Time:  2021-11-16 11:53:58
```

**Comment by pingyu** [comment]
Let me see see.

**Comment by JmPotato** [comment]
Sorry, I didn't notice that you assigned this PR, could you please help review this PR above, I made a fix on this issue? @pingyu

**Comment by pingyu** [comment]
> Sorry, I didn't notice that you assigned this PR, could you please help review this PR above? I made a fix on this issue, thx! @pingyu

Never mind. OK, with pleasure~
(But I'm not a reviewer, and my LGTM do not count :(
