### ISSUE TITLE
Physical timestamp part in TSO is unique in concurrent transactions ?

### ISSUE THREAD

**Issue by noradomi** [tikv/pd#4637]
# Question
Hi,

My project needs to use TSO of each transaction in form of physical timestamp and value must be unique. I know a TSO is monotonically increasing, which includes 2 parts:

- Physical timestamp

- Logical counter

So I gonna extract the physical part in TSO. But I have a concern that in case of two transactions begin at the same time, we will get 2 different TSOs for each transaction, but the physical timestamps in 2 TSOs are guaranteed to be different?

**Comment by noradomi** [comment]
@rleungx can you help me?

**Comment by rleungx** [comment]
Physical timestamps might be the same. We usually use the logical timestamp to distinguish them once two transactions happen at the same time.

**Comment by noradomi** [comment]
@rleungx got it. Thank you so much.
