### ISSUE TITLE
BR restore failed because "unknown method ReportMinResolvedTS for service pdpb.PD\" makes ingest file failed

### ISSUE THREAD

**Issue by Tammyxia** [tikv/pd#4739]
## Bug Report

- BR restore failed cause by  hundreds of "[ERROR] [import.go:428] ["ingest file failed"] ...[error="[BR:KV:ErrKVEpochNotMatch]epoch not match"] "
- TiKV error: [ERROR] [[util.rs:422](http://util.rs:422/)] ["request failed, retry"] [err_code=KV:PD:gRPC] [err="Grpc(RpcFailure(RpcStatus { code: 12-UNIMPLEMENTED, message: \"unknown method ReportMinResolvedTS for service pdpb.PD\", details: [] }))"]
- It seems ReportMinResolvedTS  PR has not merged: https://github.com/tikv/pd/pull/4716, this issue makes nightly version cannot be used by BR restore or CDC replication.

### What version of PD are you using (`pd-server -V`)?
PD
Release Version: v6.0.0-nightly
Edition: Community
Git Commit Hash: 5154c0bb55abcb8dcfc5a4776323d820fa324967
Git Branch: heads/refs/tags/v6.0.0-nightly
UTC Build Time:  2022-03-15 02:04:06

TiKV 
Release Version:   6.0.0-alpha
Edition:           Community
Git Commit Hash:   b358f668752a406cfcbe4dfd8b91599b9d920bea
Git Commit Branch: heads/refs/tags/v6.0.0-nightly
UTC Build Time:    2022-03-15 18:12:20
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features:   jemalloc mem-profiling portable sse test-engines-rocksdb cloud-aws cloud-gcp cloud-azure
Profile:           dist_release

**Comment by nolouch** [comment]
close by https://github.com/tikv/pd/pull/4716.
