### ISSUE TITLE
Dr-autosync: After recover backup dc, hit error 9005: unavailable region when query one table

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/pd#4752]
### What did you do?
1、Configure a cluster run at dr-auto-sync mode;
2、Down backup dc，run bank workload;
3、Start up backup dc, util replication mode change to sync_recover
4、Down primary dc，recover the cluster from backup dc;
5、Run bank workload again 

### What did you expect to see?
bank account maybe not equal to the original value.

### What did you see instead?

MySQL [bank]> select count(*) from bank2_transaction;
ERROR 9005 (HY000): Region is unavailable

### What version of PD are you using (`pd-server -V`)?
MySQL [(none)]> select type, max(version), max(git_hash) from information_schema.cluster_info group by type;
+------+--------------+------------------------------------------+
| type | max(version) | max(git_hash)                            |
+------+--------------+------------------------------------------+
| pd   | 6.0.0-alpha  | d56b195b72dc006b5232a92d45743480b7460a1c |
| tikv | 6.0.0-alpha  | e1fae9469b33ff1ec4fd66aa143a21a5f30f5aa3 |
| tidb | 6.0.0-alpha  | 9fcc6b090b02c8351aba4ee8a7f072e0e0c840e0 |
+------+--------------+------------------------------------------+
3 rows in set (0.01 sec)

**Comment by disksing** [comment]
The reason is that some region has splitted during the `async` state. After the connection has recovered, the regions start to sync to DR center. When part of the regions are synced, there will be some _holes_ (ranges with no data) in the tikv storage. So if Primary center fails again, we cannot recover full data from DR nodes.

**Comment by nolouch** [comment]
So, it's by design? cc @disksing

**Comment by disksing** [comment]
Not by design. It is a design flaw. We need to forbid region split in `async` state to overcome this issue.
