### ISSUE TITLE
PD scheduler can not recover after lightning abnormally exit

### ISSUE THREAD

**Issue by matchge-ca** [tikv/pd#4768]
### What did you do?

1. Import using lightning with local backend
2. Kill lightning while it is running or wait till lightning exited with error status (i.e, checksum failed)

### What did you expect to see?
PD schedulers are resumed after 5 minutes

### What did you see instead?
PD schedulers is remaining paused even after 5 mins(TTL should expired) 

### What version of PD are you using (`pd-server -V`)?
5.3.0

**Comment by JmPotato** [comment]
Duplicated with https://github.com/pingcap/tidb/issues/33546. I will close this one.
