### ISSUE TITLE
Metadata should be isolated from other region by default

### ISSUE THREAD

**Issue by CharlesCheung96** [tikv/pd#4772]
### Describe your feature request related problem
Ref: https://github.com/pingcap/tiflow/issues/4756

**Comment by JmPotato** [comment]
As @disksing mentioned in https://github.com/tikv/pd/pull/4774#issuecomment-1083014935, PD should work independently from TiDB as a part of TiKV. So it should not involve any TiDB- or SQL-specified terms like the metadata of TiDB. A proper way to do this is to use features like Region Label to set it from the TiDB side.

**Comment by CharlesCheung96** [comment]
@JmPotato Thank you for your suggestion, we will implement this requirement through Region Label.
