### ISSUE TITLE
No balance operator even one disk is full  

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/pd#4805]
### What did you do?
1、config 5 tikvs, 3 tikv has 1.5T capacity and the others has 500G.
2、Continue inject data  until one tikv is full.
  

### What did you see instead?

![image](https://user-images.githubusercontent.com/9443637/163311489-ab021c99-527a-4bb9-a087-5db77c1dca63.png)

![image](https://user-images.githubusercontent.com/9443637/163311743-5fc24d65-ff0e-41ac-9ea4-040d4722381c.png)

### What version of PD are you using (`pd-server -V`)?
/ # /pd-server -V
Release Version: v6.0.0
Edition: Community
Git Commit Hash: 71f35735d7f9ff7bfa8057fbd67a039c9ea8cf75
Git Branch: heads/refs/tags/v6.0.0
UTC Build Time:  2022-03-31 11:58:41

**Comment by nolouch** [comment]
@mayjiang0203 Does https://github.com/tikv/pd/pull/4837 verified?

**Comment by mayjiang0203** [comment]
Yes， has been verified.
