### ISSUE TITLE
server/cluster/cluster.go: share the lock with all attribbutes for running is expensive

### ISSUE THREAD

**Issue by AndreMouche** [tikv/pd#4823]
## Enhancement Task
The attribute `running ` shares the lock with other attributes in the `RaftCluster`, which is expensive, could we use `atomic.StoreInt64` instead similar with `Server.isServing`
[https://github.com/tikv/pd/blob/56a015c32925022cda9c803830c058916ca02d38/server/cluster/cluster.go#L405-L408](https://github.com/tikv/pd/blob/56a015c32925022cda9c803830c058916ca02d38/server/cluster/cluster.go#L405-L408)

ref `Server.IsClosed` [https://github.com/tikv/pd/blob/56a015c32925022cda9c803830c058916ca02d38/server/server.go#L494-L496](https://github.com/tikv/pd/blob/56a015c32925022cda9c803830c058916ca02d38/server/server.go#L494-L496)

**Comment by aidendou** [comment]
hey @AndreMouche, I am onboarding TiDB at work, I can take this as the first issue. I assume we'll just need to change `running` from boolean to int64 and use atomic pkg for IsRunning() and maybe Context()?

**Comment by e11jah** [comment]
Hi, I'd like to work on this issue :)
