### ISSUE TITLE
Must use prefix when update config with TTL

### ISSUE THREAD

**Issue by CabinfeverB** [tikv/pd#4861]
### What did you do?
>>curl -X POST -d '{"max-snapshot-count":30}' "127.0.0.1:2379/pd/api/v1/config?ttlSecond=1"

### What did you expect to see?
update successfully

### What did you see instead?
error "unsupported ttl config max-snapshot-count"

And
>> curl -X POST -d '{"schedule.max-snapshot-count":30}' "127.0.0.1:2379/pd/api/v1/config?ttlSecond=1" 

 success

### What version of PD are you using (`pd-server -V`)?
master

**Comment by rleungx** [comment]
I think It's an expected behavior.
