### ISSUE TITLE
sever/encryptionkm/key_manager: should we select `ctx.Done()` in the `keyWatchLoop`

### ISSUE THREAD

**Issue by AndreMouche** [tikv/pd#4876]
## Enhancement Task

It seems we need to select `ctx.Done()` in the `keyWatchLoop`?
[https://github.com/tikv/pd/blob/e71664f2aec9a64e737a42de9aff0cc57bcff292/server/encryptionkm/key_manager.go#L226-L258](https://github.com/tikv/pd/blob/e71664f2aec9a64e737a42de9aff0cc57bcff292/server/encryptionkm/key_manager.go#L226-L258)

cc @HunDunDM

**Comment by HunDunDM** [comment]
When `ctx` done, a `resp` of type `Canceled` is generated.
