### ISSUE TITLE
[Dynamic Region]tikv can not rolling update due one leader transfer very slowly

### ISSUE THREAD

**Issue by Lily2025** [tikv/pd#4880]
### What did you do?
update some config with rolling restart
            region-max-keys = 144000000000
            region-max-size = "1.3GB"
            region-split-keys = 96000000000
            region-split-size = "1GB"

### What did you expect to see?
tikv can restart quickly when rolling update

### What did you see instead?
a new test resule：after one hours later，the leader of tikv still can not transfer successfully
![image](https://user-images.githubusercontent.com/84712107/167830187-715e59e6-deeb-4081-ae75-4b2a6dddbf1a.png)

another test：
one tikv takes 20min to restart when rolling update due one leader transfer very slowly
![OFrIpPxOxE](https://user-images.githubusercontent.com/84712107/165917024-ed9783ea-3bf4-4fb2-b9d4-5a67656c856b.png)

### What version of PD are you using (`pd-server -V`)?
./tikv-server -V
TiKV
Release Version: 6.0.0-alpha
Edition: Community
Git Commit Hash: https://github.com/tikv/tikv/commit/95c4d0ed36369c254b1bee36eb007004ee834948
Git Commit Branch: heads/refs/tags/v6.1.0-nightly
UTC Build Time: 2022-04-21 10:58:55
Rust Version: rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features: jemalloc mem-profiling portable sse test-engines-rocksdb cloud-aws cloud-gcp cloud-azure
Profile: dist_release
2022-04-24T10:07:55.070+0800 INFO k8s/client.go:107 it should be noted that a long-running command will not be interrupted even the use case has ended. For more information, please refer to https://github.com/pingcap/test-infra/discussions/129
./pd-server -V
Release Version: v6.1.0-alpha-40-g1d8eba0
Edition: Community
Git Commit Hash: 1d8eba08d9907ef1a6fdebd1ebf6b218b9338d91
Git Branch: feature/region_monitor
UTC Build Time: 2022-04-22 12:21:42
2022-04-24T10:07:55.245+0800 INFO k8s/client.go:107 it should be noted that a long-running command will not be interrupted even the use case has ended. For more information, please refer to https://github.com/pingcap/test-infra/discussions/129
./tidb-server -V
Release Version: v6.1.0-nightly
Edition: Community
Git Commit Hash: 571d97bb16f6f69fcbcf74648380da3c2e80a3fb
Git Branch: heads/refs/tags/v6.1.0-nightly
UTC Build Time: 2022-04-20 23:02:41
GoVersion: go1.18
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
2022-04-24T10:07:55.385+0800 INFO k8s/client.go:107 it should be noted that a long-running command will not be interrupted even the use case has ended. For more information, please refer to https://github.com/pingcap/test-infra/discussions/129

**Comment by Lily2025** [comment]
from bufferflies：
The main reason for the slow restart of tikv0: Before the rolling restart of the cluster, there is a remaining region on store 5 that is being scheduled by the balance region, so that the evict leader cannot take effect for the normally scheduled region, and the scheduling is completed after 20 minutes.

**Comment by Lily2025** [comment]
another test result：
![image](https://user-images.githubusercontent.com/84712107/167828651-cf4c8a16-8387-426f-a9da-d14b6bfbc2e6.png)

**Comment by bufferflies** [comment]
In this test，some executing operator is too slow and their scheduled region is too big more than 5g, the scene small probability . If some region can not be evict leader， it can transfer pd leader，remove this operators.

**Comment by bufferflies** [comment]
relate： https://github.com/tikv/tikv/issues/12597

**Comment by nolouch** [comment]
staled.
