### ISSUE TITLE
v5.4.1: pd panic after inject 252ms io delay to pd leader

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/pd#4886]
### What did you do?
tcms testcase: oltp_pd_rel_leader_io_delay
tcms testplan: plan/784916

### What did you expect to see?
No panic.

### What did you see instead?
pd panic.

### What version of PD are you using (`pd-server -V`)?
2022-05-04T07:09:34.881+0800    INFO    k8s/client.go:107       it should be noted that a long-running command will not be interrupted even the use case has ended. For more informat
ion, please refer to https://github.com/pingcap/test-infra/discussions/129
./pd-server -V
 Release Version: v5.4.1
Edition: Community
Git Commit Hash: 18098e99e2eacc0b327710742516910dc75059a4
Git Branch: heads/refs/tags/v5.4.1
UTC Build Time:  2022-04-29 01:18:56

**Comment by bufferflies** [comment]
related issue: https://github.com/etcd-io/etcd/issues/13406

**Comment by bufferflies** [comment]
panic log:
![DcGako9AHg](https://user-images.githubusercontent.com/23159587/167242197-bc20d356-ff81-42ee-9b0f-7b101a204f03.jpg)

**Comment by bufferflies** [comment]
won't fix
