### ISSUE TITLE
Fail to add evict-leader

### ISSUE THREAD

**Issue by CabinfeverB** [tikv/pd#4911]
### Which jobs are failing
schedulerTestSuite.TestScheduler
https://github.com/tikv/pd/runs/6345603511?check_suite_focus=true

### CI link
https://github.com/tikv/pd/runs/6345603511?check_suite_focus=true

### Reason for failure (if possible)
The scheduler deletion action is performed asynchronously. In this test, the scheduler will be added before it is completely deleted, resulting in the addition failure.

**Comment by rleungx** [comment]
Is it fixed now?

**Comment by CabinfeverB** [comment]
fixed https://github.com/tikv/pd/pull/5723 and https://github.com/tikv/pd/pull/5793
