### ISSUE TITLE
PD CPU 100% on an idle cluster

### ISSUE THREAD

**Issue by tiancaiamao** [tikv/pd#4920]
### What did you do?

Start a playground cluster, load some data:

```
tiup playground --tiflash 0
tiup br restore full -s 's3://bank/shema-full?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http://minio.pingcap.net:9000&force-path-style=true/' -u 'http://127.0.0.1:2379/'
```

Then the cluster is idle, but I find PD CPU is nearly 100%

### What did you expect to see?

PD CPU usage should be low.

### What did you see instead?

Note the CPU usage below:

![image](https://user-images.githubusercontent.com/1420062/167758262-e25bc773-930f-4739-9e2d-ceb4a3e1f965.png)
![image](https://user-images.githubusercontent.com/1420062/167758804-5081ce37-e435-4759-8f7c-a7b622284398.png)

Profile shows the CPU is used in the `patolRegions` function

![image](https://user-images.githubusercontent.com/1420062/167758844-ff118e02-9946-483c-a51c-8faa334f5ea7.png)

I believe it's caused by this loop:

https://github.com/tikv/pd/blob/d20eacc1212a558cde18ebc0d873236dee46d1fc/server/cluster/coordinator.go#L112-L130

Maybe **the actual work takes more time then the ticker interval**, so it repeat the execution endlessly... and cost 100% CPU

### What version of PD are you using (`pd-server -V`)?

6.0.0

**Comment by tiancaiamao** [comment]
@nolouch

**Comment by rleungx** [comment]
Due to the replica being 3 and there is only 1 TiKV,  PD tries to add replicas repeatedly. Here is the test result with 3 TiKV:
![Screen Shot 2022-05-16 at 11 26 39 AM](https://user-images.githubusercontent.com/35896542/168515037-2410e121-8839-4d30-8b65-4e774d109693.png)

But we need to consider this case and use a backoff mechanism when it cannot create an operator.

**Comment by mayjiang0203** [comment]
Through it is a corner case, but the affect is severe, so mark it Major.
/severity Major
