### ISSUE TITLE
[Dynamic Region] Some regions that are greater than expected for a long time

### ISSUE THREAD

**Issue by Lily2025** [tikv/pd#4979]
### What did you do?
modify config repeatedly
![2aox2hWk9g](https://user-images.githubusercontent.com/84712107/168973711-2c37fe75-0354-4cdf-b6a0-7cf2a407aba7.png)
![image](https://user-images.githubusercontent.com/84712107/168973916-cce8c6ff-9747-484a-80df-7bce13caff33.png)

current config：
    "coprocessor": {
        "split-region-on-table": false,
        "batch-split-limit": 10,
        "region-max-size": "400MiB",
        "region-split-size": "256MiB",
        "region-max-keys": 36000000000,
        "region-split-keys": 24000000000,
        "consistency-check-method": "mvcc",
        "enable-region-bucket": true,
        "region-bucket-size": "128MiB",
        "region-size-threshold-for-approximate": "512MiB",
        "region-bucket-merge-size-ratio": 0.33
    },

### What did you expect to see?
regions can split normally

### What did you see instead?
Some regions that are greater than expected for a long time
![image](https://user-images.githubusercontent.com/84712107/168973408-d97fdbe4-d4a0-4e81-919f-a6ebc99efd10.png)
![middle_img_v2_136be586-860d-48a3-b544-7b681c87671g](https://user-images.githubusercontent.com/84712107/169490049-9f59a4af-b062-4e58-a185-721bd5e97b02.jpg)
date: 05/17~05/18

### What version of PD are you using (`pd-server -V`)?
./tikv-server -V
TiKV
Release Version: 6.1.0-alpha
Edition: Community
Git Commit Hash: 744d688512744c7a6898d96c4f247c1dc26680b2
Git Commit Branch: heads/refs/tags/v6.1.0-nightly
UTC Build Time: 2022-05-14 10:57:47
Rust Version: rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features: jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile: dist_release
2022-05-16T19:25:14.031+0800 INFO k8s/client.go:107 it should be noted that a long-running command will not be interrupted even the use case has ended. For more information, please refer to https://github.com/pingcap/test-infra/discussions/129
./pd-server -V
Release Version: v6.1.0-nightly
Edition: Community
Git Commit Hash: https://github.com/tikv/pd/commit/656f50d4578c50e8aa658459cc866a68c12ba6c2
Git Branch: heads/refs/tags/v6.1.0-nightly
UTC Build Time: 2022-05-13 10:56:22
2022-05-16T19:25:14.189+0800 INFO k8s/client.go:107 it should be noted that a long-running command will not be interrupted even the use case has ended. For more information, please refer to https://github.com/pingcap/test-infra/discussions/129
./tidb-server -V
Release Version: v6.1.0-nightly
Edition: Community
Git Commit Hash: 32258fdaeca50ed29110760a87b6b3563c24e1d7
Git Branch: heads/refs/tags/v6.1.0-nightly
UTC Build Time: 2022-05-15 23:01:17
GoVersion: go1.18
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by bufferflies** [comment]
![origin_img_v2_23551151-a6c3-4228-9f94-07bd85fc45eg](https://user-images.githubusercontent.com/23159587/170024187-3c14e1b1-a494-440d-9cd5-e46ca3a507ad.png)

**Comment by nolouch** [comment]
repeat with https://github.com/tikv/tikv/issues/12597
