### ISSUE TITLE
server/grpc_service: RegionHeartbeat will panic when the leader in request is nil 

### ISSUE THREAD

**Issue by AndreMouche** [tikv/pd#5011]
## Bug Report
We do `request.GetLeader().GetStoreId()` before check if the leader is nil  `if region.GetLeader() == nil` when we process the request `RegionHeartbeat`, with the leader is nil the request will panic when try `request.GetLeader().GetStoreId()`
[https://github.com/tikv/pd/blob/9f10a5185b81cd270f5c920b3fd6ec655fa8ebd1/server/grpc_service.go#L858-L879](https://github.com/tikv/pd/blob/9f10a5185b81cd270f5c920b3fd6ec655fa8ebd1/server/grpc_service.go#L858-L879)

**Comment by mayjiang0203** [comment]
Seems it is not a bug, mark it minor.
/severity Minor
