### ISSUE TITLE
server/grpc_service: new AskSplitRequest could be removed

### ISSUE THREAD

**Issue by AndreMouche** [tikv/pd#5014]
## Enhancement Task
It seems we do not need to create a new `AskSplit` in the function `AskSplitRegion`, use request directly instead.
[https://github.com/tikv/pd/blob/9f10a5185b81cd270f5c920b3fd6ec655fa8ebd1/server/grpc_service.go#L1066-L1072](https://github.com/tikv/pd/blob/9f10a5185b81cd270f5c920b3fd6ec655fa8ebd1/server/grpc_service.go#L1066-L1072)

**Comment by AndreMouche** [comment]
Meanwhile, similar logic in AskBatchSplit
[https://github.com/tikv/pd/blob/9f10a5185b81cd270f5c920b3fd6ec655fa8ebd1/server/grpc_service.go#L1111-L1115](https://github.com/tikv/pd/blob/9f10a5185b81cd270f5c920b3fd6ec655fa8ebd1/server/grpc_service.go#L1111-L1115)

**Comment by qingfeng777** [comment]
Did you mean like this?
```
	split, err := rc.HandleAskBatchSplit(&pdpb.AskBatchSplitRequest{
		Region:     request.Region,
		SplitCount: request.SplitCount,
	})
```
