### ISSUE TITLE
Allow to specify leader-schedule-policy in the config

### ISSUE THREAD

**Issue by Tema** [tikv/pd#5016]
## Enhancement Task

We use `leader-schedule-policy:count` by setting it through https://docs.pingcap.com/tidb/v4.0/pd-control.

We would like to be able to set it at PD configuration time, but it is not available there: https://docs.pingcap.com/tidb/dev/pd-configuration-file

**Comment by rleungx** [comment]
The configuration file only works at the first-time start. Once the cluster is started, the scheduling configuration will be stored in etcd, we can only use pd-ctl/HTTP API to change them.

**Comment by rleungx** [comment]
> > The configuration file only works at the first-time start.
> 
> I understand that and it is exactly what I need. However, https://docs.pingcap.com/tidb/dev/pd-configuration-file simply doesn't have a way to specify `leader-schedule-policy:count `.

Actually, you can add it into your toml:
```
"leader-schedule-policy": "size",
```

**Comment by Tema** [comment]
> Actually, you can add it into your toml:

So it is just a documentation gap, as https://docs.pingcap.com/tidb/dev/pd-configuration-file  does not have it?

**Comment by rleungx** [comment]
> > Actually, you can add it into your toml:
> 
> So it is just a documentation gap, as https://docs.pingcap.com/tidb/dev/pd-configuration-file does not have it?

Yes
