### ISSUE TITLE
server/grpc_service: could we make the lock for the func `UpdateServiceGCSafepoint` smaller? 

### ISSUE THREAD

**Issue by AndreMouche** [tikv/pd#5019]
## Bug Report
It seems the function `UpdateServiceGCSafepoint` should only save a safepoint bigger than the `minServiceGCSafepoint`, So that we can make sure that the `minServiceGCSafepoint` is always increasing. However, there exist corner case that it may store a safepoint smaller than the minServiceGCSafepoint.
[https://github.com/tikv/pd/blob/efb4c9f687620afd0654296bfcd932515fce5a46/server/grpc_service.go#L1395-L1430](https://github.com/tikv/pd/blob/efb4c9f687620afd0654296bfcd932515fce5a46/server/grpc_service.go#L1395-L1430)

### What did you do?
Here is the case we may store a safepoint smaller than the minServiceGCSafepoint.
assume that there is only one service safepoint in PD:(cdc,safepoint=5)
1.  br-client: got min=(cdc,safepoint=5) from `LoadMinServiceGCSafePoint`.
2.  cdc-client: got min=(cdc,safepoint=5) from `LoadMinServiceGCSafePoint`.
3.  cdc-client: set (cdc,safepoint=10) with `SaveServiceGCSafePoint` should success since  the safepoint 10 > min.safepoint 5
4. cdc-client: get min = (cdc,safepoint=10) success from `LoadMinServiceGCSafePoint` and returns to the client.
5.  br-client: set (br,safepoint=7) success since the safepoint 7 > min.safepoint 5(got from step1)
6.  br-client: get min = (br,safepoint=7) success from `LoadMinServiceGCSafePoint` and returns to the client.

### What did you expect to see?
step 5 shouldn't happen and br-client should got response  `min = (cdc,safepoint=10)`

### What did you see instead?
step 5-6 happens.
### What version of PD are you using (`pd-server -V`)?
master

**Comment by mayjiang0203** [comment]
It may cause GCSafePoint go back from client side.
/severity Major

**Comment by AndreMouche** [comment]
This issue won't happen while we already have a big lock [https://github.com/tikv/pd/blob/efb4c9f687620afd0654296bfcd932515fce5a46/server/grpc_service.go#L1368-L1369](https://github.com/tikv/pd/blob/efb4c9f687620afd0654296bfcd932515fce5a46/server/grpc_service.go#L1368-L1369)
However, we can also do something to make the lock smaller, such as move it into sub functions.
