### ISSUE TITLE
Offline left time and scale speed will jump in 10m after change pd leader

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/pd#5025]
### What did you do?

Down pd leader during scale out.

### What did you expect to see?
Left time and speed should be  stable and reaction actual situation.

### What did you see instead?
![image](https://user-images.githubusercontent.com/9443637/170177101-3be9b61e-62be-4817-99f3-211b1b90de3f.png)

![image](https://user-images.githubusercontent.com/9443637/170177648-4a17e2b8-a286-485d-a89c-1f073d0406c3.png)

### What version of PD are you using (`pd-server -V`)?
./pd-server -V
 Release Version: v6.1.0-nightly
Edition: Community
Git Commit Hash: b3eeaae3ea3d0e058d7363e134a8c84737f4798f
Git Branch: heads/refs/tags/v6.1.0-nightly
UTC Build Time:  2022-05-24 06:13:20

**Comment by mayjiang0203** [comment]
Since there is chaos inject during the test, and the speed or left time will come back to normal after change leader 10m later, mark it moderate.
/severity moderate
/assign @rleungx

**Comment by rleungx** [comment]
The offline progress has the same problem.
