### ISSUE TITLE
[Dynamic Region]The configuration obtained by PD is inconsistent with TIKV

### ISSUE THREAD

**Issue by Lily2025** [tikv/pd#5072]
### What did you do?
![image](https://user-images.githubusercontent.com/84712107/171086682-5dbb5deb-e3a8-41fe-8cda-fa44368392c0.png)
modify tikv region split config by rolling update

### What did you expect to see?
The configuration obtained by PD is consistent with TIKV

### What did you see instead?
The configuration obtained by PD is inconsistent with TIKV
![middle_img_v2_c4ab23ae-e99d-4875-8880-f48df8c80f7g](https://user-images.githubusercontent.com/84712107/171083347-e1c47a05-0620-4381-a150-d49433778430.png)
![middle_img_v2_97dd6fca-b0f4-458e-8e02-6a8f493e74fg](https://user-images.githubusercontent.com/84712107/171083355-109cf308-32cd-442c-bff5-fd57f8f25cad.png)

### What version of PD are you using (`pd-server -V`)?
2022-05-30T23:57:46.897+0800	INFO	k8s/client.go:107	it should be noted that a long-running command will not be interrupted even the use case has ended. For more information, please refer to https://github.com/pingcap/test-infra/discussions/129
./pd-server -V
 Release Version: v6.1.0
Edition: Community
Git Commit Hash: 426e8c31c721c4822914f5d1ff2c988eedd2d7a9
Git Branch: heads/refs/tags/v6.1.0
UTC Build Time:  2022-05-30 10:04:19

**Comment by bufferflies** [comment]
ref: https://github.com/tikv/pd/pull/5074

**Comment by bufferflies** [comment]
fix at #5074
