### ISSUE TITLE
[Online Recovery] Unsafe online recovery failed with info “"triggered by error: Exceeds timeout 2022-06-01 05:28:31.116444297 +0000 UTC m=+3515.090953498"”

### ISSUE THREAD

**Issue by Lily2025** [tikv/pd#5085]
### What did you do?
1、down two tikv
2、execute online unsafe recovery

### What did you expect to see?
Unsafe recovery success

### What did you see instead?
    }
  },
  {
    "info": "Unsafe recovery enters exit force leader stage",
    "time": "2022-06-01 05:28:31.645",
    "details": [
      "triggered by error: Exceeds timeout 2022-06-01 05:28:31.116444297 +0000 UTC m=+3515.090953498"
    ]
  },
  {
    "info": "Collecting reports from alive stores(0/3)",
    "time": "2022-06-01 05:28:31.645",
    "details": [
      "Stores that have not dispatched plan: 5, 6, 7",
      "Stores that have reported to PD: ",
      "Stores that have not reported to PD: "
    ]
  }
]

### What version of PD are you using (`pd-server -V`)?
./tikv-server -V
 TiKV 
Release Version:   6.1.0-alpha
Edition:           Community
Git Commit Hash:   6a67b08d7fc6fa0623009e5bcb756333c2a655af
Git Commit Branch: heads/refs/tags/v6.1.0-nightly
UTC Build Time:    2022-05-31 18:12:07
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
./pd-server -V
 Release Version: v6.1.0-nightly
Edition: Community
Git Commit Hash: 52dd58715804faa5e6ee88bf11183b61b5273570
Git Branch: heads/refs/tags/v6.1.0-nightly
UTC Build Time:  2022-05-31 06:11:58

**Comment by Connor1996** [comment]
The log shows force leader stage retried again and again
![fC0Tg4KPzg](https://user-images.githubusercontent.com/13497871/171373938-3f015162-d143-42da-9da9-bbe9308ffae4.png)
