### ISSUE TITLE
If a store is evicted leader, can't make other store offline on single-replica cluster

### ISSUE THREAD

**Issue by CabinfeverB** [tikv/pd#5129]
### What did you do?
There is a single-replica cluster that has 5 TiKVs. Add evict-leader scheduler for store A and make store B offline.

### What did you expect to see?
Store B can be offline usually.

### What did you see instead?
Store B can not be offline. There is no operator created.

### What version of PD are you using (`pd-server -V`)?
v6.1.0-alpha-24-g3320891

**Comment by AndreMouche** [comment]
I think `evict-leader` scheduler shouldn't exist for a single-replica cluster.

**Comment by rleungx** [comment]
I did some tests on the nightly branch:
1. add evict leader for store 1
2. delete store 4

<img width="921" alt="Screenshot 2023-07-17 at 15 10 40" src="https://github.com/tikv/pd/assets/35896542/94e64bec-36ff-404a-a6bb-352b9ea3ac77">
<img width="919" alt="Screenshot 2023-07-17 at 15 10 46" src="https://github.com/tikv/pd/assets/35896542/c4bb410b-2f8f-4f74-8d01-ce87544e1048">

store 4 can be offline successfully.

**Comment by CabinfeverB** [comment]
Let me fill in the details. There is a single-replica cluster that has 4 TiKVs. `location-labels` is `zone`, and `isolation-level` is `zone`. the label of store 1 is `zone=z2`, the label of store 2 is `zone=z2`, the label if store 3 if `zone=z1`, and the label of store 4 is `zone=z1`. Add evict-leader scheduler for store 1 and make store 2 offline.
![image](https://github.com/tikv/pd/assets/23399268/4289de77-8216-438a-b19d-a1d5dce5b3e6)
![image](https://github.com/tikv/pd/assets/23399268/4df44604-5c64-48e0-89fe-490991d6d8d3)
![image](https://github.com/tikv/pd/assets/23399268/75cd4c23-31db-49ba-ba78-04d82ad13329)

**Comment by rleungx** [comment]
I tested it again, seems it can offline successfully now. I'm going to close this issue.
