### ISSUE TITLE
scheduler/filter: could we define the reason when needed to improve GC

### ISSUE THREAD

**Issue by AndreMouche** [tikv/pd#5150]
## Enhancement Task
In the `StoreStateFilter`, we need to check the condition and record the failed reason when failed, However, we always record the reason before we check the condition, since we will stop once we meet false so the final reason should be right, while it may case GC problem if we update the `reason` in every condition-check function.
[https://github.com/tikv/pd/blob/c8775b6176a03eb25cb1622fc46ba1d496872df7/server/schedule/filter/filters.go#L297-L310](https://github.com/tikv/pd/blob/c8775b6176a03eb25cb1622fc46ba1d496872df7/server/schedule/filter/filters.go#L297-L310)

**Comment by xueshanfeishu** [comment]
Hi, I'd like to work on this issue :)
