### ISSUE TITLE
The error returned by PD gRPC service is not expected

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#5161]
## Bug Report

See https://github.com/tikv/pd/blob/d263b8586123387d219bdccf9a1733632ab0d9c2/server/grpc_service.go#L470

We should put the error into the header instead of directly returning a gRPC error.

### What version of PD are you using (`pd-server -V`)?
master

**Comment by Connor1996** [comment]
@mayjiang0203 Should we level it up to major, it may cause pd client of TiKV to reconnect again and again which greatly affects the performance

**Comment by nolouch** [comment]
ref https://github.com/pingcap/tiflash/issues/7408
