### ISSUE TITLE
server/schedulers: potential data race in the function of clone for XXXScheduler.config 

### ISSUE THREAD

**Issue by AndreMouche** [tikv/pd#5170]
## Bug Report

It may cause data race since it do not deeply clone the slice  in the function `Clone` for some config, there are more than 1 issues:
- 

### grantHotRegionSchedulerConfig

[https://github.com/tikv/pd/blob/c8775b6176a03eb25cb1622fc46ba1d496872df7/server/schedulers/grant_hot_region.go#L123-L129](https://github.com/tikv/pd/blob/c8775b6176a03eb25cb1622fc46ba1d496872df7/server/schedulers/grant_hot_region.go#L123-L129)

related test case
```
func TestGrantHotRegionSchedulerConfig(t *testing.T) {
	re := require.New(t)
	conf := &grantHotRegionSchedulerConfig{
		StoreIDs:      []uint64{1, 2, 3, 4, 5},
		StoreLeaderID: 1,
	}
	conf2 := conf.Clone()
	re.Equal(conf, conf2)
	conf2.StoreIDs[0] = 7
	re.Equal(uint64(7), conf2.StoreIDs[0])
	re.NotEqual(uint64(7), conf.StoreIDs[0])
}
```
 

### grantleader

[https://github.com/tikv/pd/blob/c8775b6176a03eb25cb1622fc46ba1d496872df7/server/schedulers/grant_leader.go#L102-L107](https://github.com/tikv/pd/blob/c8775b6176a03eb25cb1622fc46ba1d496872df7/server/schedulers/grant_leader.go#L102-L107)

Please fix it one by one

- [ ] grantleader
- [ ] grantHotRegionSchedulerConfig

Other similar case https://github.com/tikv/pd/issues/5156

**Comment by rleungx** [comment]
Can we close it now? @LLThomas

**Comment by LLThomas** [comment]
> Can we close it now? @LLThomas

@rleungx Yes, I didn't find a similar error like this.
