### ISSUE TITLE
Identify regions of unknown size as empty-region and undersized-region.

### ISSUE THREAD

**Issue by HunDunDM** [tikv/pd#5273]
### What did you do?

Restart TiKV.

### What did you expect to see?

TiKV needs to re-count the region-size information. During this period, the reported `approximate-size` and `approximate-keys` are 0, and they should not be counted as empty-region and undersized-region.

This is just a monitoring issue, PD will not merge these regions.

### What did you see instead?

<img width="704" alt="image" src="https://user-images.githubusercontent.com/19789302/177482843-7a04c54d-55d1-43eb-896a-6525b32536dd.png">

### What version of PD are you using (`pd-server -V`)?

[master](https://github.com/tikv/pd/commit/3abc703fa00cef164cd75426c7590d59bd0649c1)

**Comment by rleungx** [comment]
Does https://github.com/tikv/pd/pull/7009 also solve it? @CabinfeverB

**Comment by CabinfeverB** [comment]
solved by #7009
