### ISSUE TITLE
Cannot failover well after recover pd from `pd-recover` and one tikv has gone

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#5279]
### What did you do?

one TiKV and all PDs has gone, I do recovery. 

I use `pd-recovery` to recreate the PD cluster, and all existing TiKVs reconnect to PD.  and then I scale a new TiKV. 

### What did you expect to see?

I want to see PD can fix all unhealthy peers, which means scheduling to move peers from missing TiKV to the new TiKV.

### What did you see instead?
**Note**: Due to PD is recreated, so PD no any information about the missing  TiKV. this is the main reason about the follow behavior.

I can see there actually do some scheduling operator:
![image](https://user-images.githubusercontent.com/6428910/177523608-3fd7032a-82b3-47bc-9fd0-99904e1b0f44.png)

Here exist main two kinds of operators:
- `add-rule-peers`:  caused by the rule fit, the peer in the missing store is not fit. so PD think the region's peer count not meet the requirement.
- `remove-orphan-peer`: caused by the rule fit. because the peer in the missing store is not fit, so the peer is an `orphan peer`. PD will remove after the peer count of the region meets the requirement. 

If the operator succeeds, it will satisfy our expectations. but all the `remove-orphan-peer` operator is timeout:
![image](https://user-images.githubusercontent.com/6428910/177525058-a48f203f-2f1b-4a38-ae98-b335b675651f.png)

 After I check the log. I can see the operator command cannot send to TiKV:

![image](https://user-images.githubusercontent.com/6428910/177525473-37ff5767-9dd7-4172-9ef7-19daf0a80eb9.png)

### What version of PD are you using (`pd-server -V`)?
master

**Comment by nolouch** [comment]
cc @LLThomas  would you like have a try to fix it.

**Comment by LLThomas** [comment]
> cc @LLThomas would you like have a try to fix it.

Ok, I'll try it.
