### ISSUE TITLE
implement keyspace management

### ISSUE THREAD

**Issue by AmoebaProtozoa** [tikv/pd#5293]
## Development Task

In order to let multiple keyspaces share the same PD cluster, PD needs to provide storage and ways to manage keyspace metadata. 

Feature request: tikv/tikv#12998
Parent Issue: tikv/tikv#12999

## Task List

- [x] #5294 
- [x] pingcap/kvproto#952
- [x] #5265
- [x] #5291
- [x] #5297 
- [x] #5347 
- Refactor keyspace manager using RunInTxn & Tombstone Keyspace 
    - [x] https://github.com/pingcap/kvproto/pull/1033
    - [x] #5843 
- [x] #5844 
- [x] #5869 
- [x] #5313

**Comment by rleungx** [comment]
Close it since it has been finished
