### ISSUE TITLE
Auto gc the tombstone store

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#5348]
## Development Task
![image](https://user-images.githubusercontent.com/6428910/180697466-6cb2f13a-7203-4b26-8b62-0665e0c6e38b.png)

In a long-running cluster, there are too many tombstones. and ops with the cluster is a normal maintenance.

**Comment by cjc7373** [comment]
This behavior seems like to be undocumented. Might be a good idea to mention it somewhere?
