### ISSUE TITLE
CPU cost by `fixBetterLocation` is high

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#5360]
## Enhancement Task
Once we have TiFlash, there could be many rules. And if these rules all have location labels and ask for more than 1 replica, every region will enter the fixBetterLocation logic and cannot skip it, which could waste CPU since there are some heavy operations like filtering and comparing locations. We need to improve it in this situation. See https://github.com/tikv/pd/blob/master/server/schedule/checker/rule_checker.go#L285-L301

Here is the profile:
![image-2022-07-26-14-35-24-192 (1)](https://user-images.githubusercontent.com/35896542/181004633-6398f582-d4b0-45cf-8e1b-331b800e8cc7.png)

**Comment by nolouch** [comment]
Fixed by https://github.com/pingcap/tidb-operator/issues/4678

**Comment by nolouch** [comment]
But we may consider more ways to improve the performance.
