### ISSUE TITLE
Region does not distribute after plugging new server

### ISSUE THREAD

**Issue by phamtai97** [tikv/pd#5417]
Hi all,
I have a problem related to distribution data in the cluster after i plugged new servers into the current cluster. 
I have two datacenter in one city. Firstly, i only ran one datacenter (id: 1) with 5 servers. After that I plugged in a new datacenter (id: 2) with 3 servers. I set up leaders to only place in the datacenter 1, so servers of datacenter 2 have no leader. Then, I monitored and saw that data was rebalanced from datacenter 1 to datacenter 2. But there is a problem. Can see below image:

<img width="1366" alt="Screen Shot 2022-08-10 at 10 16 54" src="https://user-images.githubusercontent.com/38773351/183807647-cd43557d-7bde-4469-af03-3ab781ae39f0.png">

We can easily see node 1.0.1.20 (node in datacenter 1) and node 1.0.0.23 (node in datacenter 2) has more region score than other nodes, although leaders is balance between nodes in cluster. 

Before I plugged servers of datacenter 2 to a TiDB cluster of datacenter 1, servers of datacenter 1 have the same region and data size.

![Screen Shot 2022-08-10 at 12 43 38](https://user-images.githubusercontent.com/38773351/183824482-7b009e27-2a4e-44c5-b43c-a0335ab8088d.png)

Besides, we also triggered the rebalance region but it did not resolve the problem.

My config here:
```
» config show
{
  "replication": {
    "enable-placement-rules": "true",
    "enable-placement-rules-cache": "false",
    "isolation-level": "dc",
    "location-labels": "zone,dc,rack,host",
    "max-replicas": 5,
    "strictly-match-label": "false"
  },
  "schedule": {
    "enable-cross-table-merge": "true",
    "enable-joint-consensus": "true",
    "high-space-ratio": 0.7,
    "hot-region-cache-hits-threshold": 2,
    "hot-region-schedule-limit": 8,
    "hot-regions-reserved-days": 7,
    "hot-regions-write-interval": "10m0s",
    "leader-schedule-limit": 4,
    "leader-schedule-policy": "size",
    "low-space-ratio": 0.8,
    "max-merge-region-keys": 200000,
    "max-merge-region-size": 20,
    "max-pending-peer-count": 64,
    "max-snapshot-count": 64,
    "max-store-down-time": "30m0s",
    "merge-schedule-limit": 8,
    "patrol-region-interval": "10ms",
    "region-schedule-limit": 2048,
    "region-score-formula-version": "v2",
    "replica-schedule-limit": 64,
    "split-merge-interval": "1h0m0s",
    "tolerant-size-ratio": 20
  }
}
```
I think that PD seems to wrongly calculate region score lead to unbalance region score.

I have some questions:
- What is happened problem?
- Why does it happen?
- How to balance data in the cluster? How to fix it?

Thank you.

****

**Comment by nolouch** [comment]
Hi @phamtai97 , could you show more information with `pd-ctl store`?

**Comment by phamtai97** [comment]
Hi @nolouch
This is a result:

```json
» store
{
  "count": 8,
  "stores": [
    {
      "store": {
        "id": 2,
        "address": "10.0.1.24:20160",
        "labels": [
          {
            "key": "zone",
            "value": "vn"
          },
          {
            "key": "rack",
            "value": "1AL33"
          },
          {
            "key": "host",
            "value": "DB-1.24"
          },
          {
            "key": "dc",
            "value": "qtsc"
          }
        ],
        "version": "5.4.1",
        "status_address": "1.0.1.24:20180",
        "git_hash": "91fe561f0af87cc47359cdf61d6e6838471cb644",
        "start_timestamp": 1657573268,
        "deploy_path": "/data/tidb-v5-deploy/tikv-20160/bin",
        "last_heartbeat": 1660124898363324012,
        "state_name": "Up"
      },
      "status": {
        "capacity": "3.436TiB",
        "available": "2.719TiB",
        "used_size": "504.9GiB",
        "leader_count": 8587,
        "leader_weight": 1,
        "leader_score": 794307,
        "leader_size": 794307,
        "region_count": 21505,
        "region_weight": 1,
        "region_score": 2178631.798707262,
        "region_size": 1992356,
        "slow_score": 1,
        "receiving_snap_count": 1,
        "start_ts": "2022-07-12T04:01:08+07:00",
        "last_heartbeat_ts": "2022-08-10T16:48:18.363324012+07:00",
        "uptime": "708h47m10.363324012s"
      }
    },
    {
      "store": {
        "id": 7,
        "address": "1.0.1.24:20160",
        "labels": [
          {
            "key": "zone",
            "value": "vn"
          },
          {
            "key": "rack",
            "value": "1AF38"
          },
          {
            "key": "host",
            "value": "DB-1.22"
          },
          {
            "key": "dc",
            "value": "qtsc"
          }
        ],
        "version": "5.4.1",
        "status_address": "1.0.1.22:20180",
        "git_hash": "91fe561f0af87cc47359cdf61d6e6838471cb644",
        "start_timestamp": 1653413782,
        "deploy_path": "/data/tidb-v5-deploy/tikv-20160/bin",
        "last_heartbeat": 1660124898854990332,
        "state_name": "Up"
      },
      "status": {
        "capacity": "3.436TiB",
        "available": "2.718TiB",
        "used_size": "505.6GiB",
        "leader_count": 8608,
        "leader_weight": 1,
        "leader_score": 797725,
        "leader_size": 797725,
        "region_count": 21478,
        "region_weight": 1,
        "region_score": 2177987.719119125,
        "region_size": 1991701,
        "slow_score": 1,
        "sending_snap_count": 2,
        "receiving_snap_count": 1,
        "start_ts": "2022-05-25T00:36:22+07:00",
        "last_heartbeat_ts": "2022-08-10T16:48:18.854990332+07:00",
        "uptime": "1864h11m56.854990332s"
      }
    },
    {
      "store": {
        "id": 8,
        "address": "1.0.1.23:20160",
        "labels": [
          {
            "key": "zone",
            "value": "vn"
          },
          {
            "key": "rack",
            "value": "1AL33"
          },
          {
            "key": "host",
            "value": "DB-1.23"
          },
          {
            "key": "dc",
            "value": "qtsc"
          }
        ],
        "version": "5.4.1",
        "status_address": "1.0.1.23:20180",
        "git_hash": "91fe561f0af87cc47359cdf61d6e6838471cb644",
        "start_timestamp": 1653413317,
        "deploy_path": "/data/tidb-v5-deploy/tikv-20160/bin",
        "last_heartbeat": 1660124895589995097,
        "state_name": "Up"
      },
      "status": {
        "capacity": "3.436TiB",
        "available": "2.723TiB",
        "used_size": "503GiB",
        "leader_count": 8582,
        "leader_weight": 1,
        "leader_score": 796605,
        "leader_size": 796605,
        "region_count": 21443,
        "region_weight": 1,
        "region_score": 2175445.0020835083,
        "region_size": 1989557,
        "slow_score": 1,
        "start_ts": "2022-05-25T00:28:37+07:00",
        "last_heartbeat_ts": "2022-08-10T16:48:15.589995097+07:00",
        "uptime": "1864h19m38.589995097s"
      }
    },
    {
      "store": {
        "id": 9,
        "address": "1.0.1.21:20160",
        "labels": [
          {
            "key": "zone",
            "value": "vn"
          },
          {
            "key": "rack",
            "value": "1AF38"
          },
          {
            "key": "host",
            "value": "DB-1.21"
          },
          {
            "key": "dc",
            "value": "qtsc"
          }
        ],
        "version": "5.4.1",
        "status_address": "1.0.1.21:20180",
        "git_hash": "91fe561f0af87cc47359cdf61d6e6838471cb644",
        "start_timestamp": 1653413054,
        "deploy_path": "/data/tidb-v5-deploy/tikv-20160/bin",
        "last_heartbeat": 1660124893188417625,
        "state_name": "Up"
      },
      "status": {
        "capacity": "3.436TiB",
        "available": "2.72TiB",
        "used_size": "503.2GiB",
        "leader_count": 8571,
        "leader_weight": 1,
        "leader_score": 795159,
        "leader_size": 795159,
        "region_count": 21470,
        "region_weight": 1,
        "region_score": 2176288.526747567,
        "region_size": 1990212,
        "slow_score": 1,
        "sending_snap_count": 1,
        "start_ts": "2022-05-25T00:24:14+07:00",
        "last_heartbeat_ts": "2022-08-10T16:48:13.188417625+07:00",
        "uptime": "1864h23m59.188417625s"
      }
    },
    {
      "store": {
        "id": 263685,
        "address": "1.0.0.23:20160",
        "labels": [
          {
            "key": "zone",
            "value": "vn"
          },
          {
            "key": "rack",
            "value": "1AP09"
          },
          {
            "key": "host",
            "value": "DB-0.23"
          },
          {
            "key": "dc",
            "value": "campus"
          }
        ],
        "version": "5.4.1",
        "status_address": "1.0.0.23:20180",
        "git_hash": "91fe561f0af87cc47359cdf61d6e6838471cb644",
        "start_timestamp": 1659977540,
        "deploy_path": "/data/tidb-v5-deploy/tikv-20160/bin",
        "last_heartbeat": 1660124901624067044,
        "state_name": "Up"
      },
      "status": {
        "capacity": "3.438TiB",
        "available": "2.272TiB",
        "used_size": "976.6GiB",
        "leader_count": 0,
        "leader_weight": 1,
        "leader_score": 0,
        "leader_size": 0,
        "region_count": 42946,
        "region_weight": 1,
        "region_score": 4397617.4101327,
        "region_size": 3981723,
        "slow_score": 1,
        "start_ts": "2022-08-08T23:52:20+07:00",
        "last_heartbeat_ts": "2022-08-10T16:48:21.624067044+07:00",
        "uptime": "40h56m1.624067044s"
      }
    },
    {
      "store": {
        "id": 263912,
        "address": "1.0.0.25:20160",
        "labels": [
          {
            "key": "zone",
            "value": "vn"
          },
          {
            "key": "rack",
            "value": "1AP07"
          },
          {
            "key": "host",
            "value": "DB-0.25"
          },
          {
            "key": "dc",
            "value": "campus"
          }
        ],
        "version": "5.4.1",
        "status_address": "1.0.0.25:20180",
        "git_hash": "91fe561f0af87cc47359cdf61d6e6838471cb644",
        "start_timestamp": 1659636774,
        "deploy_path": "/data/tidb-v5-deploy/tikv-20160/bin",
        "last_heartbeat": 1660124893887435729,
        "state_name": "Up"
      },
      "status": {
        "capacity": "3.438TiB",
        "available": "2.743TiB",
        "used_size": "493.5GiB",
        "leader_count": 0,
        "leader_weight": 1,
        "leader_score": 0,
        "leader_size": 0,
        "region_count": 21456,
        "region_weight": 1,
        "region_score": 2172610.6091105402,
        "region_size": 1987753,
        "slow_score": 1,
        "receiving_snap_count": 1,
        "start_ts": "2022-08-05T01:12:54+07:00",
        "last_heartbeat_ts": "2022-08-10T16:48:13.887435729+07:00",
        "uptime": "135h35m19.887435729s"
      }
    },
    {
      "store": {
        "id": 263913,
        "address": "1.0.0.24:20160",
        "labels": [
          {
            "key": "zone",
            "value": "vn"
          },
          {
            "key": "rack",
            "value": "1AP07"
          },
          {
            "key": "host",
            "value": "DB-0.24"
          },
          {
            "key": "dc",
            "value": "campus"
          }
        ],1.0.1.20
        "version": "5.4.1",
        "status_address": "1.0.0.24:20180",
        "git_hash": "91fe561f0af87cc47359cdf61d6e6838471cb644",
        "start_timestamp": 1659636774,
        "deploy_path": "/data/tidb-v5-deploy/tikv-20160/bin",
        "last_heartbeat": 1660124901505906648,
        "state_name": "Up"
      },
      "status": {
        "capacity": "3.438TiB",
        "available": "2.744TiB",
        "used_size": "493.3GiB",
        "leader_count": 0,
        "leader_weight": 1,
        "leader_score": 0,
        "leader_size": 0,
        "region_count": 21492,
        "region_weight": 1,
        "region_score": 2179560.7357748505,
        "region_size": 1994187,
        "slow_score": 1,
        "start_ts": "2022-08-05T01:12:54+07:00",
        "last_heartbeat_ts": "2022-08-10T16:48:21.505906648+07:00",
        "uptime": "135h35m27.505906648s"
      }
    },
    {
      "store": {
        "id": 1,
        "address": "1.0.1.20:20160",
        "labels": [
          {
            "key": "zone",
            "value": "vn"
          },
          {
            "key": "rack",
            "value": "1AR25"
          },
          {
            "key": "host",
            "value": "DB-1.20"
          },
          {
            "key": "dc",
            "value": "qtsc"
          }
        ],
        "version": "5.4.1",
        "status_address": "1.0.1.20:20180",
        "git_hash": "91fe561f0af87cc47359cdf61d6e6838471cb644",
        "start_timestamp": 1653412605,
        "deploy_path": "/data/tidb-v5-deploy/tikv-20160/bin",
        "last_heartbeat": 1660124897767117548,
        "state_name": "Up"
      },
      "status": {
        "capacity": "3.436TiB",
        "available": "2.223TiB",
        "used_size": "1011GiB",
        "leader_count": 8598,
        "leader_weight": 1,
        "leader_score": 797927,
        "leader_size": 797927,
        "region_count": 42946,
        "region_weight": 1,
        "region_score": 4403410.68563885,
        "region_size": 3981723,
        "slow_score": 1,
        "sending_snap_count": 1,
        "start_ts": "2022-05-25T00:16:45+07:00",
        "last_heartbeat_ts": "2022-08-10T16:48:17.767117548+07:00",
        "uptime": "1864h31m32.767117548s"
      }
    }
  ]
}
```

**Comment by nolouch** [comment]
Hi, @phamtai97 .  I think the score is not wrong according to the `used_size`, but why not balanced need to diagnose?  Could you report some information to us? if you use `tiup` to deploy the cluster, you can use the clinic to report it: https://docs.pingcap.com/tidb/stable/quick-start-with-clinic. and give us the url.

**Comment by phamtai97** [comment]
I am sorry, we use TiDB v5.4.0. It have no above feature.

**Comment by phamtai97** [comment]
If you need to more infomation, I can provide it for you to support investigate the problem.

**Comment by nolouch** [comment]
I think it also may work in v5.4.0. you can have a try.
BTW, I need your placement rule settings. `pd-ctl  config placement-rule load`

**Comment by phamtai97** [comment]
It result:

```json
» config placement-rules show
[
  {
    "group_id": "pd",
    "id": "default",
    "start_key": "",
    "end_key": "",
    "role": "voter",
    "count": 5,
    "location_labels": [
      "zone",
      "dc",
      "rack",
      "host"
    ]
  }
]
```

**Comment by nolouch** [comment]
> I set up leaders to only place in the datacenter 1

How do you set it?

**Comment by phamtai97** [comment]
I ran  config set label-property reject-leader dc campus

**Comment by phamtai97** [comment]
@nolouch Do you have any update?

**Comment by nolouch** [comment]
I need some metrics, if you can use the clinic, I would happy to diagnose it.

**Comment by phamtai97** [comment]
Currently, I cannot set it up and we have some important private metrics, so I cannot share it with you. But I can screenshot and post here if you need any metric.

**Comment by nolouch** [comment]
@phamtai97 Could you show the `PD-Operator` and `PD-Scheduler` relative metrics in grafana?

**Comment by phamtai97** [comment]
@nolouch 
There are here:
<img width="1410" alt="Screen Shot 2022-08-10 at 22 05 58" src="https://user-images.githubusercontent.com/38773351/183939507-0c16902c-3d77-4934-a893-d729abb64164.png">

<img width="1407" alt="Screen Shot 2022-08-10 at 22 06 17" src="https://user-images.githubusercontent.com/38773351/183939553-d7542784-c6ab-415a-a558-63daba5d34dd.png">

<img width="1407" alt="Screen Shot 2022-08-10 at 22 06 32" src="https://user-images.githubusercontent.com/38773351/183939592-08422582-fa1f-429e-87b5-513989fd4dba.png">

**Comment by phamtai97** [comment]
You can see the shuffle metric because we ran shuffle region to rebalance region. But it did not resolve the problem.

**Comment by phamtai97** [comment]
We have 8 nodes and set max replicate is 5, so Can it impact to distribute data between nodes in cluster?

**Comment by nolouch** [comment]
@phamtai97  the proposal of `shuffle region` do not rebalance the region, you should remove it.

**Comment by rleungx** [comment]
I think in your case, the region is distributed at the rack level since you have set 5 replicas. From the store information, we can find that the number of stores in `1AL33:1AF38:1AR25:1AP09:1AP07` is 2:2:1:1:2. So the store in the rack 1AR25 and 1AP09 will have double region number than others which are store 1 and store 263685.

**Comment by phamtai97** [comment]
@rleungx Thank you very much, so  How do we update config to rebalance them?

**Comment by phamtai97** [comment]
@nolouch  Can you help me?

**Comment by rleungx** [comment]
The basic idea is to add 2 more stores in 1AR25 and 1AP09, which can tolerate two racks crushed. Because the store num mod replica number is not equal to 0. If you want all stores to have the same region size, you can just remove the location label setting but it will lose the isolation.

**Comment by phamtai97** [comment]
That means config

```json
{
  "replication": {
    "isolation-level": "dc",
    "location-labels": "zone,dc,rack,host",
  }
```

And I have to update to:
```json
{
  "replication": {
    "isolation-level": "",
    "location-labels": "",
  },
```

**Comment by rleungx** [comment]
> That means we have to change the config:
> 
> ```json
> {
>   "replication": {
>     "isolation-level": "dc",
>     "location-labels": "zone,dc,rack,host",
>   }
> ```
> 
> to:
> 
> ```json
> {
>   "replication": {
>     "isolation-level": "",
>     "location-labels": "",
>   },
> ```
> 
> And how does it affect current data? Because we have two datacenters and we want data replicated for two datacenters to increase available for database. If we remove isolation, Is the data copied to another data center? I saw a document here: https://docs.pingcap.com/tidb/v5.4/configure-placement-rules

It will rebalance some regions. If there are more than 2 stores crushed, it may introduce an availability problem. So I suggest you add two more stores which is the first way.

**Comment by phamtai97** [comment]
How to add more stores to the current rack? And we set up  "isolation-level": "dc", it is affect data replication.

**Comment by rleungx** [comment]
> How to add more stores to the current rack?

If you are using TiUP, you can see https://docs.pingcap.com/tidb/dev/scale-tidb-using-tiup for more details

> And we set up "isolation-level": "dc", Does it affect data replication?

You can take a look at https://docs.pingcap.com/tidb/stable/schedule-replicas-by-topology-labels

> And Why PD do not create 8 rack / 8 server instead of 5 rack / 8 server?

PD won't automatically set a label for TiKV. So it could be that you have a such configuration in TiKV. You can change the store label by using pd-ctl. See https://docs.pingcap.com/tidb/stable/pd-control#store-delete--cancel-delete--label--weight--remove-tombstone--limit--store_id---jqquery-string. e.g., `store label 1 zone a dc b rack c host d --force` will overwrite the store 1 label to `{zone:a, dc:b, rack:c host:d}`

**Comment by phamtai97** [comment]
If I change the store lable, the current data is rebalanced, right? Does it affect to production?

**Comment by rleungx** [comment]
> If I change the store label, the current data is rebalanced, right? Does it affect to production?

Yes, it will. Whether it affects the production depends on your workload pressure. Because the rebalance process may cause some extra compaction operations of RocksDB.

**Comment by phamtai97** [comment]
I have just checked the config, I set the duplicate rack for servers. So, currently, can I overwrite rack label for 3 servers? Because I have 8 servers, there are 3 double servers (ex: server 1, 2 have the same rack label) that are duplicated rack label. So, I need to change 3 servers with different rack labels. Finally, I have 8 racks / 8 servers, and data is rebalanced, right?

**Comment by phamtai97** [comment]
@rleungx Could you answer my question?

**Comment by rleungx** [comment]
> I update rack label to 8 racks, how does data distribute in cluster? Is data guaranteed to have a copy in another data center?

AFAICT, it cannot guarantee each DC has at least one replica if you update to 8 racks without `isolation-level: "dc"`. As for `isolation-level`, you can check the example in https://docs.pingcap.com/tidb/stable/schedule-replicas-by-topology-labels for the details.

**Comment by rleungx** [comment]
Maybe you can take a look at https://docs.pingcap.com/tidb/dev/two-data-centers-in-one-city-deployment or https://docs.pingcap.com/tidb/dev/multi-data-centers-in-one-city-deployment

**Comment by phamtai97** [comment]
Thank you @rleungx. We will review our cluster again.

**Comment by lhy1024** [comment]
Because it has not been updated for a long time, I will close it first, feel free to reopen it
