### ISSUE TITLE
Hot Region: Resolve dimensional conflict problem and enhance stability 

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#5446]
## Background
There are some stability issue in our benchmarks:
- case 1: https://github.com/tikv/pd/issues/4529
- case 2: 

And also it's met in some user scenarios, that need us to turn some paraments to solve that.
Stability:
- case : https://github.com/tikv/pd/issues/3919

and we found it's relative the randomly hot-spot scheduling, The effect of each round of testing is different, and some round fall into the **local optimal solution**, not ** global optimal solution**, and then because of dimensional conflict, no any scheduling can produce.

## Tasks

Enhance Hot-Region Algorithm
- [x] https://github.com/tikv/pd/issues/4949

**Comment by lhy1024** [comment]
![image](https://user-images.githubusercontent.com/19542290/200800692-f133d846-a4d5-473b-93db-c3fe9b2b88a8.png)

Performance improvement greater than 1% marked green.
performance regression greater than 1% marked red, stability evaluated by coefficient of variation, v2 greater than 0.05 and positive variation, marked red.
results are related to load and environment, marked yellow.
v2 is more balanced compared with v1, but the qps is not improved, marked blue; the scheduling convergence result is related to the split result, marked light blue.

**Comment by lhy1024** [comment]
@nolouch @HunDunDM Can we close it?

**Comment by lhy1024** [comment]
I will close this issue first, feel free to reopen it.
