### ISSUE TITLE
Improve the scheduler's performance in big cluster

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#5473]
## Enhancement Task
Arm： the qps of the `balance-region-scheduler` should not less than 100  for 200 nodes (includes 30 tiflash).
In 6.2 version , the qps is 2op/s.  
#### Placement Rule Influence
![image](https://user-images.githubusercontent.com/6428910/188797228-c65b0bb2-ef24-48f7-ac34-7c3f19a2cd86.png)
- [x] #5522  improve 10X ==>20  ops
- [x]  https://github.com/tikv/pd/pull/5553 ==> 1.2X
- [x] #5537
- [x] #5538 ==> 50ops
- [x] #5645

#### Balance region scheduler
- [x] #5539 improve 1.5X ==> 30 ops 
- [x] https://github.com/tikv/pd/pull/5555 ==> 1.5X 

#### Batch
- [ ] One `schedule()` can produce multi operators
#### Concurrency
- [ ] handy add multi same scheduler
- [ ] Supports concurrency for each scheduler

#### Grouping by resident label 
- [ ] Label split to `Location Labels` and `Attribution Labels`. `Location Labels` has the keyword [Region, Zone, Host].

**Comment by bufferflies** [comment]
link https://github.com/tikv/pd/pull/5480/files

**Comment by bufferflies** [comment]
ref: https://github.com/pingcap/log/issues/28

**Comment by lhy1024** [comment]
It seems to be related with https://github.com/tikv/pd/issues/3744

**Comment by nolouch** [comment]
close due to finished.
