### ISSUE TITLE
multi-region dr: after down and restarting the primary cluster, the placement policy doesn't work as before

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/pd#5504]
### What did you expect to see?
Leader should only set in east-1.

### What did you see instead?
The leaders were balanced between all regions after restarting the cluster in east-1
![image](https://user-images.githubusercontent.com/9443637/190297224-4c86d3b0-e432-4616-a4d2-3a2d9bd4c556.png)

### What version of PD are you using (`pd-server -V`)?
6.1.1

**Comment by nolouch** [comment]
the problem not in the release branch.
