### ISSUE TITLE
observability:  expose region rule fit detail 

### ISSUE THREAD

**Issue by bufferflies** [tikv/pd#5507]
## Enhancement Task
In past, It is difficult to diagnose the placement rule is not right . 

It is appreciate that pd-ctl can show the region fitting rule, like this:

```
/pd-ctl region rules xxx

{
   orphanPeers: [{peer_id,store_id,role}...],
   fitRule: [{ 
       rule_id:xxx,
       group_id:xxx,
       peers:[{peer_id,store_id,role}],
       different_roles: [{peer_id,store_id,role}],
}]
}
```

**Comment by rleungx** [comment]
Does https://github.com/tikv/pd/pull/5433 meet your requirement?
