### ISSUE TITLE
pd-ctl: hot write store query is zero when run bench

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#5643]
### What did you do?

run tpcc bench and get hot write peer with `pd-ctl`

### What did you expect to see?

not zero

### What did you see instead?

store query is zero, but there are many hot peers.

![image](https://user-images.githubusercontent.com/19542290/198250853-2d1bc3a5-6620-4222-8e36-e2180847ef4d.png)

### What version of PD are you using (`pd-server -V`)?

master

**Comment by matchge-ca** [comment]
Tested multiple PD versions including v6.1 and v6.3, as well as binary build from `master` branch and couldn't reproduce the issue. The `"store_query": 0` only existed in the `as_peer` section, and the `store_query` for `as_leader` regions have non-zero values, which is expected. 
Screenshots attached below:

<img width="1191" alt="Screen Shot 2022-11-30 at 4 20 25 PM" src="https://user-images.githubusercontent.com/74505524/204911183-fdde6863-f826-4be1-8cef-b506c13acf75.png">
<img width="465" alt="Screen Shot 2022-11-30 at 3 53 50 PM" src="https://user-images.githubusercontent.com/74505524/204911185-8bf85854-4b11-4235-8f80-cfd6c949ceee.png">
<img width="459" alt="Screen Shot 2022-11-30 at 3 53 17 PM" src="https://user-images.githubusercontent.com/74505524/204911186-a62ff422-f531-4396-be7f-b463c76c3bb9.png">
