### ISSUE TITLE
`TestExternalTimestamp` failed

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#5682]
### Which jobs are failing
```
--- FAIL: TestExternalTimestamp (2.22s)
    cluster_test.go:1529: 
        	Error Trace:	cluster_test.go:1529
        	Error:      	Not equal: 
        	            	expected: 0xe9
        	            	actual  : 0x611088156b00002
        	Test:       	TestExternalTimestamp
```

### CI link
https://github.com/tikv/pd/actions/runs/3392914559/jobs/5639655252

**Comment by rleungx** [comment]
https://github.com/tikv/pd/actions/runs/3545263062/jobs/5953266987

**Comment by lhy1024** [comment]
> https://github.com/tikv/pd/actions/runs/3545263062/jobs/5953266987

The log shows globalTS increase more than 2 seconds, maybe test is so slow, we need to use `eventually` in test.

**Comment by lhy1024** [comment]
After increasing the time interval, the test became stable
