### ISSUE TITLE
Hot region consumes too much memory

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#5692]
## Enhancement Task
When there is a large number of regions, it will cause PD OOM sometimes.

<img width="1920" alt="Screen Shot 2022-11-09 at 3 56 20 PM" src="https://user-images.githubusercontent.com/35896542/200771357-498ed900-3f3b-4cd9-afc9-2590b3f6c2eb.png">

**Comment by rleungx** [comment]
BTW, it also consumes lots of CPU.

**Comment by lhy1024** [comment]
- [x] #5709
- [x] #5716
- [x] #5721
- [x] #5728
- [x] #5729
- [x] #5734
- [x] #5700
- [ ] #5749
- [ ] #5752

Before: v6.4 ea9b1e9
BenchmarkCheckRegionFlow-40        64240             19952 ns/op            5849 B/op         87 allocs/op
After: master 500b0d6
BenchmarkCheckRegionFlow-40        78693             15800 ns/op            4023 B/op         60 allocs/op

Before: v6.4 ea9b1e9
462 + 3340
![image](https://user-images.githubusercontent.com/19542290/205590586-706ac782-434a-4281-8513-760674e92ac9.png)

After: master 500b0d6
307 + 2891
![image](https://user-images.githubusercontent.com/19542290/205590640-a48feeb1-a9b8-4340-866e-db8c20bbc372.png)
