### ISSUE TITLE
Improve GC policy

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#5707]
## Enhancement Task
GC consumes lots of CPU, we need to improve it.
<img width="1792" alt="Screen Shot 2022-11-15 at 2 21 58 PM" src="https://user-images.githubusercontent.com/35896542/201842047-211e1ebc-a863-4d9e-94ff-3bb03ce97a7f.png">

**Comment by nolouch** [comment]
closed by https://github.com/tikv/pd/issues/5827
