### ISSUE TITLE
pd-leader cannot get new tso

### ISSUE THREAD

**Issue by qiaohao9** [tikv/pd#5742]
## Bug Report

![image](https://user-images.githubusercontent.com/15377472/204954150-589b3bf3-1d62-4987-ad96-800c428da75b.png)

### What did you do?

transfer pd leader via pd-ctl every 15s

### What did you expect to see?

everything is ok, and pd is working normal.

### What did you see instead?

pd tso is zerotime, and the client cannot get the ts forever.

### What version of PD are you using (`pd-server -V`)?

v5.2.0

**Comment by nolouch** [comment]
@qiaohao9  How long the log report?

**Comment by qiaohao9** [comment]
> @qiaohao9 How long the log report?

until restarting the pd.

**Comment by nolouch** [comment]
lack of information
