### ISSUE TITLE
Balance region scheduler doesn't work as expected

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#5790]
### What did you do?

Scale out one TiKV.

### What did you expect to see?
<img width="680" alt="Screen Shot 2022-12-16 at 12 56 52 PM" src="https://user-images.githubusercontent.com/35896542/208025912-f799dbbd-eae4-474e-b855-351952193ad3.png">
<img width="681" alt="Screen Shot 2022-12-16 at 12 56 58 PM" src="https://user-images.githubusercontent.com/35896542/208025922-4c0a56da-3225-4e9b-ae24-e24f9122104a.png">
<img width="680" alt="Screen Shot 2022-12-16 at 12 57 18 PM" src="https://user-images.githubusercontent.com/35896542/208025927-93ba34be-1982-4a9f-b929-6333e617fbb0.png">
<img width="681" alt="Screen Shot 2022-12-16 at 12 57 28 PM" src="https://user-images.githubusercontent.com/35896542/208025930-e69bf8f1-0ce6-4fa9-ad77-d6c31c062ba9.png">
<img width="684" alt="Screen Shot 2022-12-16 at 12 57 46 PM" src="https://user-images.githubusercontent.com/35896542/208025935-127e1953-6589-4109-bb0d-26f848712f33.png">
<img width="680" alt="Screen Shot 2022-12-16 at 1 00 41 PM" src="https://user-images.githubusercontent.com/35896542/208026016-c7ba5b8e-180d-46a3-9788-a2dee823d4fb.png">

The balance region scheduler should work and move the region from tikv-1 to tikv-14.

### What did you see instead?
The balance region scheduler did nothing for a long time.
Here is the debug log:
```
[2022/12/16 04:40:12.106 +00:00] [DEBUG] [utils.go:152] ["skip balance region"] [scheduler=balance-region-scheduler] [region-id=261496114] [source-store=14] [target-store=262514593] [source-size=8672409]
[source-score=9445391.149876121] [target-size=362] [target-score=6994600837.542799] [average-region-size=21] [tolerant-resource=47794]
```
The score is not expected and is not the same as the monitor.

### What version of PD are you using (`pd-server -V`)?
v6.5.0

**Comment by bufferflies** [comment]
The root cause is that the disk of the `tikv-14` has extra files,  so the amp(region_size /store_used_size) will be very small, the compensation  of the used size will be exceeding big.
