### ISSUE TITLE
Decoupling the resource manager  service relies on `pd/server` package

### ISSUE THREAD

**Issue by nolouch** [tikv/pd#5804]
## Development Task
Currently, the service may relies on the `pd/server`, like the service manager:
https://github.com/tikv/pd/blob/c5b06e2bde0852594b6f7d5a8a673a5b29cb0dfb/pkg/mcs/resource_manager/server/grpc_service.go#L24

We should remove this dependency.

**Comment by rleungx** [comment]
Close it since https://github.com/tikv/pd/pull/5933 is merged
