### ISSUE TITLE
Separate TSO into an independent service

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#5836]

**Comment by binshi-bing** [comment]
assign to me?

**Comment by rleungx** [comment]
> assign to me?

Yes, but I cannot find you on the assignee list. lol

**Comment by binshi-bing** [comment]
## pre-work tracked below

- [x] #5779 
- [x] #5771 
- [x] (Cancelled) [Support tso service #1038 in kvproto repo](https://github.com/pingcap/kvproto/pull/1038/files)
- [x] (Cancelled) #5852
- [ ] #5837 
- [x] #5857
- [ ] #5858
- [ ] #5874

**Comment by binshi-bing** [comment]
@rleungx could you me grant me the access to modify this issue?

**Comment by binshi-bing** [comment]
Define an independent TSO gRPC server #1053 https://github.com/pingcap/kvproto/pull/1053

**Comment by binshi-bing** [comment]
Closed by mistake. Reopen it.

**Comment by binshi-bing** [comment]
Closed by [#5986](https://github.com/tikv/pd/pull/5986) by mistake. @rleungx , could you help to reopen this issue? It seems that I don't have permission to do it.
