### ISSUE TITLE
metrics: unify '-' and '_' in schedulers and checkers

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#5845]
## Enhancement Task
There are mixed '-' and '_' in schedulers and checkers
```
replicaCheckerName = "replica-checker"
replicaChecker     = "replica_checker"
```

**Comment by lhy1024** [comment]
how about unified with '_'? @nolouch @rleungx

**Comment by nolouch** [comment]
lgtm

**Comment by okJiang** [comment]
According to the conclusion in this [PR](https://github.com/tikv/pd/issues/8379), this issue can be closed.

> For monitoring, it will be used as a filter rule_checker/replica_checker/merge_checker , temporarily converted from xxxx-checker to xxxx_checker when needed to maintain user experience compatibility. If it is determined that there is no compatibility problem, then change it

**Comment by okJiang** [comment]
Please help to close the issue~ cc @rleungx @lhy1024
