### ISSUE TITLE
Why does the curl command not exist in the 6.5.0 image of dockerhub?

### ISSUE THREAD

**Issue by mikechengwei** [tikv/pd#5876]
## Bug Report
Ref:
https://github.com/tikv/pd/blob/d1c0d840ddedee767df9814ae0015bf80f441e40/Dockerfile#L36
I have add curl command in dockerfile,but the recently generated image does not match this, what else needs to be synchronized?

### What did you expect to see?
There is a curl command in 6.5.0 image.
### What version of PD are you using (`pd-server -V`)?
6.5.0 image.

**Comment by rleungx** [comment]
Yes, we use [another dockerfile](https://github.com/PingCAP-QE/ci/blob/main/jenkins/Dockerfile/release/linux-amd64/pd) which is the simplest and has fewer security vulnerabilities. If you have some other requirement, you can build your own.
