### ISSUE TITLE
TiKV status will stay in preparing mode if scale out immediately after create cluster

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/pd#5944]
### What did you do?
create a cluster then scale out from 3 tikv to 6 tikv.

### What did you expect to see?
The new online stores will change to normal after serval minutes.

### What did you see instead?
Didn't change to normal after 10min.

### What version of PD are you using (`pd-server -V`)?
master

Here is the Grafana 
![image](https://user-images.githubusercontent.com/9443637/217504894-bbaba5d6-7e4f-4ded-b4b1-e24360273d8d.png)

**Comment by rleungx** [comment]
Close it since PR has been merged.
