### ISSUE TITLE
pd-ctl unable to delete rule-group

### ISSUE THREAD

**Issue by matchge-ca** [tikv/pd#5967]
### What did you do?
- Add new placement rule group, ie `pd2`
- Execute `pd-ctl config placement-rules rule-group delete pd2`

### What did you expect to see?
Rule group `pd2` is removed

### What did you see instead?
Nothing changes, `pd-ctl config placement-rules show` shows `pd2` is still existed

### What version of PD are you using (`pd-server -V`)?
v6.1.1

**Comment by matchge-ca** [comment]
Found few issues related to this bug:

1. `http request` response is ignored, and only error message or `Success!` will be returned. The behavior is different compare to `rule-bundle delete`
https://github.com/tikv/pd/blob/e6086c444b72a1754f247a5d11caa123ffffd7d2/tools/pd-ctl/pdctl/command/config_command.go#L671-L676
2. `pd-ctl config placement-rules rule-group delete <id>` command is not working due to `deleteGroup` func does not reset/remove the placement group. 
`rule-bundle delete <id>` command deletes rules first, so the placement group/rules are able to be removed although it has the same logic to remove the group
https://github.com/tikv/pd/blob/e6086c444b72a1754f247a5d11caa123ffffd7d2/server/schedule/placement/config.go#L117-L119
3. `rule-group delete` and `rule-bundle delete` have similar functionality, the major diff that I can tell is `rule-bundle delete` supports regex, I think we should reserve both sub-commands to prevent compliance issue, but make it clear via document?

@rleungx @HunDunDM @lhy1024 PTAL

**Comment by nolouch** [comment]
I think the `bundle` can be used to unify later, and the `bundle` can guarantee atomicity. In the future, we can iterate two versions and slowly deprecate the `group` api.
