### ISSUE TITLE
Fix "pd-server's default client-urls and peer-urls use the same value and cause server initialization to fail"

### ISSUE THREAD

**Issue by binshi-bing** [tikv/pd#5995]
## Enhancement Task
The repro and error message is as below. The reason is that we use hard code "[http://127.0.0.1:2379]" as the default value to initialize both  client-urls and peer-urls

 ~/code/pingcap/my-pd1/bin   master  ./pd-server
...
[Info][etcd.go:117] ["configuring peer listeners"] [listen-peer-urls="[http://127.0.0.1:2379]"]
[Info][etcd.go:127] ["configuring client listeners"] [listen-client-urls="[http://127.0.0.1:2379]"]
[FATAL] [main.go:196] ["run server failed"] [error="[PD:etcd:ErrStartEtcd]listen tcp 127.0.0.1:2379: bind: address already in use: listen tcp 127.0.0.1:2379: bind: address already in use"]

**Comment by rleungx** [comment]
Close it since #5996 is merged.
