### ISSUE TITLE
tikv leader are unbalanced during br full restore data 

### ISSUE THREAD

**Issue by Lily2025** [tikv/pd#6017]
### What did you do?
6 tikvs（8c/32g）with az label
br full restore 20000 warehouse
https://tcms.pingcap.net/dashboard/executions/plan/1562736

### What did you expect to see?
pd leader are balanced during br full restore data 
![8da2338a-947a-456c-979f-6a91dcc8569b](https://user-images.githubusercontent.com/84712107/219609115-c52d6d9e-fd20-426a-a1eb-f22705f6b8dc.jpeg)

### What did you see instead?
pd leader are unbalanced during br full restore data 

### What version of PD are you using (`pd-server -V`)?
./pd-server -V
 Release Version: v6.6.0
Edition: Community
Git Commit Hash: 67c0fa283673257b4dc0839f19cd74fec5ef46fb
Git Branch: heads/refs/tags/v6.6.0
UTC Build Time:  2023-02-14 11:56:24
2023-02-17T03:25:41.343Z	INFO	k8s/client.go:132

**Comment by HunDunDM** [comment]
This bug was introduced by #5663 , `NewPlacementLeaderSafeguard` excessively limited the `Target Stores` of the `move leader`, resulting in an unexpected reduction in the set of optional Leaders.

**Comment by HunDunDM** [comment]
Run the unittest ( from #6054 ) on [master](https://github.com/tikv/pd/commit/6be15a506003d073f5b24c12abe89f1e0a05fcdd):

| StoreID | Peers Count | Leaders Count |
| ---- | ---- | ---- |
| 2 | 150 | 50 |
| 3 | 150 | 150 |
| 4 | 150 | 50 |
| 5 | 150 | 0 |
| 6 | 150 | 50 |
| 7 | 150 | 0 |

Run the unittest on #6054 :

| StoreID | Peers Count | Leaders Count |
| ---- | ---- | ---- |
| 2 | 150 | 50 |
| 3 | 150 | 50 |
| 4 | 150 | 50 |
| 5 | 150 | 50 |
| 6 | 150 | 50 |
| 7 | 150 | 50 |
