### ISSUE TITLE
TestWatcher is timeout

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#6079]
### Which jobs are failing
```
panic: test timed out after 15m0s
running tests:
	TestWatcher (14m57s)
```

### CI link
https://github.com/tikv/pd/actions/runs/4312696038/jobs/7523569233

**Comment by lhy1024** [comment]
cc @rleungx

**Comment by rleungx** [comment]
> cc @rleungx

It belongs to the key manager.

**Comment by rleungx** [comment]
Duplicated with #4879.
