### ISSUE TITLE
Refine the consumption reporting period of resource control controller

### ISSUE THREAD

**Issue by JmPotato** [tikv/pd#6113]
According to the resource control [Grafana panel](https://github.com/pingcap/tidb/blob/master/metrics/grafana/tidb_resource_control.json) and Prometheus sampling period, the `15s` or `N x 15s` would be more suitable for the resource controller to report the consumption metrics. However, currently, the reporting period is limited to around `10s` by the following code:

https://github.com/tikv/pd/blob/8cd4b16f9b65149e664e87bbe8fd79acfee76a82/client/resource_group/controller/controller.go#L283-L301

To make the Grafana metrics look more smooth and referable, it's needed to refine the reporting period in the controller.

**Comment by JmPotato** [comment]
@glorv @CabinfeverB @nolouch PTAL

**Comment by nolouch** [comment]
Maybe change the period to `5s`?

**Comment by CabinfeverB** [comment]
> Maybe change the period to `5s`?

I agree. The period should be adjusted to the factor of `15`
