### ISSUE TITLE
qps dorp to zero after inject pdleader io hang

### ISSUE THREAD

**Issue by Lily2025** [tikv/pd#6124]
### What did you do?
inject pdleader io hang 
https://tcms.pingcap.net/dashboard/executions/plan/1655438
http://perf.pingcap.net:3000/d/WOw1JWmVk/ha-test-case-detail?orgId=1&refresh=10s&var-case_id=2820188
![c8d6c931-8096-412e-90d3-3273eb313ce9](https://user-images.githubusercontent.com/84712107/223927129-9f8a2c6c-cccb-4a28-881e-23e6e853db62.jpeg)
![719777a4-a367-4d9f-92bb-d5526dec6c19](https://user-images.githubusercontent.com/84712107/223927160-bd8a2652-0b54-4741-8433-623dfc366179.jpeg)

### What did you expect to see?
QPS can recover within 2min

### What did you see instead?
QPS drop to zero until fault recover
![c8d6c931-8096-412e-90d3-3273eb313ce9](https://user-images.githubusercontent.com/84712107/223927435-cda3fd83-5a8c-420f-b384-d7bb79171c7b.jpeg)
![719777a4-a367-4d9f-92bb-d5526dec6c19](https://user-images.githubusercontent.com/84712107/223927454-1f2f036a-d797-4db4-b082-5a506b6515ea.jpeg)

clinc : https://clinic.pingcap.com.cn/portal/#/orgs/31/clusters/7208067513104263723?from=1678303062&to=1678304612
logs: http://minio.pingcap.net:38888/buckets/test-infra-testground/browse/YXJjaGl2ZS9lbmRsZXNzLWhhLXRlc3QtdHBzLTE2NTU0MzgtMS02MDM=

### What version of PD are you using (`pd-server -V`)?
./pd-server -V
 Release Version: v6.7.0-alpha
Edition: Community
Git Commit Hash: 8cd4b16f9b65149e664e87bbe8fd79acfee76a82
Git Branch: heads/refs/tags/v6.7.0-alpha
UTC Build Time:  2023-03-08 11:32:54
2023-03-09T03:17:55.301+0800	INFO

**Comment by lhy1024** [comment]
it should be only affected the master branch after #6046, I will Investigate it

**Comment by rleungx** [comment]
@lhy1024 Please add more detailed information about it when you close an issue. What is the root cause?

**Comment by lhy1024** [comment]
> @lhy1024 Please add more detailed information about it when you close an issue. What is the root cause?

Just revert this behavior and test it some times.

In https://github.com/tikv/pd/pull/6046, I use multi endpoint to connect etcd, but its keepalive only detect network rather than leader healthy, so when meet pd leader io hang, the connect cannot update.
