### ISSUE TITLE
pd leader is not balance when dr-auto-sync is enabled

### ISSUE THREAD

**Issue by glorv** [tikv/pd#6195]
### What did you do?
Deploy a pd cluster with the recommanded topology of dr-auto-sync and enable dr-auto-sync. 
The placement-rules is:
```
[
  {
    "group_id": "pd",
    "group_index": 0,
    "group_override": false,
    "rules": [
      {
        "group_id": "pd",
        "id": "lg1",
        "start_key": "",
        "end_key": "",
        "role": "voter",
        "count": 1,
        "location_labels": ["dc", "logic", "host"],
        "label_constraints": [{"key": "logic", "op": "in", "values": ["lg1"]}]
      },
      {
        "group_id": "pd",
        "id": "lg2",
        "start_key": "",
        "end_key": "",
        "role": "voter",
        "count": 1,
        "location_labels": ["dc", "logic", "host"],
        "label_constraints": [{"key": "logic", "op": "in", "values": ["lg2"]}]
      },
      {
        "group_id": "pd",
        "id": "lg3",
        "start_key": "",
        "end_key": "",
        "role": "voter",
        "count": 1,
        "location_labels": ["dc", "logic", "host"],
        "label_constraints": [{"key": "logic", "op": "in", "values": ["lg3"]}]
      },
      {
        "group_id": "pd",
        "id": "lg4",
        "start_key": "",
        "end_key": "",
        "role": "learner",
        "count": 1,
        "location_labels": ["dc", "logic", "host"],
        "label_constraints": [{"key": "logic", "op": "in", "values": ["lg4"]}]
      }
    ]
  }
]
```

### What did you expect to see?
After the cluster is inited, all leaders should be balance across all primary stores.

### What did you see instead?
The leader is not balanced.

### What version of PD are you using (`pd-server -V`)?
v6.5.0

![a295f3ed-ce04-405a-9355-8443a941ae1e](https://user-images.githubusercontent.com/5196885/226531925-e264cdef-948d-4f53-8e87-6062e1908de6.jpeg)
![321f39d1-c580-42d8-986e-11bdba4c6eb0](https://user-images.githubusercontent.com/5196885/226531931-979cfae7-304d-4d67-acdf-16d05eba00aa.jpeg)

The MatchLabelsConstrains is not correct for transfer-leader-operator.

**Comment by bufferflies** [comment]
yes, the replace should support the exchange peer if their's rule role is same.
