### ISSUE TITLE
TestExpireRegionCache seems to have random failure

### ISSUE THREAD

**Issue by binshi-bing** [tikv/pd#6256]
### Which jobs are failing
--- FAIL: TestExpireRegionCache (0.07s)
    cache_test.go:95: 
        	Error Trace:	/home/runner/work/pd/pd/pkg/cache/cache_test.go:95
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 3
        	Test:       	TestExpireRegionCache
FAIL
	github.com/tikv/pd/pkg/btree	coverage: 22.4% of statements in ./...
	github.com/tikv/pd/pkg/cache	coverage: 69.2% of statements in ./...
	github.com/tikv/pd/pkg/errs	coverage: 0.0% of statements in ./...
	github.com/tikv/pd/pkg/utils/logutil	coverage: 6.1% of statements in ./...
	github.com/tikv/pd/pkg/utils/syncutil	coverage: 0.0% of statements in ./...
FAIL	github.com/tikv/pd/pkg/cache	0.102s
ok  	github.com/tikv/pd/pkg/gctuner	0.070s	coverage: 1.4% of statements in ./...
ok  	github.com/tikv/pd/pkg/schedule	[31](https://github.com/tikv/pd/actions/runs/4591744836/jobs/8108176729?pr=6247#step:5:32)2.500s	coverage: [no statements]
FAIL
make: *** [Makefile:218: ci-test-job] Error 1
Error: Process completed with exit code 2.

### CI link
https://github.com/tikv/pd/actions/runs/4591744836/jobs/8108176729?pr=6247

**Comment by rleungx** [comment]
Duplicated with #6363.
