### ISSUE TITLE
qps drop 70% during pd leader io hang with error code 8027

### ISSUE THREAD

**Issue by Lily2025** [tikv/pd#6291]
### What did you do?
1、deploy ticdc and create changefeed
2、run tpcc with 1000 warehouse，10 thread
3、inject pd leader io hang last for 10mins
![image](https://github.com/tikv/pd/assets/84712107/8b232d4b-0e20-49c6-b273-03738e0922b6)

### What did you expect to see?
qps can recover within 2min

### What did you see instead?
qpd drop 70% during pd leader io hang
![12f5f6a6-0c17-49d5-91ed-39aba344ecfa](https://user-images.githubusercontent.com/84712107/230815605-31a21f0e-00a8-437f-8945-9a68cc9fd1c6.jpeg)

### What version of PD are you using (`pd-server -V`)?
git hash：2f0229f7556e1db1171251229233568f99a2e4b6
./pd-server -V
 Release Version: v7.1.0-alpha
Edition: Community
Git Commit Hash: 2f0229f7556e1db1171251229233568f99a2e4b6
Git Branch: heads/refs/tags/v7.1.0-alpha
UTC Build Time:  2023-04-07 11:32:34

**Comment by Lily2025** [comment]
can not reproduce

**Comment by Lily2025** [comment]
can not reproduce

**Comment by lhy1024** [comment]
> this phenomenon appeared at least 3 times on 7.3.0

 it high probability occurrence with ticdc enable and report 8027 error in tidb

**Comment by lhy1024** [comment]
similiar test https://github.com/pingcap/tidb/issues/44920#issuecomment-1606522523

**Comment by JmPotato** [comment]
Fixed by #7737.

**Comment by lhy1024** [comment]
> Fixed by #7737.

Do we need to add some tests that are similiar to https://github.com/pingcap/tidb/issues/44920#issuecomment-1606522523?
