### ISSUE TITLE
schedule: unexpect merge operator canceled with "remove operator because region disappeared"

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#6323]
### What did you expect to see?

merge success

### What did you see instead?

1. add operator  {merge: region 447369 to 5286955}
{"level":"INFO","time":"2023/04/12 02:11:08.152 +00:00","caller":"operator_controller.go:452","message":"add operator","region-id":447369,"operator":"merge-region {merge: region 447369 to 5286955} (kind:merge,region,leader, region:447369(1737, 161), createAt:2023-04-12 02:11:08.152731644 +0000 UTC m=+41445.894709620, startAt:0001-01-01 00:00:00 +0000 UTC, currentStep:0, size:13, steps:[add learner peer 6555630 on store 13, add learner peer 6555631 on store 213, add learner peer 6555632 on store 218, use joint consensus, promote learner peer 6555630 on store 13 to voter, promote learner peer 6555631 on store 213 to voter, promote learner peer 6555632 on store 218 to voter, demote voter peer 447370 on store 211 to learner, demote voter peer 447372 on store 216 to learner, demote voter peer 447371 on store 239 to learner, transfer leader from store 211 to store 13, leave joint state, promote learner peer 6555630 on store 13 to voter, promote learner peer 6555631 on store 213 to voter, promote learner peer 6555632 on store 218 to voter, demote voter peer 447370 on store 211 to learner, demote voter peer 447372 on store 216 to learner, demote voter peer 447371 on store 239 to learner, remove peer on store 211, remove peer on store 216, remove peer on store 239, merge region 447369 into region 5286955]，timeout:[58m0s])","additional-info":""}

{"level":"INFO","time":"2023/04/12 02:11:08.153 +00:00","caller":"operator_controller.go:452","message":"add operator","region-id":5286955,"operator":"merge-region {merge: region 447369 to 5286955} (kind:merge,region,leader, region:5286955(1737, 179), createAt:2023-04-12 02:11:08.152732467 +0000 UTC m=+41445.894710354, startAt:0001-01-01 00:00:00 +0000 UTC, currentStep:0, size:100, steps:[merge region 447369 into region 5286955]，timeout:[58m0s])","additional-info":""}

2. operator finish in 5286955

{"level":"INFO","time":"2023/04/12 02:21:37.907 +00:00","caller":"operator_controller.go:565","message":"operator finish","region-id":5286955,"takes":"10m29.754260903s",
"operator":"merge-region {merge: region 447369 to 5286955} (kind:merge,region,leader, region:5286955(1737, 179), createAt:2023-04-12 02:11:08.152732467 +0000 UTC m=+41445.894710354, startAt:2023-04-12 02:11:08.153253469 +0000 UTC m=+41445.895231368, currentStep:1, size:100, steps:[merge region 447369 into region 5286955]，timeout:[58m0s]) finished","additional-info":""}
finished","additional-info":""}

4. operator cancel in 447369 unexpectly.

{"level":"WARN","time":"2023/04/12 02:21:38.771 +00:00","caller":"operator_controller.go:221","message":"remove operator because region disappeared","region-id":447369,
"operator":"merge-region {merge: region 447369 to 5286955} (kind:merge,region,leader, region:447369(1737, 161), createAt:2023-04-12 02:11:08.152731644 +0000 UTC m=+41445.894709620, startAt:2023-04-12 02:11:08.152814835 +0000 UTC m=+41445.894792734, currentStep:9, size:13, steps:[add learner peer 6555630 on store 13, add learner peer 6555631 on store 213, add learner peer 6555632 on store 218, use joint consensus, promote learner peer 6555630 on store 13 to voter, promote learner peer 6555631 on store 213 to voter, promote learner peer 6555632 on store 218 to voter, demote voter peer 447370 on store 211 to learner, demote voter peer 447372 on store 216 to learner, demote voter peer 447371 on store 239 to learner, transfer leader from store 211 to store 13, leave joint state, promote learner peer 6555630 on store 13 to voter, promote learner peer 6555631 on store 213 to voter, promote learner peer 6555632 on store 218 to voter, demote voter peer 447370 on store 211 to learner, demote voter peer 447372 on store 216 to learner, demote voter peer 447371 on store 239 to learner, remove peer on store 211, remove peer on store 216, remove peer on store 239, merge region 447369 into region 5286955]，timeout:[58m0s])"}

{"level":"INFO","time":"2023/04/12 02:21:38.771 +00:00","caller":"operator_controller.go:603","message":"operator canceled","region-id":447369,
"takes":"10m30.619180177s","operator":"merge-region {merge: region 447369 to 5286955} (kind:merge,region,leader, region:447369(1737, 161), createAt:2023-04-12 02:11:08.152731644 +0000 UTC m=+41445.894709620, startAt:2023-04-12 02:11:08.152814835 +0000 UTC m=+41445.894792734, currentStep:9, size:13, steps:[add learner peer 6555630 on store 13, add learner peer 6555631 on store 213, add learner peer 6555632 on store 218, use joint consensus, promote learner peer 6555630 on store 13 to voter, promote learner peer 6555631 on store 213 to voter, promote learner peer 6555632 on store 218 to voter, demote voter peer 447370 on store 211 to learner, demote voter peer 447372 on store 216 to learner, demote voter peer 447371 on store 239 to learner, transfer leader from store 211 to store 13, leave joint state, promote learner peer 6555630 on store 13 to voter, promote learner peer 6555631 on store 213 to voter, promote learner peer 6555632 on store 218 to voter, demote voter peer 447370 on store 211 to learner, demote voter peer 447372 on store 216 to learner, demote voter peer 447371 on store 239 to learner, remove peer on store 211, remove peer on store 216, remove peer on store 239, merge region 447369 into region 5286955]，timeout:[58m0s])","additional-info":""}

### What version of PD are you using (`pd-server -V`)?
7.0.0

**Comment by rleungx** [comment]
See https://github.com/tikv/pd/issues/3569

**Comment by lhy1024** [comment]
maybe we should not use warning log for merge?

**Comment by lhy1024** [comment]
close by https://github.com/tikv/pd/pull/6673
