### ISSUE TITLE
TestExpireRegionCache isn't stable

### ISSUE THREAD

**Issue by binshi-bing** [tikv/pd#6363]
### Which jobs are failing
--- FAIL: TestExpireRegionCache (0.07s)
    cache_test.go:95: 
        	Error Trace:	/home/runner/work/pd/pd/pkg/cache/cache_test.go:95
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 3
        	Test:       	TestExpireRegionCache

### CI link
https://github.com/tikv/pd/actions/runs/4777183939/jobs/8492711583?pr=6362

**Comment by lhy1024** [comment]
https://github.com/tikv/pd/actions/runs/6001207070/job/16274881220 again
