### ISSUE TITLE
Region Health panel missing data if PD suffers from leader transfer

### ISSUE THREAD

**Issue by iosmanthus** [tikv/pd#6366]
### What did you do?

```bash
# create a 3-PD cluster
> curl -s http://<leader>/metrics | grep empty-region-count
pd_regions_status{type="empty-region-count"} 14
> pd-ctl member leader transfer <another-leader>
> pd-ctl member leader transfer <leader>
> curl -s http://<leader>/metrics | grep empty-region-count
```

The last command outputs nothing, meaning the metrics are missing.

### What did you expect to see?
```
pd_regions_status{type="empty-region-count"} 14
```

### What did you see instead?

nothing

### What version of PD are you using (`pd-server -V`)?
[master](https://github.com/tikv/pd/commit/1b75108590defc74010fcba79fac6797db052962)

**Comment by rleungx** [comment]
introduced by https://github.com/tikv/pd/pull/5802
