### ISSUE TITLE
QPS drops to zero after isolating PD leader

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#6442]
### What did you do?

Just as the title says.

### What did you expect to see?

test pass

### What did you see instead?

<img width="1857" alt="Screenshot 2023-05-11 at 17 50 23" src="https://github.com/tikv/pd/assets/35896542/c7bff7db-8df5-4d19-a0c9-3bd62f513dd1">
<img width="1131" alt="Screenshot 2023-05-11 at 17 53 27" src="https://github.com/tikv/pd/assets/35896542/5c336cfa-455e-44f6-9d03-83cc4293dda0">
<img width="614" alt="Screenshot 2023-05-11 at 17 56 25" src="https://github.com/tikv/pd/assets/35896542/4ed89ada-20cd-4fad-8cd0-199de218eafb">
<img width="922" alt="Screenshot 2023-05-11 at 17 57 22" src="https://github.com/tikv/pd/assets/35896542/0f726646-481e-47d8-b19f-fbed9a00c900">

It seems that PD has already changed the leader.

### What version of PD are you using (`pd-server -V`)?
pd-cse

**Comment by lhy1024** [comment]
close by https://github.com/tikv/pd/pull/6577
