### ISSUE TITLE
QPS drops to zero after isolating PD leader in multiple keyspace groups environment

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#6537]
### What did you do?

Running HA tests and the case will isolate the PD leader for 10m with other components.

### What did you expect to see?

The QPS won't lose a lot.

### What did you see instead?

<img width="924" alt="Screenshot 2023-05-30 at 15 15 20" src="https://github.com/tikv/pd/assets/35896542/ed64b7dd-9056-4865-8ee4-e903f1c810b0">
<img width="1835" alt="Screenshot 2023-05-30 at 15 15 51" src="https://github.com/tikv/pd/assets/35896542/49530479-7307-4760-967c-dfbb23f8a599">
<img width="1511" alt="Screenshot 2023-05-30 at 15 30 23" src="https://github.com/tikv/pd/assets/35896542/b0da6638-054c-49e6-86f7-959232e745c2">

More details can be found at https://tcms.pingcap.net/dashboard/executions/plan/1802400

### What version of PD are you using (`pd-server -V`)?
master

**Comment by rleungx** [comment]
The root cause is the same as #6442. This issue needs to be verified after #6442 is resolved.

**Comment by nolouch** [comment]
duplicated

**Comment by lhy1024** [comment]
it is fixed by https://github.com/tikv/pd/pull/6577 cc @seiya-annie
