### ISSUE TITLE
[dr-autosync] pd in backup dc can't startup after force new cluster due to [PD:placement:ErrBuildRuleList]

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/pd#6570]
### What did you see instead?
```
[2023/06/07 21:12:26.165 +08:00] [ERROR] [server.go:1535] ["failed to create raft cluster"] [error="[PD:placement:ErrBuildRuleList]build rule list failed, needs at least one leader or voter for range {7480000000000000FF525F720000000000FA, 7480000000000000FF5300000000000000F8}"]
```

### What version of PD are you using (`pd-server -V`)?
sh-4.2# ./pd-server -V
Release Version: v6.5.3
Edition: Community
Git Commit Hash: 410b1767520b98f0285b2178eac90494aff2fc3a
Git Branch: heads/refs/tags/v6.5.3
UTC Build Time:  2023-06-06 07:04:46

**Comment by mayjiang0203** [comment]
didn't hit it with pd-recover 6.5.2 using, so close it, will reopen if hit it again.

**Comment by mayjiang0203** [comment]
hit it again with 6.5.2 pd-recover, so reopen it.
/severity critical

**Comment by nolouch** [comment]
It may be relative to the incorrect recovery steps.

**Comment by mayjiang0203** [comment]
/remove-severity critical
After adjusting the recover steps, didn't hit this issue again, so close it.
