### ISSUE TITLE
Merge operators better to be canceled together

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#6607]
## Enhancement Task
<img width="1913" alt="Screenshot 2023-06-14 at 16 38 25" src="https://github.com/tikv/pd/assets/35896542/a51d065e-c662-4ec6-8887-bb4b25bebfe0">
<img width="1912" alt="Screenshot 2023-06-14 at 16 58 49" src="https://github.com/tikv/pd/assets/35896542/9ccea478-d865-4ae7-a7aa-cfa313a5c84a">

At 05:51:30, PD creates two merge operators that are going to merge 515 and 127. But due to "cannot demote leader peer", the operator of 515 is canceled, and the operator of 127 still leaves which will continue sending merge region step to TiKV until timeout. It also affects the merge limit since it will occupy one before its timeout.

At 05:51:47, PD creates another two merge operators that are going to merge 515 and 079. This operation is successfully executed.

So we might find in TiKV, there are two different kinds of operators related to merge 515.

It's better to cancel two merge operators together so that they won't occupy the merge-schedule-limit and the merge checker will create the operators for them soon. Otherwise, it will block merge speed if the timeout is long.

**Comment by lhy1024** [comment]
is it similar to https://github.com/tikv/pd/issues/6323 ?

**Comment by rleungx** [comment]
> is it similar to #6323 ?

Yes.
