### ISSUE TITLE
TestEtcdScaleInAndOutWithoutMultiPoint "cannot fetch cluster info from peer urls"

### ISSUE THREAD

**Issue by binshi-bing** [tikv/pd#6615]
### Which jobs are failing
--- FAIL: TestEtcdScaleInAndOutWithoutMultiPoint (1.03s)
    etcdutil_test.go:381: 
                Error Trace:    /Users/binshi/code/pingcap/my-pd/pkg/utils/etcdutil/etcdutil_test.go:381
                                                        /Users/binshi/code/pingcap/my-pd/pkg/utils/etcdutil/etcdutil_test.go:320
                Error:          Received unexpected error:
                                cannot fetch cluster info from peer urls: could not retrieve cluster information from the given URLs
                Test:           TestEtcdScaleInAndOutWithoutMultiPoint

### CI link
make test under tikv/pd

### Reason for failure (if possible)
Unknown

**Comment by rleungx** [comment]
https://github.com/tikv/pd/actions/runs/6446012653/job/17500675414?pr=7163 seem the same problem

**Comment by rleungx** [comment]
This test does not exist, close it.
