### ISSUE TITLE
WatchKeyspaces in pd client is found unexpected goroutines on exit

### ISSUE THREAD

**Issue by binshi-bing** [tikv/pd#6631]
### Which jobs are failing
TestWatchKeyspaces in pd/tests/integrations/client/keyspace_test.go

goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 333950 in state chan send, with github.com/tikv/pd/client.(*client).WatchKeyspaces.func1 on top of the stack:
goroutine 333950 [chan send]:
github.com/tikv/pd/client.(*client).WatchKeyspaces.func1()
	/home/runner/work/pd/pd/client/keyspace_client.go:109 +0x147
created by github.com/tikv/pd/client.(*client).WatchKeyspaces
	/home/runner/work/pd/pd/client/keyspace_client.go:92 +0x35d

]
FAIL	github.com/tikv/pd/tests/integrations/client	213.604s
FAIL
make[1]: Leaving directory '/home/runner/work/pd/pd/tests/integrations/client'
Error: Process completed with exit code 2.

### CI link
https://github.com/tikv/pd/actions/runs/5281557806/jobs/9555307660?pr=6614

### Reason for failure (if possible)
no sync up

**Comment by lhy1024** [comment]
I also meet https://github.com/tikv/pd/actions/runs/5318919915/jobs/9630853126?pr=6626

**Comment by rleungx** [comment]
Does it still exist? @lhy1024

**Comment by lhy1024** [comment]
> Does it still exist? @lhy1024

I did not meet it again, but I am not sure whether it still exists.

**Comment by binshi-bing** [comment]
@rleungx @lhy1024 , if my memory serves me correctly, the bug was found in pse, and it has been fixed in tikv/pd main.

**Comment by rleungx** [comment]
> @rleungx @lhy1024 , if my memory serves me correctly, the bug was found in pse, and it has been fixed in tikv/pd main.

Thx! According to the comment, I'm going to close it for now. Once it happens again, feel free to reopen it.
