### ISSUE TITLE
rule-checker does not consider the engine label constraint

### ISSUE THREAD

**Issue by JmPotato** [tikv/pd#6662]
## Bug Report

https://github.com/tikv/pd/pull/6633 broke the constrain that we can only move peer between the stores that satisfy the rule, as a result, `rule-checker` will move the learner peer away to a TiKV store while keep adding rule peer in the TiFlash stores. This will cause a TiFlash replica of a region never to be replicated well while bringing many redundant replicas to other TiKV nodes.

![b4e2acdf-68ad-42b4-86e8-540e759e45b9](https://github.com/tikv/pd/assets/1446531/05bee30b-ccc8-4c28-b8ee-3cb383ca947a)

In monitoring, its phenomenon may be as shown in the figure above, with a large number of `add-rule-peer` and `move-to-better-location` at the same time. And in the log, you can see that the two act in the same region successively.

**Comment by rleungx** [comment]
We don't need to pick this fix to release-6.5 since it doesn't support survival preference in the placement rule in SQL.
