### ISSUE TITLE
TestMemberTestSuite failed because of data race

### ISSUE THREAD

**Issue by TonsnakeLin** [tikv/pd#6668]
### What did you do?

run unit test case `TestMemberTestSuite` with race.

### What did you expect to see?
It runs successfully.

### What did you see instead?
![img_v2_3e026176-3957-4011-b960-0a47d1fb8c5g](https://github.com/tikv/pd/assets/87681388/92bf891e-5b6a-40e1-84ab-dd29c9c9650a)
It appears occasionally.

### What version of PD are you using (`pd-server -V`)?
V6.5.3

**Comment by TonsnakeLin** [comment]
The race generated when initializeing tsoAllocator failed at `(3)` bellow. At this moment, `am.ResetAllocatorGroup` at `(1)` will read the variable `Leadership.keepAliveCancelFunc` and ` allocator.KeepAllocatorLeader` will write the variable `Leadership.keepAliveCancelFunc` concurrently, the race is generated.

func (am *AllocatorManager) campaignAllocatorLeader(
	loopCtx context.Context,
	allocator *LocalTSOAllocator,
	dcLocationInfo *pdpb.GetDCLocationInfoResponse,
	isNextLeader bool,
) {
	defer am.ResetAllocatorGroup(allocator.GetDCLocation())         // (1)
	// Maintain the Local TSO Allocator leader
	go allocator.KeepAllocatorLeader(ctx)                                        // (2)

	if err := allocator.Initialize(int(dcLocationInfo.Suffix)); err != nil {  // (3)
            ...
            return
        }
        ...
}

This issue will leads to panic or leak goroutines after starting pd-server.

How to fix? We should initialize the tsoAllocator when `KeepAllocatorLeader` goroutine has been started.

**Comment by lhy1024** [comment]
It has been fixed by #6636, I will pick it to oldder version https://github.com/tikv/pd/pull/6701 https://github.com/tikv/pd/pull/6702 https://github.com/tikv/pd/pull/6703 https://github.com/tikv/pd/pull/6704
