### ISSUE TITLE
mcs, tso: can't access tso pprof in dev env

### ISSUE THREAD

**Issue by binshi-bing** [tikv/pd#6682]
## Enhancement Task
 ~  kubectl exec -it pd-tso-server-0 -n tidb-serverless -- bash                                                                           ✔  11781  12:45:26
root@pd-tso-server-0:/# curl http://localhost:2379/debug/pprof/goroutine?debug=2
curl: (7) Failed to connect to localhost port 2379: Connection refused
root@pd-tso-server-0:/# curl http://localhost:2380/debug/pprof/goroutine?debug=2
curl: (7) Failed to connect to localhost port 2380: Connection refused

 ~  kubectl port-forward pd-tso-server-0 2379:2379                                                                             1 ↵  11091  09:27:43
Forwarding from 127.0.0.1:2379 -> 2379
Forwarding from [::1]:2379 -> 2379
Handling connection for 2379
Handling connection for 2379

open http://localhost:2379/debug/pprof/ in browser on local laptop.

E0626 12:46:08.874911   66533 portforward.go:409] an error occurred forwarding 2379 -> 2379: error forwarding port 2379 to pod 451de37f300b37dd06e76a3098c8766b5a4f5f1b2d77ba30a2e71cb259a5689b, uid : failed to execute portforward in network namespace "/var/run/netns/cni-2027437f-dbe6-68cd-dcc2-da07710cc114": failed to connect to localhost:2379 inside namespace "451de37f300b37dd06e76a3098c8766b5a4f5f1b2d77ba30a2e71cb259a5689b", IPv4: dial tcp4 127.0.0.1:2379: connect: connection refused IPv6 dial tcp6: address localhost: no suitable address found
E0626 12:46:08.875397   66533 portforward.go:409] an error occurred forwarding 2379 -> 2379: error forwarding port 2379 to pod 451de37f300b37dd06e76a3098c8766b5a4f5f1b2d77ba30a2e71cb259a5689b, uid : failed to execute portforward in network namespace "/var/run/netns/cni-2027437f-dbe6-68cd-dcc2-da07710cc114": failed to connect to localhost:2379 inside namespace "451de37f300b37dd06e76a3098c8766b5a4f5f1b2d77ba30a2e71cb259a5689b", IPv4: dial tcp4 127.0.0.1:2379: connect: connection refused IPv6 dial tcp6: address localhost: no suitable address found
error: lost connection to pod

**Comment by binshi-bing** [comment]
kubectl describe po pd-tso-server-0  
https://gist.githubusercontent.com/binshi-bing/033aba720bd38b218bcb7ed7ea3f074c/raw/6ae8f3ee987ae7609cdf4cd524373ab52acec393/kubectl%2520describe%2520pod%2520pd-tso-server-0

**Comment by rleungx** [comment]
I think the feature works fine but there are some environmental issues which prevents us access localhost.
