### ISSUE TITLE
Split state cannot recover if there is no request

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#6696]
## Enhancement
If the split target group doesn't receive the request, it will stay in the split state, which cannot be selected as the split source.

**Comment by lhy1024** [comment]
[tso-0.log](https://gist.github.com/lhy1024/11130198cedfc55d316dd7182266907e)
[tso-1.log](https://gist.github.com/lhy1024/e57562eae98c2e9c60bbf516b4a7cc4c)
