### ISSUE TITLE
Frequently new a timer may cost too much memory

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#6719]
## Enhancement Task
After we upgrade, PD consumes more memory compared to before.
<img width="1440" alt="ePWuRRzpCj" src="https://github.com/tikv/pd/assets/35896542/e0332c70-a1fe-4214-918b-217462fa4012">
For each request, we will create a deadline that contains a timer. We should improve it in this kind of situation.

**Comment by lhy1024** [comment]
Besides TSDeadline, time.After also cost too much memory
![image](https://github.com/tikv/pd/assets/19542290/2ab238a5-5a83-4e39-842e-daaad1b33d3a)

It is unrecommended to use time.After in for-select
