### ISSUE TITLE
Dashboard : common.bad_request isn't meaningful

### ISSUE THREAD

**Issue by jansu-dev** [tikv/pd#6729]
## Enhancement Task

when customer uses dashboard to export `slow.log` or `tidb.log`. This error named common.bad_request isn't meaningful.
I'm gonna list two scenarios I met to show why
![image](https://github.com/tikv/pd/assets/76909042/719d60fe-ab51-4689-8f1c-c45e2e9d4d13)

1. Dump slow queries failed because of priv limit.
![image](https://github.com/tikv/pd/assets/76909042/b3f0ec88-0734-414b-a846-24b841a8a810)

2. Slow query download from the TiDB dashboard was failing due to OOM at tidb server, customer had to increase `tidb_mem_quota_query` for the download worked.
More info : https://pingcap.zendesk.com/agent/tickets/1910

Please let this error more understandable, thx!

**Comment by rleungx** [comment]
Do we need to move it to tidb-dashboard repo?

**Comment by jansu-dev** [comment]
> @jansu-dev Do we need to move it to tidb-dashboard repo?

Sure, I create another one there. https://github.com/pingcap/tidb-dashboard/issues/1553
If it should be processed in tidb-dashboard repo, you can directly close this one.
