### ISSUE TITLE
mcs: WatchKeyspaces cost a lot of memory

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#6737]
## Enhancement Task
![img_v2_241fffd1-4829-4db0-97e1-9a65b251c17g](https://github.com/tikv/pd/assets/19542290/c309b0d8-f6cb-47be-8b4a-26b1d0fab0a7)

every client call WatchKeyspaces to maintain a watch-loop, but tidb only need to get all keyspace.
```
func (s *KeyspaceServer) WatchKeyspaces(request *keyspacepb.WatchKeyspacesRequest, stream keyspacepb.Keyspace_WatchKeyspacesServer) error {
    .....
    go watcher.StartWatchLoop()
    if err := watcher.WaitLoad(); err != nil {
        cancel() // cancel context to stop watcher
        return err
    }
    <-ctx.Done() // wait for context done
    return nil
}
```
```
func (w *GCWorker) getAllKeyspace(ctx context.Context) []*keyspacepb.KeyspaceMeta {
    ctx, cancel := context.WithCancel(context.Background())
    defer cancel()
    watchChan, err := w.pdClient.WatchKeyspaces(ctx)
    if err != nil {
        logutil.Logger(ctx).Error("WatchKeyspaces error")
    }
    initialLoaded := <-watchChan
    return initialLoaded
}
```

I think we only provide `GetAllKeyspace` in client is enough and maintain only one watch-loop in server
And we also can LoadKeyspace by this server watch-loop and avoid to unnecessary load by etcd.

**Comment by binshi-bing** [comment]
duplicate with https://github.com/tikv/pd/issues/6733
