### ISSUE TITLE
pd-recover and jq are not included in the pd docker image

### ISSUE THREAD

**Issue by Jy-poi** [tikv/pd#6842]
### What did you do?

I found there are no pd-recover and jq binary in the offical pd docker image(https://hub.docker.com/r/pingcap/pd).
I already tested in pingcap/pd:v6.1.0 and pingcap/pd:latest.

But I build the pd docker image myself on tag v6.1.0，it has pd-recover and jq. 
Is there some problem with the offical images？

Related issue: https://github.com/tikv/pd/issues/2402

### What did you expect to see?
There are pd-recover and jq in the pd container

### What did you see instead?

pd-recover and jq are not in the pd container

### What version of PD are you using (`pd-server -V`)?
Release Version: v6.1.0
Edition: Community
Git Commit Hash: d82f4fab6cf37cd1eca9c3574984e12a7ae27c42
Git Branch: heads/refs/tags/v6.1.0
UTC Build Time:  2022-06-01 01:44:08

**Comment by CabinfeverB** [comment]
Now we don't push jq and pd-recover to the offical pd docker image in our script. In https://docs.pingcap.com/tidb-in-kubernetes/stable/pd-recover, It mentions that you must download pd-recover.
I will try to resolve this problem.

**Comment by Jy-poi** [comment]
Ok，I know.
