### ISSUE TITLE
There are too many `/stats/region` audit records in log

### ISSUE THREAD

**Issue by CabinfeverB** [tikv/pd#6900]
## Enhancement Task
Because of  `/stats/region` called for updating TiFlash replica progress of one table/partition, there are too many `/stats/region` audit records in log.

**Comment by rleungx** [comment]
![Uploading Screenshot 2023-08-07 at 16.17.33.png…]()

**Comment by CabinfeverB** [comment]
<img width="1510" alt="img_v2_76b9f94d-0434-4e21-8e30-b7c9a42504eg" src="https://github.com/tikv/pd/assets/23399268/e70ac35d-3ccc-401e-b441-ecf90d9af301">

**Comment by rleungx** [comment]
Close it since the PR is merged.
