### ISSUE TITLE
Port is not truncated correctly when getting IP from HTTP request 

### ISSUE THREAD

**Issue by JmPotato** [tikv/pd#6957]
## Bug Report

#6622 added `X-Forwarded-For` into the header for the forwarded request. However, `GetIPAddrFromHTTPRequest` directly returns the IP address from `X-Forwarded-For` without truncating the port as handling `X-Real-Ip` down below.

https://github.com/tikv/pd/blob/54981d1b89563547e321dbfcee24edef8a6c7a1c/pkg/utils/apiutil/apiutil.go#L104-L124

When the forwarded request uses a random port and the QPS is high, the metrics may record a large number of records, which affects indicator observation or downstream monitoring services.

![img_v2_876bd46c-4f4b-40fa-8ed0-e2638bf1571g](https://github.com/tikv/pd/assets/1446531/8b1712a2-145f-44b0-ad4b-e7de3d301b5e)

**Comment by JasonWu0506** [comment]
@JmPotato can you please confirm this really affect 6.5 and 7.1? the PR is merged on Jun 20, which had passed the CF of version 7.2. my understanding is that it will affect master and 7.3 release?

**Comment by JmPotato** [comment]
> @JmPotato can you please confirm this really affect 6.5 and 7.1? the PR is merged on Jun 20, which had passed the CF of version 7.2. my understanding is that it will affect master and 7.3 release?

After checking, I'm sure that this bug only affects version 7.3 at present.
