### ISSUE TITLE
dashboard: fix export statement failed issue and support config ngm timeout param

### ISSUE THREAD

**Issue by baurine** [tikv/pd#6966]
## Development Task

Related tidb-dashboard release: https://github.com/pingcap/tidb-dashboard/pull/1572

**Comment by baurine** [comment]
affect 7.1, 6.5, 6.1

**Comment by HuSharp** [comment]
@baurine Do you need to update 7.1 & 6.1 as well?

**Comment by baurine** [comment]
This issue is fixed in the release-6.5 and master branch, so close it. Will continue to push the PR merge in the release-7.1 and release-6.1
