### ISSUE TITLE
pd scheduler do not resume after lightning finished when rolling restarting pd during lightning importing

### ISSUE THREAD

**Issue by Lily2025** [tikv/pd#6981]
### What did you do?
1、lightning importing
2、rolling restart pd

### What did you expect to see?
pd scheduler can resume after lightning finished

### What did you see instead?
pd scheduler do not resume after lightning finished
![image](https://github.com/tikv/pd/assets/84712107/d8cbc935-4fd3-437f-942a-773dc1f4a48a)

![image](https://github.com/tikv/pd/assets/84712107/db160deb-741e-48c8-8101-b9f0d456a643)

### What version of PD are you using (`pd-server -V`)?
./pd-server -V
 Release Version: v7.4.0-alpha
Edition: Community
Git Commit Hash: 497c9420668e2a94f341f0c1d360d01058f99393
Git Branch: heads/refs/tags/v7.4.0-alpha
UTC Build Time:  2023-08-22 11:36:19
2023-08-23T14:59:33.891+0800    INFO    k8s/client.go:132       it should be noted that a long-running command will not be
interrupted even the use case has ended. For more information, please refer to https://github.com/pingcap/test-infra/discus
sions/129

**Comment by CabinfeverB** [comment]
Maybe introduced by https://github.com/tikv/pd/pull/6945.
I reproduce this situation and print log:
![image](https://github.com/tikv/pd/assets/23399268/6ee30456-8a71-46c1-b3b0-3e610ac6e8d6)
![image](https://github.com/tikv/pd/assets/23399268/34a9f4cc-c13c-4d5a-9a20-451f304ece01)

**Comment by LykxSassinator** [comment]
> Maybe introduced by #6945. I reproduce this situation and print log: ![image](https://user-images.githubusercontent.com/23399268/262894178-6ee30456-8a71-46c1-b3b0-3e610ac6e8d6.png) ![image](https://user-images.githubusercontent.com/23399268/262894237-34a9f4cc-c13c-4d5a-9a20-451f304ece01.png)

Yep, it's caused by this https://github.com/tikv/pd/pull/6945, and the root cause is that when restarting the `Sync` status will not be set as the StoreConfig is old. And this makes it `false` forever after restarting the PD rather than creating a new one.

**Comment by LykxSassinator** [comment]
I'll fix it right now. Thx @CabinfeverB
