### ISSUE TITLE
Enhance the TSO server metrics

### ISSUE THREAD

**Issue by JmPotato** [tikv/pd#7011]
Part of #5895

## Enhancement Task

Currently, we have basically finished the development of the multi-tenant TSO service. Now is an excellent time to improve the observability of it. We may still need to introduce a lot of metrics to help us monitor the keyspace group and TSO-related indicators.

- [x] https://github.com/tikv/pd/pull/7012
- [x] https://github.com/tikv/pd/pull/7022
- [x] https://github.com/tikv/pd/pull/7040

**Comment by rleungx** [comment]
Is it finished now?
