### ISSUE TITLE
tests: `TestBalanceRegion` is unstable 

### ISSUE THREAD

**Issue by bufferflies** [tikv/pd#7037]
## Enhancement Task
link: https://pipelines.actions.githubusercontent.com/serviceHosts/346062d3-0b0d-46c0-8280-f67b19c8c7ca/_apis/pipelines/1/runs/68438/signedlogcontent/2?urlExpires=2023-09-04T07%3A03%3A32.6352950Z&urlSigningMethod=HMACV1&urlSignature=jlE89e0lKQNCixY5Ti3cF7oGxsC4zgCeU3JqEyRmHUU%3D

<img width="1067" alt="image" src="https://github.com/tikv/pd/assets/23159587/e1e9d2b7-1e73-4b0e-8cd8-17508da55999">

**Comment by lhy1024** [comment]
close by #7036
