### ISSUE TITLE
Witness related rules doesn't support LocationLabels very well

### ISSUE THREAD

**Issue by Yriuns** [tikv/pd#7088]
## Bug Report

I know the witness feature is not finished yet, but it seems that current implementation can not support LocationLabels very well.

### What did you do?

Write a unit test under `rule_checker_test.go`

We just add 3 zones and 5 stores. Then we add 1 peer at z1 and 1 peer at z2.

```go
func (suite *ruleCheckerTestSuite) TestAddWitness() {
	suite.cluster.SetEnableUseJointConsensus(false)
	suite.cluster.AddLabelsStore(1, 1, map[string]string{"zone": "z1", "host": "h11"})
	suite.cluster.AddLabelsStore(2, 1, map[string]string{"zone": "z2", "host": "h21"})
	suite.cluster.AddLabelsStore(3, 1, map[string]string{"zone": "z3", "host": "h31"})
	suite.cluster.AddLabelsStore(4, 1, map[string]string{"zone": "z1", "host": "h12"})
	suite.cluster.AddLabelsStore(5, 1, map[string]string{"zone": "z2", "host": "h22"})

	err := suite.ruleManager.SetRules([]*placement.Rule{
		{
			GroupID:        "pd",
			ID:             "default",
			Index:          100,
			Role:           placement.Voter,
			IsWitness:      false,
			Count:          2,
			LocationLabels: []string{"zone", "host"},
		},
		{
			GroupID:        "pd",
			ID:             "witness",
			Index:          100,
			Role:           placement.Voter,
			IsWitness:      true,
			Count:          1,
			LocationLabels: []string{"zone", "host"},
		},
	})
	suite.Nil(err)
	// add a region that missing a witness
	suite.cluster.AddLeaderRegion(1, 1, 2)
	r := suite.cluster.GetRegion(1)
	for i := 0; i < 100; i++ {
		op := suite.rc.Check(r)
		suite.NotNil(op)
		suite.Equal(uint64(3), op.Step(0).(operator.AddLearner).ToStore)
	}
}
```

### What did you expect to see?

We expect that the rule checker will always add a witness at store3@z3.

### What did you see instead?

Sometimes, it may choose store at store4@z1 or store5@z2.

I know the behavior of placement rule here is correct, but it seems hard to use the witness feature.
I thought we can replace the `IsWitness bool` field with `WitnessCount int`, so that two rules can be reduced to one like
```go
{
	GroupID:        "pd",
	ID:             "default",
	Index:          100,
	Role:           placement.Voter,
	Count:          2,
        WitnessCount:   1,
	LocationLabels: []string{"zone", "host"},
}
```

### What version of PD are you using (`pd-server -V`)?
master d0cebac09f2967348578b5159d3436f74dd92266

**Comment by Yriuns** [comment]
@ethercflow I'm sorry for bothering, but could you please take a look?

**Comment by Yriuns** [comment]
@Connor1996 would you please take a look?

**Comment by Connor1996** [comment]
The behavior is unexpected. The change looks good to me. But the development of witness feature is paused currently, the change of placement rule may introduce the compatiblity issue. So I don't suggest to change it. Can we change the placement rule logic to make the behavior correct?

**Comment by Yriuns** [comment]
> The behavior is unexpected. The change looks good to me. But the development of witness feature is paused currently, the change of placement rule may introduce the compatiblity issue. So I don't suggest to change it. Can we change the placement rule logic to make the behavior correct?

Thank you for your reply! Now that witness feature has not been released, there should not be comparability issue?

But for your suggestion, maybe we can add a group level location label.

**Comment by Connor1996** [comment]
The proto has been changed no matter whether it's released. Of course we can add one more field in the proto, but I don't want to as the feature is paused.

**Comment by Yriuns** [comment]
> The proto has been changed no matter whether it's released. Of course we can add one more field in the proto, but I don't want to as the feature is paused.

I see. But it seems that the proto of a `rule` is used in pd only(actually HTTP json API), is it acceptable to change it before it's released?

btw, may I asked why it is paused? This feature looks very useful.

**Comment by Connor1996** [comment]
I'm not sure if the `placement.Rule` proto would be persisted? /cc @rleungx If not, I'm fine to change it.

It's paused due to some architecture strategy change on the cloud, so it's not necessary for TiKV.

**Comment by Yriuns** [comment]
> I'm not sure if the `placement.Rule` proto would be persisted? /cc @rleungx If not, I'm fine to change it.
> 
> It's paused due to some architecture strategy change on the cloud, so it's not necessary for TiKV.

Does "some architecture strategy" refer to [this article](https://zhuanlan.zhihu.com/p/642948394)? If so, it's indeed not necessary for TiKV.

**Comment by Connor1996** [comment]
Yes

**Comment by Yriuns** [comment]
> Yes

I see. I'll close it.
