### ISSUE TITLE
pd prometheus scrape cardinality issue on ip (reports ip:port)

### ISSUE THREAD

**Issue by donbowman** [tikv/pd#7168]
### What did you do?

We use prometheus in kubernetes. It scrapes pd/tikv/tidb. In the v7.3.0 upgrade, a new behaviour is introduced which blows up prometheus.
specifically, a pd_service_audit_handling_seconds_sum key has a label called ip, but the value is actually ip:port, meaning it has a near unlimited cardinality. This is in turn blowing up prometheus since it groups by this value.

### What did you expect to see?

ip=ipaddr

### What did you see instead?

ip=ipaddr:port

### What version of PD are you using (`pd-server -V`)?

v7.3.0
sh-5.1# /pd-server -V
Release Version: v7.3.0
Edition: Community
Git Commit Hash: 7cab1e942d08c24ff3dfdb1693ce5d93d908915f
Git Branch: heads/refs/tags/v7.3.0
UTC Build Time:  2023-08-01 07:32:06

**Comment by donbowman** [comment]
it doesn't do this on all scrape to /metrics. but suddenly it flips from ip=127.0.0.1 to ip=podip:port

```
pd_service_audit_handling_seconds_bucket{component="anonymous",ip="10.16.1.78:57880",method="HTTP",service="GetStoreMinResolvedTS",le="2.5"} 5
pd_service_audit_handling_seconds_bucket{component="anonymous",ip="10.16.1.78:57880",method="HTTP",service="GetStoreMinResolvedTS",le="5"} 5
pd_service_audit_handling_seconds_bucket{component="anonymous",ip="10.16.1.78:57880",method="HTTP",service="GetStoreMinResolvedTS",le="10"} 5
```

which has enormous cardinality. this is new in v7.3.0 i think.

**Comment by rleungx** [comment]
Is it the same problem as https://github.com/tikv/pd/issues/6957? It has already been fixed in the master branch and we will release a new version soon.

**Comment by donbowman** [comment]
yes it appears duplicate of #6957?

**Comment by donbowman** [comment]
yes it appears duplicate of https://github.com/tikv/pd/issues/6957?
