### ISSUE TITLE
remove legacy tokenSlot of resource group bucket

### ISSUE THREAD

**Issue by guo-shaoge** [tikv/pd#7346]
## Enhancement Task
Normally when node step out gracefully(got SIGTERM etc), it will send last acquire grpc, so PD will cleanup its slot token.

But when node crash unexpctedly or got SIGKILL(which cannot be handled), it will have no chance to send last acquire grpc, so its corresponding slot token will leave here forever, which makes fillrate/burstLimit be less.

**Comment by CabinfeverB** [comment]
IMO, the weight we use is a quadratic function, if the load gap between clients is too large, it will still give too much to the low-load client. 0 is a limiting case.
We can solve some problems with 7344 first, but there may still be problems with other scenarios.

**Comment by CabinfeverB** [comment]
after #7344, change it to minor
