### ISSUE TITLE
mcs: async evict-leader-scheduler config in api server

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#7388]
### What did you do?

add evict leader scheduler config and check it

### What did you expect to see?

It is synced

### What did you see instead?

It is async between memory and persist config in api server.

Of course, because scheduling server is sync with persist config, so the memory data in api server is different from scheduling server
![image](https://github.com/tikv/pd/assets/19542290/e0f79d6d-0bea-4514-a751-ef97e8890240)

**Comment by lhy1024** [comment]
It appears that there is a synchronization discrepancy between the API server and the scheduling server regarding the paused state of the store. During testing, we observed that the scheduling server reflects store 2 as being paused, whereas the API server indicates that store 3 is paused.

This misalignment may be attributed to a lack of initial configuration and cleanup, which has led to an inconsistency in the in-memory representation of the store's state on the API server when compared to the persisted configuration.

**Comment by rleungx** [comment]
Is it duplicated with https://github.com/tikv/pd/issues/7257?

**Comment by lhy1024** [comment]
> Is it duplicated with #7257?

#7388 is a part of #7257. There still be four tests that cannot run in API mode.
