### ISSUE TITLE
[v6.5.6] dashboard can't show disk info of PD 

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/pd#7579]
### What did you see instead?
![image](https://github.com/tikv/pd/assets/9443637/c11efa78-faa8-4184-ba68-c86f4ac6afb3)

### What version of PD are you using (`pd-server -V`)?
v6.5.6-fips

**Comment by CabinfeverB** [comment]
No need to upgrade sysutil.
This issue is caused by /var/lib/pd and /var/lib/pd-log being mounted to the same device and being filtered when tidb uses the JSON_OBJECTAGG function.
We need to decide whether this deployment is justified. The dashboard will fix it if needed.

**Comment by CabinfeverB** [comment]
this deployment is not justified
