### ISSUE TITLE
TestSchedulerDiagnostic is unstable

### ISSUE THREAD

**Issue by HuSharp** [tikv/pd#7609]
## Flaky Test
TestSchedulerTestSuite/TestSchedulerDiagnostic

### Which jobs are failing
```
    --- FAIL: TestSchedulerTestSuite/TestScheduler (44.04s)
        testutil.go:64: 
            	Error Trace:	/home/runner/work/pd/pd/pkg/utils/testutil/testutil.go:64
            	            				/home/runner/work/pd/pd/tests/pdctl/scheduler/scheduler_test.go:426
            	            				/home/runner/work/pd/pd/tests/pdctl/scheduler/scheduler_test.go:508
            	            				/home/runner/work/pd/pd/tests/testutil.go:309
            	            				/home/runner/work/pd/pd/tests/testutil.go:270
            	            				/home/runner/work/pd/pd/tests/pdctl/scheduler/scheduler_test.go:99
            	Error:      	Condition never satisfied
            	Test:       	TestSchedulerTestSuite/TestScheduler
    testutil.go:275: start test TestSchedulerDiagnostic in pd mode
    --- FAIL: TestSchedulerTestSuite/TestSchedulerDiagnostic (20.03s)
        testutil.go:64: 
            	Error Trace:	/home/runner/work/pd/pd/pkg/utils/testutil/testutil.go:64
            	            				/home/runner/work/pd/pd/tests/pdctl/scheduler/scheduler_test.go:644
            	            				/home/runner/work/pd/pd/tests/pdctl/scheduler/scheduler_test.go:681
            	            				/home/runner/work/pd/pd/tests/testutil.go:279
            	            				/home/runner/work/pd/pd/tests/testutil.go:269
            	            				/home/runner/work/pd/pd/tests/pdctl/scheduler/scheduler_test.go:634
            	Error:      	Condition never satisfied
            	Test:       	TestSchedulerTestSuite/TestSchedulerDiagnostic
```

### CI link
https://github.com/tikv/pd/actions/runs/7296294204/job/19883901919

**Comment by CabinfeverB** [comment]
https://github.com/tikv/pd/actions/runs/7353983679/job/20020647054?pr=7640

**Comment by okJiang** [comment]
https://prow.tidb.net/view/gs/prow-tidb-logs/pr-logs/pull/tikv_pd/10568/pull-unit-test-next-gen-2/2039992436805079040

**Comment by okJiang** [comment]
https://github.com/tikv/pd/actions/runs/24181505696/job/70575374992

**Comment by okJiang** [comment]
https://github.com/tikv/pd/actions/runs/24333121136/job/71043385808

**Comment by okJiang** [comment]
New CI link:
- https://prow.tidb.net/view/gs/prow-tidb-logs/pr-logs/pull/tikv_pd/10504/pull-unit-test-next-gen-2/2043889945168318464

**Comment by okJiang** [comment]
New CI link:
- https://github.com/tikv/pd/actions/runs/25473406231/job/74741673310

**Comment by okJiang** [comment]
### New CI links
- https://github.com/tikv/pd/actions/runs/27927165089/job/82631754070 (PR #10913)
- https://github.com/tikv/pd/actions/runs/27929131501/job/82637381035 (PR #10913)
- https://github.com/tikv/pd/actions/runs/27956522921/job/82726274542 (PR #10893)

**Comment by okJiang** [comment]
### New CI links

Observed again for `TestSchedulerTestSuite/TestSchedulerDiagnostic`:

- https://github.com/tikv/pd/actions/runs/28095073102/job/83182437461 (PR #10893)

**Comment by okJiang** [comment]
New CI link(s):
- https://prow.tidb.net/view/gs/prow-tidb-logs/pr-logs/pull/tikv_pd/10952/pull-unit-test-next-gen-2/2071794023265210368
- https://github.com/tikv/pd/actions/runs/28431345321/job/84246549720

**Comment by okJiang** [comment]
### New CI link
- https://github.com/tikv/pd/actions/runs/29013167343/job/86101517491

Observed again for `TestSchedulerTestSuite/TestSchedulerDiagnostic`.
