### ISSUE TITLE
The PD API returned the wrong message

### ISSUE THREAD

**Issue by arturiamu** [tikv/pd#7614]
### What did you do?
Send create scheduler request to pd through pd api

### What did you expect to see?
api returns correct information

### What did you see instead?
When creating a new evict-leader-scheduler, if the passed store_id does not exist, the pd api will still print ""The scheduler is created."" after returning "[PD:core:ErrStoreNotFound]store 999 not found".

### What version of PD are you using (`pd-server -V`)?
v7.5.0

### scene
```
❯ curl http://127.0.0.1:2379/pd/api/v1/schedulers
[
  "balance-region-scheduler",
  "balance-leader-scheduler",
  "balance-witness-scheduler",
  "balance-hot-region-scheduler",
  "transfer-witness-leader-scheduler"
]
❯ curl -H "Content-Type: application/json" -X POST -d '{"name": "evict-leader-scheduler", "store_id": 999}' http://127.0.0.1:2379/pd/api/v1/schedulers
"[PD:core:ErrStoreNotFound]store 999 not found"
"The scheduler is created."
```

**Comment by rleungx** [comment]
Thanks for your feedback, would you like to send a patch to fix this problem?

**Comment by arturiamu** [comment]
After my simple investigation, I found that the cause of the problem was: after the program returned an error message to the user in the `addEvictOrGrant` method, the "addEvictOrGrant" method did not return an error message to the caller `CreateScheduler`, resulting in `CreateScheduler` The method continues to return "The scheduler is created" information to the user, and since "grant-leader-scheduler" and "evict-leader-scheduler" share the "addEvictOrGrant" method, the problem also occurs in "evict-leader-scheduler".

And I'd be happy to fix this

**Comment by rleungx** [comment]
Got it, you can raise a PR for it.

**Comment by JackL9u** [comment]
The issue no longer exists.

```
> curl http://127.0.0.1:2379/pd/api/v1/schedulers
[
  "balance-region-scheduler",
  "balance-leader-scheduler",
  "balance-hot-region-scheduler",
  "evict-slow-store-scheduler"
]
> curl -H "Content-Type: application/json" -X POST -d '{"name": "evict-leader-scheduler", "store_id": 999}' http://127.0.0.1:2379/pd/api/v1/schedulers
"[PD:core:ErrStoreNotFound]store 999 not found"
```
