### ISSUE TITLE
qps recover after 3mins when all tso recover from failure lasts for 10mins

### ISSUE THREAD

**Issue by Lily2025** [tikv/pd#7821]
### What did you do?
1、run tpcc
2、inject all tso failure last for 10mins
![image](https://github.com/tikv/pd/assets/84712107/6d8b46b7-2728-4e8f-8409-ef3f76e44850)

### What did you expect to see?
qps can recover quickly when fault recover

### What did you see instead?
qps recover after 3mins when all tso recover from failure lasts for 10mins
![image](https://github.com/tikv/pd/assets/84712107/1cf1a963-3b07-49f8-9aba-2a8b9a987c7c)

### What version of PD are you using (`pd-server -V`)?
./pd-server -V
 Release Version: v7.1.1-serverless
Edition: Community
Git Commit Hash: 1b93dce40464910fb6c44deb85363a838f4c8b8e
Git Branch: release-7.1-keyspace
UTC Build Time:  2024-02-05 08:28:18
2024-02-17T13:15:00.516+0800

**Comment by rleungx** [comment]
In this case, it's better to close the old connection and recreate a new one.
