### ISSUE TITLE
Invalid package when compiling source code

### ISSUE THREAD

**Issue by Nickelth** [tikv/pd#7842]
### What did you do?

I cloned the latest repository and use "make" command. 

### What did you expect to see?

Compiling successfully.

### What did you see instead?

An error message: 
go: github.com/breeswish/gin-jwt/v2@v2.6.4-jwt-patch: invalid version: resolves to version v2.6.5-0.20211112114546-24b7fddb24dc (v2.6.4-jwt-patch is not a tag)
The problem is this line in go.mod:
github.com/breeswish/gin-jwt/v2 v2.6.4-jwt-patch // indirect
If I delete this line and use "go get github.com/breezewish/gin-jwt", then that's will be fixed.

### What version of PD are you using (`pd-server -V`)?

Version at commit#d6d9fea

**Comment by rleungx** [comment]
See https://github.com/tikv/pd/issues/5574

**Comment by Nickelth** [comment]
> See #5574

Thanks for reply.
