### ISSUE TITLE
Change the Keyspace config name for the GC management type

### ISSUE THREAD

**Issue by ystaticy** [tikv/pd#8002]
## Enhancement Task
`safe_point_version` Config name in keyspace meta config make some confuse.
It need be changed to `gc_management_type`.

If `gc_management_type` is `global_gc`, it means the current keyspace requires a tidb without 'keyspace-name'
configured to run a global gc worker to calculate a global gc safe point.
If `gc_management_type` is `keyspace_level_gc` it means the current keyspace can calculate gc safe point by its own.

**Comment by rleungx** [comment]
Close it since it has been done.
