### ISSUE TITLE
when do import on dbass，import failed "[pd] failed to get cluster id"

### ISSUE THREAD

**Issue by zhongmin-amin** [tikv/pd#8172]
### What did you do?
do import on dbass

### What did you expect to see?
import success

### What did you see instead?
import failed 
![img_v3_00as_24584fc3-4bf3-491a-9921-20cbe15fbd3g](https://github.com/tikv/pd/assets/81375082/2d41cea3-bd5d-4c20-89d2-71a43a86e17e)

### What version of PD are you using (`pd-server -V`)?
8.1.0

**Comment by lance6716** [comment]
/close

This is caused by wrong configuration at client side

**Comment by okJiang** [comment]
@lance6716 Do you want to close the issue?(It did not close)

Can you link the fixed pr/issue about the client side

**Comment by lance6716** [comment]
@okJiang Yes it can be closed but I don't have permission.

it's caused by client behaviour change https://github.com/pingcap/tidb/pull/53140
