### ISSUE TITLE
panic when exec "pd health" with tls

### ISSUE THREAD

**Issue by Lily2025** [tikv/pd#8237]
### What did you do?
1、tiup deploy cluster
2、exec "pd health" with tls
`tiup ctl:nightly pd -u https://pd1-peer:2379 health --cacert /root/.tiup/storage/cluster/clusters/tidbcluster/tls/ca.crt --cert /root/.tiup/storage/cluster/clusters/tidbcluster/tls/client.crt --key /root/.tiup/storage/cluster/clusters/tidbcluster/tls/client.pem
Starting component ctl: /root/.tiup/components/ctl/v8.2.0-alpha-nightly/ctl pd -u https://pd1-peer:2379 health --cacert /root/.tiup/storage/cluster/clusters/tidbcluster/tls/ca.crt --cert /root/.tiup/storage/cluster/clusters/tidbcluster/tls/client.crt --key /root/.tiup/storage/cluster/clusters/tidbcluster/tls/client.pem`

### What did you expect to see?
cmd can success

### What did you see instead?
cmd panic:

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x11afa05]

goroutine 1 [running]:
github.com/tikv/pd/tools/pd-ctl/pdctl/command.showHealthCommandFunc(0xc000599800, {0x14c4cf6?, 0x4?, 0x14c4bae?})
        /workspace/source/pd/tools/pd-ctl/pdctl/command/health_command.go:33 +0x25
github.com/spf13/cobra.(*Command).execute(0xc000599800, {0xc00034af00, 0x8, 0x8})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000bb800)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/tikv/pd/tools/pd-ctl/pdctl.MainStart({0xc00012c0b0, 0x9, 0x9})
        /workspace/source/pd/tools/pd-ctl/pdctl/ctl.go:105 +0x228
main.main()
        /workspace/source/pd/tools/pd-ctl/main.go:67 +0x3cf`

### What version of PD are you using (`pd-server -V`)?
    "binary_version": "v8.2.0-alpha-63-g19c9852",
    "git_hash": "19c9852decda4cb49a2319b453c4f01c6a26014f"

**Comment by JmPotato** [comment]
It was introduced by https://github.com/tikv/pd/pull/7804/files#diff-fa210a5de72cbd052e8e765c3d3798c449eb5c410868dd6007fd3c8212cb6e55R119-R120.

**Comment by okJiang** [comment]
@JmPotato why do we need check if get the cluster information successfully before init PDClient? PD client has the feature of service discover.🤔
<img width="746" alt="image" src="https://github.com/tikv/pd/assets/23556834/65b9fa22-28f3-4fee-9ea3-922b7f2c5bb5">

**Comment by JmPotato** [comment]
> @JmPotato why do we need check if get the cluster information successfully before init PDClient? PD client has the feature of service discover.🤔
> 
> <img width="746" alt="image" src="https://github.com/tikv/pd/assets/23556834/65b9fa22-28f3-4fee-9ea3-922b7f2c5bb5">
> 
> 

Because even in the interact mode, we can use `--pd/u` to connect different clusters for different commands, and each PD client can only connect to an unique cluster, it's necessary to check for each command if the client needs to be reinitialized.
