### ISSUE TITLE
`Runner.pendingTaskCount` appears somewhat unnecessary

### ISSUE THREAD

**Issue by okJiang** [tikv/pd#8244]
## Enhancement Task

It mainly is used to record metrics https://github.com/tikv/pd/blob/a929a546a790222299b556e449816e622288a5d1/pkg/ratelimit/runner.go#L130-L132

However, It will only be 1 and 0. Because `processPendingTasks` will be executed twice for each `RunTask`. https://github.com/tikv/pd/blob/a929a546a790222299b556e449816e622288a5d1/pkg/ratelimit/runner.go#L182-L187

So, even if it exists one pending task and the consumer can't consume it, the process will be block here,https://github.com/tikv/pd/blob/a929a546a790222299b556e449816e622288a5d1/pkg/ratelimit/runner.go#L157
 because the taskChan does not have any buffer 
https://github.com/tikv/pd/blob/a929a546a790222299b556e449816e622288a5d1/pkg/ratelimit/runner.go#L83

Also, now that the `RunTask` will be executed sequentially in only one function, `processRegionHeartbeat`, is it possible for it to act as a producer without locks?
https://github.com/tikv/pd/blob/a929a546a790222299b556e449816e622288a5d1/pkg/mcs/scheduling/server/cluster.go#L596

I currently don't know the background of doing this and the overall problem that needs to be solved behind it, so I don't know how to modify it appropriately now.

**Comment by okJiang** [comment]
cc @rleungx @nolouch

**Comment by rleungx** [comment]
It won't block in `case cr.taskChan <- task: `

**Comment by okJiang** [comment]
> It won't block in `case cr.taskChan <- task: `

you are right. The consumer is very quick https://github.com/tikv/pd/blob/a929a546a790222299b556e449816e622288a5d1/pkg/ratelimit/runner.go#L108-L117

The other problems are
1. Is `RunnerPendingTasks` necessary? It's almost always 0
2. Is the handling of concurrency in `RunTask` necessary? For example, the locks

**Comment by okJiang** [comment]
> If there are millions of regions, there might be lots of pending tasks.

Does PD execute `RegionHeartbeat` for each region?

https://github.com/tikv/pd/blob/fcec1882ec12655b1f1bf31c55f56aaf20dc7dfb/pkg/mcs/scheduling/server/grpc_service.go#L122

**Comment by okJiang** [comment]
PD execute RegionHeartbeat for each store.
