### ISSUE TITLE
pdms: after scale out, online number can't return to 0 even if cluster is balance

### ISSUE THREAD

**Issue by mayjiang0203** [tikv/pd#8331]
### What did you see instead?
![583a7319-6406-46e9-be71-1ed0c0264d4c](https://github.com/tikv/pd/assets/9443637/d61f8084-ab41-4589-843f-e0bc6448de08)

![b4e4c0e3-c483-49e4-b420-a36044e120a0](https://github.com/tikv/pd/assets/9443637/19e27c6b-33c7-4150-bf06-0d77976b0ff9)

### What version of PD are you using (`pd-server -V`)?
master

**Comment by rleungx** [comment]
The problem is before we calculate the progress, we need to check if the prepare checker is prepared. But if we deploy scheduling as an independent service, the prepare checker will never run, which skips the progress calculation.
