### ISSUE TITLE
BatchScanRegions need to return an error to tell client regions exist hole for retry

### ISSUE THREAD

**Issue by okJiang** [tikv/pd#8358]
## Enhancement Task

ref 

- https://github.com/tikv/client-go/pull/1377
- https://github.com/pingcap/tidb/blob/1480bb127a9363e31e8b2e9f3808289ea54d9d28/br/pkg/streamhelper/regioniter.go#L103
- https://github.com/pingcap/tidb/blob/1480bb127a9363e31e8b2e9f3808289ea54d9d28/br/pkg/restore/split/split.go#L40

**Comment by Tristan1900** [comment]
@okJiang Looks like after the proto change, TiKV code `pd_client/src/util#check_resp_header` breaks because of not handling the added error type. Curious if there is a fix already opened or in progress? Or who should be good to contact to fix it?  Thanks!

**Comment by okJiang** [comment]
> @okJiang Looks like after the proto change, TiKV code `pd_client/src/util#check_resp_header` breaks because of not handling the added error type. Curious if there is a fix already opened or in progress? Or who should be good to contact to fix it? Thanks!

If you don't set the added parameter(contain_all_key_range), it will not return the added error type(REGIONS_NOT_CONTAIN_ALL_KEY_RANGE). So can you explain which problem do you meet?

**Comment by Tristan1900** [comment]
@okJiang hmm, from my side it's a compiler error that `check_resp_header` did not exhaustively handle all the enum type
<img width="1486" alt="image" src="https://github.com/user-attachments/assets/f7b48e06-4516-4040-acfd-e76b29dd0ab9">

maybe I somehow use it wrong? I added a panic to bypass the complier to not blocking me but I don't think that's the correct way to do so asking for help.

**Comment by okJiang** [comment]
> @okJiang hmm, from my side it's a compiler error that `check_resp_header` did not exhaustively handle all the enum type. BTW I did not make any changes on pd_client, I'm working on the backup side
> 
> <img alt="image" width="1486" src="https://private-user-images.githubusercontent.com/18143892/361493549-f7b48e06-4516-4040-acfd-e76b29dd0ab9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDg3NTUsIm5iZiI6MTcyNDc0ODQ1NSwicGF0aCI6Ii8xODE0Mzg5Mi8zNjE0OTM1NDktZjdiNDhlMDYtNDUxNi00MDQwLWFjZmQtZTc2YjI5ZGQwYWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA4NDczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmM2RmNzI1MDg4MDg2ZWUzMGQ3N2M1MDRmNzA4MGZmNGJiNDM3ZWFkMTAxZjUyOTA2MDVhNGU3ZDJjOGYwOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7CDiXfG4vPqHjRA-vKeQboBzmNlfkW-ghmimeu98VCY">
> maybe I somehow use it wrong? I added a panic to bypass the complier to not blocking me but I don't think that's the correct way to do so asking for help.

I am sorry that I am not familiar with rust... @YuJuncen Can you help to reply it?😂

**Comment by Tristan1900** [comment]
@YuJuncen ok, I'm not sure how should we behave on TiKV side in response of this error so didn't add anything on my own. Sounds like this error will never happen on TiKV side? If we are sure about that I can add something.
I feel like having complier error is better in case people forgot to add the handling after changing the proto, but yeah it's cubersome.

**Comment by 3AceShowHand** [comment]
I also meet this issue, any update ?
