### ISSUE TITLE
Misuse of trace region in tso_dispatcher

### ISSUE THREAD

**Issue by zyguan** [tikv/pd#8534]
https://github.com/tikv/pd/blob/1b8fc6a950dbe658a0051c7f8228367b85bc9180/client/tso_dispatcher.go#L413-L415

Here `Region.End` should be called in reversed order, otherwise, it makes trace out broken.

![2024-08-15_154136](https://github.com/user-attachments/assets/b2d95e1e-ea62-474f-a0c6-28a74273f3f3)

**Comment by YangKeao** [comment]
For anyone who encountered this issue, please try to use https://github.com/YangKeao/go/tree/fix-tidb-trace-region this branch to view the trace. It patched the go trace tool to workaround this issue.
