### ISSUE TITLE
scheduler: there is no source filter in transferIn

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#8621]

**Comment by rleungx** [comment]
No need I think

**Comment by lhy1024** [comment]
there is no source filter in transferIn
![img_v3_02el_3df9a537-28d5-45c0-90c7-1b52db1caf5g](https://github.com/user-attachments/assets/13459abc-9af0-4510-9bf2-f9e852d9f195)

there is source filter in transferIn
![img_v3_02el_cf06b108-5823-48ec-919f-a757edee273g](https://github.com/user-attachments/assets/8051e1ec-a844-4be5-9d9b-454d4e5cf11e)

**Comment by lhy1024** [comment]
Maybe we should replace `pauseLeader` with two flags
