### ISSUE TITLE
`labelLevelStats` may leak when merging regions

### ISSUE THREAD

**Issue by rleungx** [tikv/pd#8700]
## Bug Report

Consider the following case:

1. Patrol region has scanned a batch of regions, e.g., a,b,c,d
2. Before updating label statistics, the merge finished, e.g., merge a and b
3. PD will remove one of the regions, assumed b, from label statistics because of overlaps during the process of region heartbeat.
4. Then patrol region update a,b,c,d to label statistics

b will never be deleted again and left in memory until the PD is restarted.

**Comment by okJiang** [comment]
This issue only affects metrics.

**Comment by lhy1024** [comment]
> This issue only affects metrics?

If the cluster has a high frequency of merge regions, this may cause memory growth.
