### ISSUE TITLE
TestRaftClusterMultipleRestart is timeout

### ISSUE THREAD

**Issue by lhy1024** [tikv/pd#8801]
### Which jobs are failing
```
panic: test timed out after 5m0s
	running tests:
		TestRaftClusterMultipleRestart (5m0s)
```

### CI link
https://github.com/tikv/pd/actions/runs/11775311359/job/32795518792

**Comment by okJiang** [comment]
meet again https://github.com/tikv/pd/actions/runs/11887377630/job/33120025548?pr=8820

/reopen
