### ISSUE TITLE
Failed to run UT on PC

### ISSUE THREAD

**Issue by zgcbj** [tikv/pd#8814]
## Bug Report

When I run ut with `make ci-test-job JOB_COUNT=1 JOB_INDEX=1` on PC, there are many POTENTIAL DEADLOCKs. Why doesn't github action report an error?
### What did you do?
```
git clone git@github.com:tikv/pd.git
git checkout v8.1.1
cd pd
make ci-test-job JOB_COUNT=1 JOB_INDEX=1
```

### What did you expect to see?
All UT  can pass 
### What did you see instead?
```
[2024/11/14 16:00:44.212 +08:00] [INFO] [key_manager.go:131] ["saved encryption keys"]
FAIL    github.com/tikv/pd/pkg/encryption       10.768s
ok      github.com/tikv/pd/pkg/election 72.475s coverage: 1.5% of statements in ./...
ok      github.com/tikv/pd/pkg/dashboard/adapter        1.782s  coverage: 1.1% of statements in ./...
POTENTIAL DEADLOCK: Duplicate locking, saw callers this locks in one goroutine:
current goroutine 2 lock &{{{0 0} 0 0 {{} 1} {{} 0}}}
all callers to this lock in the goroutine
sliding_window.go:118 storelimit.(*SlidingWindows).Available { s.mu.RLock() } <<<<<
limit_test.go:138 storelimit.TestFeedback.func1 { if s.Available(regionSize, SendSnapshot, constant.Low) && iter.Load() > 0 { }

sliding_window.go:151 storelimit.(*SlidingWindows).Ack { s.mu.Lock() } <<<<<
/usr/local/go23/go/src/container/list/list.go:70 list.(*List).Front { if l.len == 0 { }


Other goroutines holding locks:


FAIL    github.com/tikv/pd/pkg/core/storelimit  0.207s

```
### What version of PD are you using (`pd-server -V`)?
tag: v8.1.1

**Comment by rleungx** [comment]
Did you run tests with go 1.23?

**Comment by zgcbj** [comment]
> Did you run tests with go 1.23?
yes

**Comment by rleungx** [comment]
Deadlock detection has some issues with go 1.23. You can try 1.22 or manually upgrade the deadlock dependency to v0.3.5.

**Comment by zgcbj** [comment]
> Deadlock detection has some issues with go 1.23. You can try 1.22 or manually upgrade the deadlock dependency to v0.3.5.

go 1.22 works fine!

**Comment by rleungx** [comment]
Change the issue to question and close it, feel free to reopen it.
